/**
 * Stickering masks for <twisty-player>, in the Cubepath colour scheme.
 *
 * cubing.js hard-codes its cube palette per axis (U white, F green, R red) and
 * has no colour-scheme API, so the only way to show yellow on top / red front /
 * green right is the whole-cube setup rotation `SETUP_ALG`. That rotation
 * silently inverts every built-in `experimental-stickering` value, because a
 * stickering mask binds to the CUBIE, not to the slot — the stock OLL mask
 * would land on the bottom layer. So the player passes
 * `experimental-stickering-mask-orbits` instead, built here.
 *
 * The table below is DERIVED from cubing.js by scripts/gen-stickering.mjs and
 * pinned by tests/algs.spec.ts. Never hand-edit the generated region.
 *
 * On top of the stock mask, `maskFor` narrows the highlight to the pieces the
 * case's own algorithm actually fixes: anything already solved in the case
 * state is dimmed, so an OLL row highlights the misoriented pieces rather than
 * claiming the whole last layer.
 *
 * `maskFor` takes an optional `StageContext` (ladder + stage, see lib/ladders).
 * With one, the base mask comes from Cubepath's own ladder and carries THREE
 * tiers — highlight what this step solves, dim what an earlier step solved,
 * grey what the method has not reached — instead of cubing.js's two. Without
 * one it uses BASE_MASKS exactly as before, so every existing caller is
 * unchanged: the third tier is opt-in, per call site.
 *
 * Two invariants live in `build()` rather than in the tables, because they must
 * hold for what reaches the ATTRIBUTE and not merely for what a helper returns:
 *
 *  - A CENTRE IS NEVER GREY. Grey means "the method has not reached this
 *    piece"; a centre is fixed by definition and is the frame every recognition
 *    cue is written against. cubing.js's own `F2L` scope greys the U centre
 *    (`CENTERS:I-----`), which is how all 41 F2L cases shipped with a grey
 *    yellow centre. The ladder builds the rule in; here it is enforced on the
 *    no-ladder path too.
 *  - NARROWING IS ASPECT-AWARE. A stage that settles orientation is narrowed by
 *    orientation alone, one that settles permutation by permutation alone.
 *    Testing both, regardless of the stage, highlighted a piece whose relevant
 *    aspect was already correct on 53 of the 81 orientation/permutation cases.
 */
import { KPattern } from "cubing/kpuzzle";
import type { KPuzzle } from "cubing/kpuzzle";

import L2E_RAW from "../data/extracted/l2e-raw.json";
import type { Puzzle, Stickering } from "../data/algs";
import {
  ORBIT_KINDS,
  STAGES,
  TIER_CHARS,
  type Aspect,
  type StageContext,
  contextForCase,
  puzzleOfContext,
  stageMask,
} from "./ladders";

// <generated by scripts/gen-stickering.mjs — do not edit by hand>
export const SETUP_ALG = "x2 y";

/** Stickering -> per-piece mask chars in HOME-SLOT order, one orbit per segment. */
export const BASE_MASKS: Record<Stickering, string> = {
  "full": "EDGES:------------,CORNERS:--------,CENTERS:------",
  "Cross": "EDGES:IIII----IIII,CORNERS:IIIIIIII,CENTERS:DDDDD-",
  "F2L": "EDGES:IIII--------,CORNERS:IIII----,CENTERS:I-----",
  "LL": "EDGES:----DDDDDDDD,CORNERS:----DDDD,CENTERS:-DDDDD",
  "OLL": "EDGES:OOOODDDDDDDD,CORNERS:OOOODDDD,CENTERS:-DDDDD",
  "OCLL": "EDGES:ooooDDDDDDDD,CORNERS:OOOODDDD,CENTERS:DDDDDD",
  "PLL": "EDGES:PPPPDDDDDDDD,CORNERS:PPPPDDDD,CENTERS:DDDDDD",
  "ELL": "EDGES:----DDDDDDDD,CORNERS:DDDDDDDD,CENTERS:DDDDDD",
};

/** Puzzle -> orbit -> slot -> cubie under SETUP_ALG. Masks bind to the cubie. */
export const FRAMES: Record<Puzzle, Record<string, readonly number[]>> = {
  "3x3x3": {
    "EDGES": [5, 4, 7, 6, 1, 0, 3, 2, 8, 10, 9, 11],
    "CORNERS": [4, 5, 6, 7, 0, 1, 2, 3],
    "CENTERS": [5, 4, 3, 2, 1, 0],
  },
  "4x4x4": {
    "CORNERS": [4, 5, 6, 7, 0, 1, 2, 3],
    "EDGES": [23, 20, 21, 22, 18, 19, 16, 17, 14, 15, 12, 13, 10, 11, 8, 9, 6, 7, 4, 5, 1, 2, 3, 0],
    "CENTERS": [
      23, 20, 21, 22, 18, 19, 16, 17, 14, 15, 12, 13, 10, 11, 8, 9, 6, 7, 4, 5, 1, 2, 3, 0,
    ],
  },
  "5x5x5": {
    "EDGES": [23, 20, 21, 22, 18, 19, 16, 17, 14, 15, 12, 13, 10, 11, 8, 9, 6, 7, 4, 5, 1, 2, 3, 0],
    "EDGES2": [6, 7, 11, 8, 4, 9, 0, 1, 3, 5, 10, 2],
    "CORNERS": [4, 5, 6, 7, 0, 1, 2, 3],
    "CENTERS": [
      23, 20, 21, 22, 18, 19, 16, 17, 14, 15, 12, 13, 10, 11, 8, 9, 6, 7, 4, 5, 1, 2, 3, 0,
    ],
    "CENTERS2": [
      23, 20, 21, 22, 18, 19, 16, 17, 14, 15, 12, 13, 10, 11, 8, 9, 6, 7, 4, 5, 1, 2, 3, 0,
    ],
    "CENTERS3": [1, 0, 3, 2, 5, 4],
  },
};
// </generated>

/**
 * Colour-carrying char -> its quiet counterpart, used for pieces the algorithm
 * never touches. `I` (grey/unknown) and `D` (already dim) are left alone.
 *
 * This IS the HIGHLIGHT -> DIM demotion of the three-tier model — it is built
 * from two rows of `TIER_CHARS` in stages.json rather than restating them, so
 * it cannot drift: `-`->`D` (both), `O`->`o` (orientation), `P`->`D`
 * (permutation — there is no dim-permutation char, and `D` "solved, do not
 * care" is the right thing to say about a piece that is already placed).
 * Because it is derived, "QUIET agrees with TIER_CHARS" is no longer something
 * a test can find out; what tests/algs.spec.ts pins instead is the ALPHABET —
 * that the chars stages.json emits are still the ones `GREY` and `DIM` below
 * hard-code, which is the half of the agreement no derivation can guarantee.
 */
export const QUIET: Record<string, string> = Object.fromEntries(
  (Object.keys(TIER_CHARS.highlight) as Aspect[]).map((aspect) => [
    TIER_CHARS.highlight[aspect],
    TIER_CHARS.dim[aspect],
  ]),
);

/** "Not yet reached". Never legal on a centre — see `build`. */
const GREY = "I";
/** What a grey centre is promoted to: solved, and not this step's business. */
const DIM = "D";

/** All 24 whole-cube orientations, as in scripts/lib/kpuzzle-utils.mjs. */
const ROTATIONS: string[] = [];
for (const a of ["", "x", "x2", "x'", "z", "z'"]) {
  for (const b of ["", "y", "y2", "y'"]) ROTATIONS.push([a, b].filter(Boolean).join(" "));
}

const kpuzzles = new Map<Puzzle, Promise<KPuzzle>>();

/** Lazy so the import never follows a component into a client bundle. */
function kpuzzleFor(puzzle: Puzzle): Promise<KPuzzle> {
  let p = kpuzzles.get(puzzle);
  if (!p) {
    p = import("cubing/puzzles").then((m) => m.puzzles[puzzle]!.kpuzzle());
    kpuzzles.set(puzzle, p);
  }
  return p;
}

/** The orbits of `puzzle` whose pieces sit on one face, i.e. its centres. */
const centreOrbits = (puzzle: Puzzle): string[] =>
  Object.entries(ORBIT_KINDS[puzzle] ?? {})
    .filter(([, kind]) => kind === "center")
    .map(([orbitName]) => orbitName);

/**
 * The case state of `alg` in the STANDARD frame: solved, undone by the
 * algorithm, with any net whole-cube rotation the algorithm carries taken back
 * out. Every centre orbit has to agree, which is what pins the orientation on
 * 5x5 (its inner CENTERS3 orbit is the only one with distinguishable pieces).
 *
 * THE ROTATION GOES ON THE LEFT — the cube is turned FIRST and the algorithm
 * undone afterwards — and that is the whole content of this function. Five
 * primary PLLs carry a net rotation (Aa, Ab and Ja an `x`, E an `x'`, V an
 * interior `y`), and undoing the algorithm first and rotating the result
 * afterwards also brings the centres home, so the search finds an answer and
 * nothing looks wrong. It is the wrong answer: for `pll.aa`, a pure three-cycle
 * of U corners, it reports corners in slots 2, 6 and 7 — two of them in the
 * BOTTOM layer — and two of them twisted. The mask built from that lit one
 * corner of three. On `pll.v` it reported the right COUNT on the wrong two
 * slots, which is the version of this bug that survives a spot check.
 *
 * On a 3x3 some rotation always exists — no move on that puzzle can leave the
 * six centres in a configuration a whole-cube turn cannot undo — and
 * tests/algs.spec.ts asserts that for every case that ships. On a big cube a
 * WIDE MOVE really does displace centres, so a partial demo like `Rw U Rw'`
 * has no home orientation at all; that returns the state as written rather
 * than failing, which is the honest answer to "which pieces does this move" —
 * `caseState` falls back to the un-rotated state, `hasHomeOrientation` reports
 * that no such rotation exists. Both ask this one search.
 */
function homeState(kp: KPuzzle, puzzle: Puzzle, alg: string): KPattern | undefined {
  const orbits = centreOrbits(puzzle);
  const solved = kp.defaultPattern();
  const undo = kp.algToTransformation(alg).invert();
  for (const r of ROTATIONS) {
    const p = (r ? solved.applyAlg(r) : solved).applyTransformation(undo);
    const home = orbits.every((o) =>
      p.patternData[o]!.pieces.every((v, i) => v === solved.patternData[o]!.pieces[i]),
    );
    if (home) return p;
  }
  return undefined;
}

function caseState(kp: KPuzzle, puzzle: Puzzle, alg: string): KPattern {
  return (
    homeState(kp, puzzle, alg) ??
    kp.defaultPattern().applyTransformation(kp.algToTransformation(alg).invert())
  );
}

/** Whether some whole-cube rotation brings the case state's centres home. */
export async function hasHomeOrientation(puzzle: Puzzle, alg: string): Promise<boolean> {
  return homeState(await kpuzzleFor(puzzle), puzzle, alg) !== undefined;
}

/**
 * Cases whose real state is NOT `solved · alg⁻¹`, keyed by their algorithm.
 *
 * This is the 5x5 last-two-edges set, and it is the one place where "what the
 * algorithm fixes" and "what the case IS" come apart. An L2E algorithm is
 * written for a hold partway through reduction, so running it backwards from a
 * solved cube produces a legal state one algorithm from solved — but not the
 * position a solver meets. For `555.l2e-6` the backwards run lights the UF
 * group (the case) AND the UL and UR groups, because swapping those two is a
 * SIDE EFFECT the algorithm has on the way, and running backwards turns a side
 * effect into a precondition. The lesson names both swaps a paragraph away.
 *
 * The mask is what fixes it. The player still starts where the algorithm's
 * inverse puts it — there is no setup alg for a parity state — but the
 * highlight is computed from the DISPLAYED HOLD that `verify-l2e.mjs` exports
 * and the SVG diagram is drawn from, so those two groups come out DIM rather
 * than lit. Dim is the honest tier for them: at the pairing stage a group that
 * is intact but displaced is finished, and the 3x3 stage places it.
 *
 * Keyed by algorithm because that is what `maskFor` is given — the same idiom
 * `contextForPlayer` already resolves cases by, and the 13 L2E strings collide
 * with nothing (tests/algs.spec.ts pins that triples are near-unique).
 */
type Delta = { orbit: string; slot: number; piece: number; orientation: number };

const HOLDS: Record<string, Delta[]> = Object.fromEntries(
  (L2E_RAW as { algs: string[]; displayed?: Delta[] }[]).flatMap((c) =>
    c.displayed && c.algs[0] ? [[c.algs[0], c.displayed] as const] : [],
  ),
);

/**
 * Which pieces the algorithm fixes, per orbit, in home-slot order — i.e. the
 * pieces that are NOT already solved in the state the player starts from,
 * taken in the standard frame (see `caseState`) so that an algorithm written
 * with a whole-cube rotation reports the pieces it really moves.
 *
 * `aspect` is the stage's, and it decides what "solved" means here: an
 * orientation stage asks only whether the piece is twisted, a permutation stage
 * only whether it is in the wrong slot. Without a stage (no ladder context) the
 * question is `both`, which is what shipped before.
 */
async function touchedSlots(
  puzzle: Puzzle,
  alg: string,
  aspect: Aspect,
): Promise<Record<string, boolean[]>> {
  const kp = await kpuzzleFor(puzzle);
  const solved = kp.defaultPattern();
  const hold = HOLDS[alg];
  const state = hold ? patched(solved, hold) : caseState(kp, puzzle, alg);
  const out: Record<string, boolean[]> = {};
  for (const { orbitName } of kp.definition.orbits) {
    const d = state.patternData[orbitName]!;
    const s = solved.patternData[orbitName]!;
    out[orbitName] = d.pieces.map((p, i) => {
      const misplaced = p !== s.pieces[i];
      const twisted = d.orientation[i] !== s.orientation[i];
      if (aspect === "orientation") return twisted;
      if (aspect === "permutation") return misplaced;
      return misplaced || twisted;
    });
  }
  return out;
}

/** The solved pattern with an exported hold patched over it. */
function patched(solved: KPattern, hold: Delta[]): KPattern {
  // Per-orbit copies, never `structuredClone`: cubing.js hands every orbit of
  // the same length ONE zero-filled orientation array, and a clone preserves
  // that aliasing — see `unaliasedCopy` in scripts/verify-l2e.mjs for the bug
  // it caused there.
  const data: Record<string, { pieces: number[]; orientation: number[] }> = {};
  for (const [orbit, o] of Object.entries(solved.patternData)) {
    data[orbit] = { pieces: [...o.pieces], orientation: [...o.orientation] };
  }
  for (const d of hold) {
    const orbit = data[d.orbit];
    if (!orbit) throw new Error(`stickering: hold names unknown orbit ${d.orbit}`);
    orbit.pieces[d.slot] = d.piece;
    orbit.orientation[d.slot] = d.orientation;
  }
  return new KPattern(solved.kpuzzle, data);
}

const cache = new Map<string, Promise<string | undefined>>();

/**
 * The `experimental-stickering-mask-orbits` string for one case, or undefined
 * when no mask is needed — `full` with no ladder context, which means "show the
 * whole cube".
 *
 * `context` opts this call into the three-tier ladder (lib/ladders): the base
 * mask then says what this STEP solves, what an earlier step already solved,
 * and what the method has not reached, rather than cubing.js's highlight/dim.
 * Passing a context is also the only way to mask a `full` case — supplying a
 * stage is an explicit request for the ladder, which is what a lesson player
 * illustrating the cross, and every 4x4/5x5 case, needs.
 */
export function maskFor(
  puzzle: Puzzle,
  stickering: Stickering,
  alg: string,
  context?: StageContext,
): Promise<string | undefined> {
  const key = `${puzzle}|${stickering}|${alg}|${context ? `${context.ladder}:${context.stage}` : ""}`;
  let p = cache.get(key);
  if (!p) {
    p = build(puzzle, stickering, alg, context);
    cache.set(key, p);
  }
  return p;
}

/**
 * The un-narrowed base mask, in HOME-SLOT order: the ladder's when a context is
 * given, cubing.js's stock one otherwise. Exported so the tests can assert the
 * tier invariants on the mask the ladder produces, before `touchedSlots`
 * narrows it down to one case's algorithm.
 */
function baseMaskFor(stickering: Stickering, context?: StageContext): string | undefined {
  if (!context) return BASE_MASKS[stickering];
  const mask = stageMask(context);
  if (!mask) {
    throw new Error(
      `stickering: ladder "${context.ladder}" carries no mask for stage "${context.stage}"`,
    );
  }
  return mask;
}

async function build(
  puzzle: Puzzle,
  stickering: Stickering,
  alg: string,
  context?: StageContext,
): Promise<string | undefined> {
  if (context) {
    // A context is a request for the ladder, so a puzzle we cannot mask is a
    // build failure that names itself, never a silent drop back to one tier —
    // which is exactly how 63 big-cube cases shipped with no attribute at all.
    const want = puzzleOfContext(context);
    if (want !== puzzle) {
      throw new Error(
        `stickering: ladder "${context.ladder}" is a ${want} ladder, asked for on ${puzzle}`,
      );
    }
    if (!FRAMES[puzzle]) {
      throw new Error(`stickering: no ${SETUP_ALG} frame for ${puzzle} — run gen:stickering`);
    }
  } else if (stickering === "full" || puzzle !== "3x3x3") {
    // No ladder: "full" means show the whole cube, and the stock BASE_MASKS are
    // 3x3 scopes that would land on the wrong pieces anywhere else.
    return undefined;
  }
  const base = baseMaskFor(stickering, context);
  if (base === undefined) return undefined;
  const aspect: Aspect = context ? STAGES[context.stage].aspect : "both";
  const kinds = ORBIT_KINDS[puzzle]!;
  const frames = FRAMES[puzzle]!;
  const touched = await touchedSlots(puzzle, alg, aspect);
  return base
    .split(",")
    .map((segment) => {
      const [orbitName, chars] = segment.split(":") as [string, string];
      const frame = frames[orbitName]!;
      const isCentre = kinds[orbitName] === "center";
      const out: string[] = new Array(chars.length);
      for (let slot = 0; slot < chars.length; slot++) {
        // Centre twist is invisible on a real cube, so centres keep the stock
        // char; only edges and corners are narrowed to what the alg fixes.
        const keep = isCentre || touched[orbitName]![slot];
        const char = keep ? chars[slot]! : (QUIET[chars[slot]!] ?? chars[slot]!);
        // A centre is the reference frame every recognition cue is written
        // against, so "not yet reached" is never true of one. cubing.js's F2L
        // scope greys the U centre; the ladder never does. Enforced here so the
        // rule holds on the string that reaches the attribute, either way.
        out[frame[slot]!] = isCentre && char === GREY ? DIM : char;
      }
      return `${orbitName}:${out.join("")}`;
    })
    .join(",");
}

/**
 * The ladder context for a player that was handed nothing but a case's own
 * puzzle, stickering and algorithm — the shape `/case/[...id]` renders, and the
 * only shape a component that is not told WHICH case it is showing can resolve.
 *
 * 183 of the 185 cases are uniquely identified by that triple. The two that are
 * not are `eo.line` and `oll.45`: they share `F R U R' U' F'` and sit at
 * DIFFERENT stages (beginner/`eo` against cfop/`oll`) — which is precisely the
 * bug the yellow-cross lesson had. So an ambiguous triple resolves to NOTHING
 * rather than to a coin flip, and a caller that knows which case it is showing
 * passes `contextForCase(def)` explicitly. tests/algs.spec.ts pins both halves:
 * the coverage, and the refusal.
 */
let byAlg: Map<string, StageContext | null> | undefined;

export async function contextForPlayer(
  puzzle: Puzzle,
  stickering: Stickering,
  alg: string,
): Promise<StageContext | undefined> {
  if (!byAlg) {
    const { ALL_CASES, primaryAlg } = await import("../data/algs");
    byAlg = new Map();
    for (const def of ALL_CASES) {
      const key = `${def.puzzle}|${def.stickering}|${primaryAlg(def)}`;
      const ctx = contextForCase(def);
      const seen = byAlg.get(key);
      if (seen === undefined) byAlg.set(key, ctx);
      else if (seen === null || seen.ladder !== ctx.ladder || seen.stage !== ctx.stage) {
        byAlg.set(key, null);
      }
    }
  }
  return byAlg.get(`${puzzle}|${stickering}|${alg}`) ?? undefined;
}
