/**
 * Stickering masks for <twisty-player>, in the Cubepath colour scheme.
 *
 * cubing.js hard-codes its cube palette per axis (U white, F green, R red) and
 * has no colour-scheme API, so the only way to show yellow on top / red front /
 * green right is the whole-cube setup rotation `SETUP_ALG`. That rotation
 * silently inverts every built-in `experimental-stickering` value, because a
 * stickering mask binds to the CUBIE, not to the slot — the stock OLL mask
 * would land on the bottom layer. So the player passes
 * `experimental-stickering-mask-orbits` instead, built here.
 *
 * The table below is DERIVED from cubing.js by scripts/gen-stickering.mjs and
 * pinned by tests/algs.spec.ts. Never hand-edit the generated region.
 *
 * On top of the stock mask, `maskFor` narrows the highlight to the pieces the
 * case's own algorithm actually fixes: anything already solved in the case
 * state is dimmed, so an OLL row highlights the misoriented pieces rather than
 * claiming the whole last layer.
 */
import type { KPattern, KPuzzle } from "cubing/kpuzzle";

import type { Puzzle, Stickering } from "../data/algs";

// <generated by scripts/gen-stickering.mjs — do not edit by hand>
export const SETUP_ALG = "x2 y";

/** Stickering -> per-piece mask chars in HOME-SLOT order, one orbit per segment. */
export const BASE_MASKS: Record<Stickering, string> = {
  "full": "EDGES:------------,CORNERS:--------,CENTERS:------",
  "Cross": "EDGES:IIII----IIII,CORNERS:IIIIIIII,CENTERS:DDDDD-",
  "F2L": "EDGES:IIII--------,CORNERS:IIII----,CENTERS:I-----",
  "LL": "EDGES:----DDDDDDDD,CORNERS:----DDDD,CENTERS:-DDDDD",
  "OLL": "EDGES:OOOODDDDDDDD,CORNERS:OOOODDDD,CENTERS:-DDDDD",
  "OCLL": "EDGES:ooooDDDDDDDD,CORNERS:OOOODDDD,CENTERS:DDDDDD",
  "PLL": "EDGES:PPPPDDDDDDDD,CORNERS:PPPPDDDD,CENTERS:DDDDDD",
  "ELL": "EDGES:----DDDDDDDD,CORNERS:DDDDDDDD,CENTERS:DDDDDD",
};

/** Orbit -> slot -> cubie under SETUP_ALG. Masks bind to the cubie, not the slot. */
export const FRAME: Record<string, readonly number[]> = {
  "EDGES": [5, 4, 7, 6, 1, 0, 3, 2, 8, 10, 9, 11],
  "CORNERS": [4, 5, 6, 7, 0, 1, 2, 3],
  "CENTERS": [5, 4, 3, 2, 1, 0],
};
// </generated>

/**
 * Colour-carrying char -> its quiet counterpart, used for pieces the algorithm
 * never touches. `I` (grey/unknown) and `D` (already dim) are left alone.
 */
const QUIET: Record<string, string> = { "-": "D", O: "o", P: "D" };

/** All 24 whole-cube orientations, as in scripts/lib/kpuzzle-utils.mjs. */
const ROTATIONS: string[] = [];
for (const a of ["", "x", "x2", "x'", "z", "z'"]) {
  for (const b of ["", "y", "y2", "y'"]) ROTATIONS.push([a, b].filter(Boolean).join(" "));
}

let kpuzzlePromise: Promise<KPuzzle> | undefined;

/** Lazy so the import never follows a component into a client bundle. */
function kpuzzle(): Promise<KPuzzle> {
  kpuzzlePromise ??= import("cubing/puzzles").then((m) => m.puzzles["3x3x3"]!.kpuzzle());
  return kpuzzlePromise;
}

/** Rotate a pattern until its centres are home; throws if no rotation does. */
function centersHome(kp: KPuzzle, pattern: KPattern): KPattern {
  const solved = kp.defaultPattern().patternData.CENTERS!.pieces;
  for (const r of ROTATIONS) {
    const p = r ? pattern.applyAlg(r) : pattern;
    if (p.patternData.CENTERS!.pieces.every((v, i) => v === solved[i])) return p;
  }
  throw new Error("stickering: no rotation brings the centres home");
}

/**
 * Which pieces the algorithm fixes, per orbit, in home-slot order — i.e. the
 * pieces that are NOT already solved in the state the player starts from.
 * The state is re-oriented so its centres are home first, so an algorithm
 * written with a whole-cube rotation does not report every piece as touched.
 */
async function touchedSlots(alg: string): Promise<Record<string, boolean[]>> {
  const kp = await kpuzzle();
  const solved = kp.defaultPattern();
  const state = centersHome(kp, solved.applyTransformation(kp.algToTransformation(alg).invert()));
  const out: Record<string, boolean[]> = {};
  for (const { orbitName } of kp.definition.orbits) {
    const d = state.patternData[orbitName]!;
    const s = solved.patternData[orbitName]!;
    out[orbitName] = d.pieces.map(
      (p, i) => p !== s.pieces[i] || d.orientation[i] !== s.orientation[i],
    );
  }
  return out;
}

const cache = new Map<string, Promise<string | undefined>>();

/**
 * The `experimental-stickering-mask-orbits` string for one case, or undefined
 * when no mask is needed. Big cubes are all `full` (and `full` is rotation-
 * invariant), so they get none.
 */
export function maskFor(
  puzzle: Puzzle,
  stickering: Stickering,
  alg: string,
): Promise<string | undefined> {
  const key = `${puzzle}|${stickering}|${alg}`;
  let p = cache.get(key);
  if (!p) {
    p = build(puzzle, stickering, alg);
    cache.set(key, p);
  }
  return p;
}

async function build(
  puzzle: Puzzle,
  stickering: Stickering,
  alg: string,
): Promise<string | undefined> {
  // Big cubes only ever use "full", and "full" is rotation-invariant, so
  // neither needs a mask — "full" means "show the whole cube", untouched.
  if (puzzle !== "3x3x3" || stickering === "full") return undefined;
  const touched = await touchedSlots(alg);
  return BASE_MASKS[stickering]
    .split(",")
    .map((segment) => {
      const [orbitName, chars] = segment.split(":") as [string, string];
      const frame = FRAME[orbitName]!;
      const out: string[] = new Array(chars.length);
      for (let slot = 0; slot < chars.length; slot++) {
        const char = chars[slot]!;
        // Centre twist is invisible on a real cube, so centres keep the stock
        // char; only edges and corners are narrowed to what the alg fixes.
        const keep = orbitName.startsWith("CENTER") || touched[orbitName]![slot];
        out[frame[slot]!] = keep ? char : (QUIET[char] ?? char);
      }
      return `${orbitName}:${out.join("")}`;
    })
    .join(",");
}
