"""Printable card set: imposition, build gates and the CLI.

Four ID-1 panels (85.6 x 53.98 mm) — three numbered progression cards and one
annex. What each card *says* lives in `cards.py`; this module lays them out on
paper, compiles them and refuses to ship a broken one.

Nothing here retypes an algorithm. Every 3x3 string comes from `algs.py` via
`notation.CHUNKS` or `notation.PLL_CHUNKS`; every big-cube string is read out
of the app script that pins it for CI; recognition wording is generated by
`recognition.py`. Colour is derived by exact-token lookup in `palette.FAMILY`,
never assigned by hand.

Four failure modes this module actively guards, because each one silently
ships a wrong card:

*   Typst's smart quotes rewrite every ASCII prime to U+2019, which cubing.js
    refuses to parse — `#set smartquote(enabled: false)` plus a gate.
*   Typst exits 0 on an unknown font family, so a macOS-only font compiles
    clean here and falls back to something else everywhere else — the build
    runs `--ignore-system-fonts` and treats warnings as errors.
*   Typst silently paginates on overflow, so a too-full card becomes a third
    page instead of an error — the build asserts the page count and geometry.
*   A duplex imposition that pairs the wrong front with the wrong back looks
    perfect on a proof sheet. The row-duplication theorem is asserted, not
    assumed (see `_duplex`).
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
from pathlib import Path

from cubepath.cards import (
    CARD_H,
    CARD_W,
    COL_W,
    DECK,
    FRONT_SLOTS,
    MARGIN,
    USABLE_W,
    Card,
)
from cubepath.diagrams import CARD, all_cases, render, render_step
from cubepath.fullsets import card_pll_cases
from cubepath.glossary import BANNED
from cubepath.notation import BIGCUBE_CHUNKS, CHUNKS, PLL_CHUNKS, compact
from cubepath.palette import TRIGGER_COLORS
from cubepath.typst import esc, prime

_REPO = Path(__file__).resolve().parents[4]
_GUIDE = _REPO / "guide"
_OUT = _GUIDE / "build" / "cards"
_CARD_SVG = _OUT / "card-svg"

USABLE_H = CARD_H - 2 * MARGIN  # 49.98 — identity band, content and footer
IDENT_H, FOOT_H = 2.40, 2.60  # nominal; the gate measures what they really take
CONTENT_H = USABLE_H - IDENT_H - FOOT_H  # 44.98, the plan's column budget

# L* 78 / 62 / 46 / 88 as 8-bit greys. A descending lightness ramp survives
# photocopying as an ordinal staircase; it is deliberately not the vivid
# trigger hues, so the two colour systems cannot be read as one code.
_TINT = {78: 193, 62: 150, 46: 109, 88: 221}


# ── Print-variant diagrams ────────────────────────────────────────────
# The cards re-render every diagram in `diagrams.CARD` style rather than
# post-processing the screen SVG. That is the difference between a palette
# that is chosen and gated (`palette.contrast`) and a list of hex-string
# substitutions that silently stops matching the day diagrams.py changes.


def build_print_svgs() -> dict[str, int]:
    """Re-render every diagram the cards use, in card style."""
    from cubepath.diagrams import (
        _align_edge_cases,
        _corner_case_steps,
        _corner_pos_case,
        _edge_case_steps,
        _orient_corner_case,
        _orient_corner_cases_15,
        _step_cases,
    )

    if _CARD_SVG.exists():
        shutil.rmtree(_CARD_SVG)
    counts: dict[str, int] = {}

    def bump(path: Path) -> None:
        counts[path.parent.name] = counts.get(path.parent.name, 0) + 1

    for case in all_cases():
        bump(render(case, _CARD_SVG, style=CARD))
    # Card 3 renders from the algorithm it prints, never from JPerm's primary:
    # the repo's Z-Perm and JPerm's solve states differing by a `y` rotation.
    for case in card_pll_cases():
        bump(render(case, _CARD_SVG, style=CARD))
    steps = (
        _step_cases()
        + _corner_case_steps()
        + _edge_case_steps()
        + _orient_corner_cases_15()
        + _align_edge_cases()
        + [_orient_corner_case(), _corner_pos_case()]
    )
    for step in steps:
        bump(render_step(step, _CARD_SVG, style=CARD))

    if set(counts) != {"oll", "pll", "pll-full", "steps"}:
        raise AssertionError(f"unexpected card diagram categories: {sorted(counts)}")
    return counts


# ── Typst preamble ────────────────────────────────────────────────────


def _preamble() -> str:
    cr, cg, cb = (TRIGGER_COLORS[k] for k in "rgb")
    return f"""// GENERATED by cubepath-cards — do not edit by hand.
// Every algorithm is expanded from tools/diagrams/src/cubepath/algs.py via
// notation.CHUNKS / PLL_CHUNKS; every big-cube string is read from the app
// script that pins it for CI; every recognition cue is generated by
// recognition.py. Editing this file will be overwritten on the next build.

#let style(body) = {{
  // Typst rewrites ASCII primes to U+2019, which cubing.js refuses to parse.
  set smartquote(enabled: false)
  set text(font: "Libertinus Serif", size: 4.2pt)
  set par(leading: 0.20em, spacing: 0.20em)
  set block(spacing: 0.30em)
  body
}}

#let M  = "DejaVu Sans Mono"   // the only mono font Typst bundles
#let CR = rgb("#{cr}")
#let CG = rgb("#{cg}")
#let CB = rgb("#{cb}")
// The regrip gap must dominate whatever separates moves *inside* a chunk, and
// that differs by block — so there are two, both measured at 600dpi:
//   compacted blocks: widest intra-chunk gap is 0.34mm, so 0.55em (1.55mm,
//     4.6x) is unambiguous.
//   spaced blocks (big cubes keep real spaces): an ordinary space already
//     measures 1.50mm, so 0.55em would be 1.03x and the break would vanish.
#let GAP  = 0.55em
#let GAPW = 0.90em

// In monospace the prime gets a full character cell, so "R'" reads as two
// separate glyphs with a gap between them. Narrow its advance and pull it
// left so it binds to the letter it modifies. Measured at 600dpi: 0.38mm
// before, 1.36mm after, and ~19% width back on prime-heavy algorithms.
#let pr() = box(width: 0.22em, move(dx: -0.20em, text("'")))

#let a(sz, ..p)  = text(font: M, size: sz, weight: "bold")[#p.pos().join(h(GAP))]
#let aw(sz, ..p) = text(font: M, size: sz, weight: "bold")[#p.pos().join(h(GAPW))]
#let r(t) = text(fill: CR, t)
#let g(t) = text(fill: CG, t)
#let b(t) = text(fill: CB, t)
#let dia(f, w, rot: 0deg) = {{
  let i = image("card-svg/" + f, width: w)
  if rot != 0deg {{ box(rotate(rot, i)) }} else {{ i }}
}}
#let hdr(n, t, s) = block(above: 0.5mm, below: 0.35mm)[
  #text(size: 4.8pt, weight: "bold")[#if n != [] [#n#h(0.5mm)]#upper(t)]
  #if s != [] [#text(size: 3.8pt, fill: luma(95))[ · #s]]]
#let nm(t)  = text(size: 4.0pt, weight: "bold")[#t]
#let cue(t) = text(size: 4.0pt, fill: luma(72))[#t]
#let sw(c)  = box(baseline: 0pt, rect(width: 0.9mm, height: 0.9mm, fill: c, stroke: none))
#let mn(t)  = text(font: M, weight: "bold", size: 4.2pt)[#t]
#let key(t) = text(size: 4.0pt, fill: luma(60))[#t]
#let lbl(t) = text(size: 4.1pt, weight: "bold")[#t]
// The Sune fallback badge. Its number is BFS output (recognition.py), not a
// claim — "at most three Sunes" is measured on the simulator.
#let bdg(n) = box(baseline: 0.15mm, inset: (x: 0.25mm), outset: (y: 0.15mm),
  radius: 0.3mm, fill: luma(225))[#text(size: 3.4pt, weight: "bold")[#n]]

#let D  = 4.65mm   // OLL, three to a block
#let DS = 5.5mm    // step and OLL rows with room to breathe
#let DC = 5.5mm    // PLL corners — headlights is a coarse recognition
#let DP = 6.2mm    // PLL edges — the cycle arrows need the extra size
#let DF = 5.8mm    // Card 3, all 21 — 21 rows buy their size back
#let AS = 6.5pt    // every algorithm
#let AB = 6.5pt
#let AP = 6.5pt

#let pad(t) = box(width: 5.53mm)[#t]   // measured width of "3Rw'" at 6.5pt

// A 20 mm tick on every card back, so a card cut out of a sheet still carries
// its own scale check — sheet furniture does not survive the scissors.
#let tick20() = box(baseline: 0.2mm)[
  #box(width: 20mm, height: 1.0mm)[
    #place(bottom + left, rect(width: 20mm, height: 0.25mm, fill: luma(40)))
    #place(bottom + left, rect(width: 0.2mm, height: 1.0mm, fill: luma(40)))
    #place(bottom + right, rect(width: 0.2mm, height: 1.0mm, fill: luma(40)))]
  #text(size: 3.4pt, fill: luma(60))[ 20 mm]]

// Identity band. The numeral sits at the end opposite the punch corner, so a
// manual-duplex print with the wrong flip is caught after cutting ONE card
// (front says 1, back says 2) instead of after wasting the sheet.
#let ident(id, face, title, filled, tint) = block(below: 0.45mm)[
  #grid(columns: (1fr, auto), align: (left + horizon, right + horizon),
    text(size: 4.4pt, weight: "bold")[#upper(title)],
    text(size: 4.0pt, weight: "bold")[
      #for i in range(3) [#if i < filled [#sym.square.filled] else [#sym.square.stroked]]
      #h(0.6mm) #id · #face])
  #v(-0.35mm)
  #line(length: 100%, stroke: 0.9pt + luma(tint))]

// Two columns with a hairline between them. The rule is drawn at the height
// of the taller column, not the card, so it stops above the footer instead of
// spearing it.
// The divider is a grid stroke, not a `line(length: 100%)` cell: a percentage
// length resolves against the container, so a rule cell spears the footer
// instead of stopping at the taller column.
#let cols(a, b) = grid(
  columns: ({COL_W}mm, {COL_W}mm), column-gutter: 1.2mm,
  stroke: (x, y) => if x == 1 {{ (left: 0.35pt + luma(170)) }},
  inset: (x: 0.5mm), align: (top, top), a, b)
#let full(a) = block(width: 100%, a)

// The gate that replaces hand arithmetic. A fixed-height content block does
// not paginate when it overruns — it silently overlaps the footer, which the
// page-count gate cannot see. So measure the real rendered height and refuse
// to compile. This is why every column budget in docs/card-set-plan.md can be
// trusted: nothing checks them by eye.
#let fit(name, body) = context {{
  let h = measure(block(width: {USABLE_W}mm, body)).height
  if h > {USABLE_H}mm {{
    panic("card overflows: " + name + " needs "
      + str(calc.round(h.mm(), digits: 2)) + "mm of " + str({USABLE_H}) + "mm")
  }}
  body
}}

// The footer is a block in the flow, not an absolutely-placed box. Placed
// absolutely it grows *upward* into the content when it runs to four lines,
// which no content-height gate can see — that is exactly how Card 3's map
// footer collided with its own glossary.
#let foot(body) = block(width: 100%, above: 0.45mm, breakable: false,
  inset: (top: 0.35mm), stroke: (top: 0.4pt + luma(160)),
  text(size: 3.7pt, fill: luma(55))[#body])
"""


# ── Card bodies ───────────────────────────────────────────────────────


def _footer(card: Card, face: str) -> str:
    """Front footer carries the trigger legend; back carries the ladder."""
    if face == "front":
        legend = " ".join(
            f"#sw(C{f.upper()})~#mn[{prime(compact(t))}]~{label}#h(1.1mm)"
            for f, t, label in (
                ("r", "R U R' U'", "sexy move"),
                ("g", "R U R' U", "Sune"),
                ("b", "R' F R F'", "sledgehammer"),
            )
        )
        return f"#foot[{legend} gap = change grip]"

    lines = [esc(n) for n in card.notes]
    if card.unlock:
        tail = esc(card.unlock)
        if card.master:
            tail += f" #sym.square.stroked {esc(card.master)}"
        if card.next_title:
            tail += f" · NEXT: {esc(card.next_title)}"
        lines.append(tail)
    lines.append("#tick20()")
    return "#foot[" + " \\\n".join(lines) + "]"


def _section(sec: str | tuple[str, str]) -> str:
    if isinstance(sec, str):
        return f"#full([\n{sec}\n])"
    left, right = sec
    return f"#cols([\n{left}\n], [\n{right}\n])"


def _card_body(card: Card, face: str) -> str:
    sections = (card.front if face == "front" else card.back)()
    letter = "A" if face == "front" else "B"
    body = "\n".join(_section(s) for s in sections)
    # The content block is exactly CONTENT_H tall. That is what makes the
    # column rule stop above the footer, and it is the budget every column in
    # docs/card-set-plan.md is costed against.
    return f"""#let body-{card.index}-{face} = [
#ident([{card.ident}], [{letter}], [{esc(card.title)}], {card.filled}, {_TINT[card.tint_L]})
{body}
{_footer(card, face)}
]
#let card-{card.index}-{face} = box(width: {CARD_W}mm, height: {CARD_H}mm,
  inset: {MARGIN}mm)[
#style(fit("{card.slug} {face}", body-{card.index}-{face}))]
"""


def write_sources(strict: bool = True) -> Path:
    """Write the shared card body module and one per-card entry point.

    `strict=False` turns the overflow gate into a pass-through, so
    `measure_faces` can report every face's height instead of stopping at the
    first one that overruns.
    """
    _OUT.mkdir(parents=True, exist_ok=True)
    body = _OUT / "card-body.typ"
    preamble = _preamble()
    if not strict:
        # Replace the whole gate, not just its `context` head: the body still
        # calls measure(), which is only legal inside a context expression.
        head = preamble.index("#let fit(name, body) = context {")
        tail = preamble.index("\n", preamble.index("  body\n}}".replace("}}", "}"), head))
        preamble = preamble[:head] + "#let fit(name, body) = body" + preamble[tail:]
    body.write_text(
        preamble + "\n" + "\n".join(_card_body(c, f) for c in DECK for f in ("front", "back"))
    )
    for c in DECK:
        (_OUT / f"card-{c.index}-{c.slug}.typ").write_text(
            '#import "card-body.typ": *\n'
            f"#set page(width: {CARD_W}mm, height: {CARD_H}mm, margin: 0pt)\n"
            f"#card-{c.index}-front\n#pagebreak()\n#card-{c.index}-back\n"
        )
    return body


# ── Imposition ────────────────────────────────────────────────────────

SHEETS = {"a4": (210.0, 297.0), "letter": (215.9, 279.4)}

# Back-sheet slot s lands behind front slot sigma[s].
SIGMA_LONG = [1, 0, 3, 2, 5, 4, 7, 6]  # (r,c) -> (r, 1-c); content upright
SIGMA_SHORT = [6, 7, 4, 5, 2, 3, 0, 1]  # (r,c) -> (3-r, c); + whole-page 180
RHO = [7 - s for s in range(8)]  # whole-page 180 rotation


def _slots(w: float, h: float, cols: int, rows: int) -> tuple[list[float], list[float]]:
    x0, y0 = (w - cols * CARD_W) / 2, (h - rows * CARD_H) / 2
    return (
        [x0 + i * CARD_W for i in range(cols)],
        [y0 + i * CARD_H for i in range(rows)],
    )


def _cut_guides(w: float, h: float, xs: list[float], ys: list[float]) -> str:
    """Hairlines across the sheet plus solid ticks in the margins — one
    straight cut serves a whole column."""
    bw, bh = len(xs) * CARD_W, len(ys) * CARD_H
    x0, y0 = xs[0], ys[0]
    parts = []
    for x in xs + [x0 + bw]:
        parts.append(
            f"  #place(top + left, dx: {x}mm, dy: 0mm, "
            f"rect(width: 0.07mm, height: {h}mm, fill: luma(190)))"
        )
        for dy in (y0 - 3, y0 + bh):
            parts.append(
                f"  #place(top + left, dx: {x - 0.05}mm, dy: {dy}mm, "
                f"rect(width: 0.1mm, height: 3mm, fill: black))"
            )
    for y in ys + [y0 + bh]:
        parts.append(
            f"  #place(top + left, dx: 0mm, dy: {y}mm, "
            f"rect(width: {w}mm, height: 0.07mm, fill: luma(190)))"
        )
        for dx in (x0 - 3, x0 + bw):
            parts.append(
                f"  #place(top + left, dx: {dx}mm, dy: {y - 0.05}mm, "
                f"rect(width: 3mm, height: 0.1mm, fill: black))"
            )
    return "\n".join(parts)


def _strip(x0: float, bw: float, dy: float, text: str) -> str:
    return (
        f"  #place(top + left, dx: {x0}mm, dy: {dy}mm, box(width: {bw}mm)[\n"
        f"    #text(size: 7pt)[{text}]\n"
        f"    #box(width: 80mm, height: 1.4mm)[\n"
        f"      #place(bottom + left, rect(width: 80mm, height: 0.4mm, fill: black))\n"
        f"      #place(bottom + left, rect(width: 0.3mm, height: 1.4mm, fill: black))\n"
        f"      #place(bottom + right, rect(width: 0.3mm, height: 1.4mm, fill: black))]\n"
        f"  ])"
    )


def check_row_duplication() -> None:
    """The theorem the whole duplex scheme rests on.

    `FRONT_SLOTS[2k] == FRONT_SLOTS[2k+1]` is what makes the long-edge back
    page need *no* transform and the short-edge back page need exactly one
    whole-page rotation. A future reorder that interleaves cards silently
    scrambles every duplex print with no visible symptom on a proof sheet.
    """
    f = FRONT_SLOTS
    assert len(f) == 8, f"the sheet holds 8 slots, deck lays out {len(f)}"
    assert all(f[2 * k] == f[2 * k + 1] for k in range(4)), f"front list is not row-duplicated: {f}"
    assert [f[SIGMA_LONG[s]] for s in range(8)] == f, "long-edge back page is not the identity"
    assert [f[SIGMA_SHORT[s]] for s in range(8)] == f[::-1], "short-edge back page is not reversed"
    assert SIGMA_SHORT == [RHO[SIGMA_LONG[s]] for s in range(8)], "sigma_short != rho . sigma_long"
    assert all(SIGMA_LONG[SIGMA_LONG[s]] == s for s in range(8)), "sigma_long is not an involution"
    assert all(SIGMA_SHORT[SIGMA_SHORT[s]] == s for s in range(8)), (
        "sigma_short is not an involution"
    )


def check_mirror(w: float, h: float) -> None:
    """Centred grids register under either flip. Never compare floats with
    `==`: 40.54 + 202.48 + 53.98 sums to 297.00000000000006."""
    xs, ys = _slots(w, h, 2, 4)
    assert abs(xs[0] + xs[1] + CARD_W - w) <= 0.01, xs
    for r in range(2):
        assert abs(ys[r] + ys[3 - r] + CARD_H - h) <= 0.01, ys


def _duplex(w: float, h: float, flip: str) -> str:
    """Two complete sets per sheet, 2 x 4, for the named flip only.

    Never one file claiming to work under either setting: a naive whole-page
    180 rotation maps (r,c) -> (r, 1-c), which degenerates into the long-edge
    column swap and pairs Card 1's front with Card 2's back. That is invisible
    on a sheet of identical cards, which is how it survived until now.
    """
    check_row_duplication()
    check_mirror(w, h)
    xs, ys = _slots(w, h, 2, 4)
    bw = 2 * CARD_W
    guides = _cut_guides(w, h, xs, ys)
    note = (
        f"Print at 100% / Actual size — do NOT fit to page. Two-sided, flip on the "
        f"{flip.upper()} edge. The numeral on both faces is your check: cut ONE card first. "
        f"This bar must measure exactly 80 mm:"
    )
    strips = (
        _strip(xs[0], bw, ys[0] - 9, note)
        + "\n"
        + _strip(xs[0], bw, ys[0] + 4 * CARD_H + 4.5, note)
    )

    def face(which: str) -> str:
        cells = []
        for s in range(8):
            x, y = xs[s % 2], ys[s // 2]
            cells.append(
                f"  #place(top + left, dx: {x}mm, dy: {y}mm, card-{FRONT_SLOTS[s]}-{which})"
            )
        return "\n".join(cells)

    back = f"{guides}\n{strips}\n{face('back')}"
    if flip == "short":
        # Emitting the same slot order and rotating the page places the card
        # laid at slot k physically at rho[k] = 7-k, so physical slot s gets
        # F[7-s] = reverse(F) — exactly what sigma_short requires.
        back = (
            f"#rotate(180deg, origin: center + horizon, block(width: {w}mm, height: {h}mm)[\n"
            f"{back}\n])"
        )
    return f"""#import "card-body.typ": *
#set page(width: {w}mm, height: {h}mm, margin: 0pt)
#[
{guides}
{strips}
{face("front")}
]
#pagebreak()
#[
{back}
]
"""


_FOLD_NOTE = (
    "Print at 100% / Actual size, SINGLE-sided. Crease along the grey line, fold so both "
    "printed faces are outward, glue, then cut."
)


def _foldover(w: float, h: float, indices: list[int]) -> str:
    """One single-sided sheet: back rotated 180 above the front, sharing the
    fold edge. No duplexer, no registration error, no flip choice."""
    panel_h = 2 * CARD_H
    bw, bh = 2 * CARD_W, 2 * panel_h
    x0, y0 = (w - bw) / 2, (h - bh) / 2
    cells = []
    for i, idx in enumerate(indices):
        r, c = divmod(i, 2)
        x, y = x0 + c * CARD_W, y0 + r * panel_h
        cells.append(f"  #place(top + left, dx: {x}mm, dy: {y}mm, rotate(180deg, card-{idx}-back))")
        cells.append(f"  #place(top + left, dx: {x}mm, dy: {y + CARD_H}mm, card-{idx}-front)")
        cells.append(
            f"  #place(top + left, dx: {x}mm, dy: {y + CARD_H - 0.05}mm, "
            f"rect(width: {CARD_W}mm, height: 0.1mm, fill: luma(150)))"
        )
    return f"""#import "card-body.typ": *
#set page(width: {w}mm, height: {h}mm, margin: 0pt)
#place(top + left, dx: {x0}mm, dy: {y0 - 7}mm, box(width: {bw}mm)[
  #text(size: 7pt)[{_FOLD_NOTE}]
])
{chr(10).join(cells)}
"""


# ── Build + gates ─────────────────────────────────────────────────────


def _compile(src: Path, pdf: Path) -> None:
    """Compile with only bundled fonts, treating warnings as errors.

    Typst exits 0 on an unknown font family, so a macOS-only font would
    compile clean here and silently fall back everywhere else.
    """
    proc = subprocess.run(
        ["typst", "compile", "--ignore-system-fonts", "--root", str(_GUIDE), str(src), str(pdf)],
        capture_output=True,
    )
    if proc.returncode != 0:
        raise SystemExit(proc.stderr.decode() or f"typst failed on {src}")
    if b"warning:" in proc.stderr:
        raise AssertionError(f"typst warnings compiling {src}:\n{proc.stderr.decode()}")


def _pdfinfo(pdf: Path) -> dict[str, str]:
    out = subprocess.run(["pdfinfo", str(pdf)], capture_output=True, text=True).stdout
    return dict(
        (k.strip(), v.strip())
        for k, _, v in (line.partition(":") for line in out.splitlines())
        if k
    )


def pdf_text(pdf: Path) -> str:
    return subprocess.run(["pdftotext", str(pdf), "-"], capture_output=True, text=True).stdout


_LEAKS = ("a(AB,", "aw(AB,", "a(AP,", "a(AS,", "#a(", "#aw(", "cue[", "lbl[", "bdg[", "hdr[")


def gate_card(card: Card, pdf: Path) -> str:
    """Assert one card is two ID-1 pages of legible, un-banned content."""
    info = _pdfinfo(pdf)
    if info.get("Pages") != "2":
        raise AssertionError(
            f"{card.slug}: must be exactly 2 pages, got {info.get('Pages')} — "
            "content overflowed and Typst paginated silently"
        )
    want_w, want_h = CARD_W * 72 / 25.4, CARD_H * 72 / 25.4
    m = re.match(r"([\d.]+) x ([\d.]+)", info.get("Page size", ""))
    if not m or abs(float(m.group(1)) - want_w) > 0.1 or abs(float(m.group(2)) - want_h) > 0.1:
        raise AssertionError(
            f"{card.slug}: page size {info.get('Page size')} != {want_w:.3f} x {want_h:.3f} pt"
        )

    text = pdf_text(pdf)
    for bad, label in (("’", "U+2019 right single quote"), ("′", "U+2032 prime")):
        if bad in text:
            raise AssertionError(
                f"{card.slug}: {label} in the PDF — smartquote is rewriting primes "
                "and cubing.js cannot parse the printed algorithms"
            )

    flat = re.sub(r"\s+", "", text)
    for leak in _LEAKS:
        if leak.replace(" ", "") in flat:
            raise AssertionError(f"{card.slug}: raw Typst markup {leak!r} rendered as text")

    for term in BANNED:
        if re.search(rf"(?<![A-Za-z]){re.escape(term)}(?![A-Za-z])", text, re.IGNORECASE):
            raise AssertionError(
                f"{card.slug}: banned term {term!r} reached the card — write "
                f"{BANNED[term]!r} instead"
            )

    if "20 mm" not in text:
        raise AssertionError(f"{card.slug}: no 20 mm calibration tick on the back")
    return text


def gate_deck(texts: dict[str, str]) -> None:
    """Every algorithm the set claims to teach must be on some card, in the
    form that card prints it."""
    flat = re.sub(r"\s+", "", "".join(texts.values()))
    missing = [
        k
        for k, chunks in {**CHUNKS, **PLL_CHUNKS}.items()
        if not all(compact(seg) in flat for chunk in chunks for seg in chunk)
    ]
    missing += [
        k
        for k, chunks in BIGCUBE_CHUNKS.items()
        if not all(re.sub(r"\s+", "", seg) in flat for chunk in chunks for seg in chunk)
    ]
    if missing:
        raise AssertionError(f"algorithms missing from the rendered set: {sorted(set(missing))}")


def manifest() -> list[dict]:
    """One ordered table driving the app ladder and the print page."""
    return [
        {
            "index": c.index,
            "route": f"/c{c.index}",
            "slug": c.slug,
            "title": c.title,
            "num": c.num,
            "of": 3 if c.num else None,
            "unlock": c.unlock,
            "master": c.master,
            "next": c.next_title,
            "next_slug": DECK[c.index + 1].slug if c.index + 1 < len(DECK) - 1 else None,
            "supersedes": c.supersedes,
            "superseded_by": c.superseded_by,
            "card_pdf": f"card-{c.index}-{c.slug}.pdf",
            "fold_pdf": {s: f"card-{c.index}-{c.slug}-fold-{s}.pdf" for s in SHEETS},
        }
        for c in DECK
    ]


def measure_faces() -> dict[str, float]:
    """Rendered content height of every card face, in mm. Diagnostic only —
    the build gate lives in the Typst source so a bad card cannot compile."""
    write_sources(strict=False)
    src = _OUT / "_measure.typ"
    lines = [
        '#import "card-body.typ": *',
        "#set page(width: 400mm, height: auto, margin: 4mm)",
    ]
    for c in DECK:
        for f in ("front", "back"):
            lines.append(
                f"#context [{c.slug}|{f}|"
                f"#calc.round(measure(block(width: {USABLE_W}mm, "
                f"style(body-{c.index}-{f}))).height.mm(), digits: 2)|MM\\ ]"
            )
    src.write_text("\n".join(lines))
    pdf = _OUT / "_measure.pdf"
    _compile(src, pdf)
    out = {}
    for line in pdf_text(pdf).splitlines():
        line = line.strip().replace(" ", "")
        if "|MM" not in line:
            continue
        slug, face, mm, _ = line.split("|")
        out[f"{slug} {face}"] = float(mm)
    src.unlink()
    pdf.unlink()  # diagnostic only — never ship it next to the real cards
    write_sources(strict=True)
    return out


def main() -> None:
    counts = build_print_svgs()
    write_sources()
    outputs, texts = [], {}

    for c in DECK:
        pdf = _OUT / f"card-{c.index}-{c.slug}.pdf"
        _compile(_OUT / f"card-{c.index}-{c.slug}.typ", pdf)
        texts[c.slug] = gate_card(c, pdf)
        outputs.append(pdf)
    gate_deck(texts)

    for name, (w, h) in SHEETS.items():
        jobs = [(f"deck-{name}-fold", _foldover(w, h, [c.index for c in DECK]))]
        for flip in ("long", "short"):
            jobs.append((f"deck-{name}-duplex-{flip}", _duplex(w, h, flip)))
        for c in DECK:
            jobs.append((f"card-{c.index}-{c.slug}-fold-{name}", _foldover(w, h, [c.index] * 4)))
        for stem, source in jobs:
            src = _OUT / f"{stem}.typ"
            src.write_text(source)
            out = _OUT / f"{stem}.pdf"
            _compile(src, out)
            outputs.append(out)

    payload = json.dumps(manifest(), indent=2) + "\n"
    (_OUT / "manifest.json").write_text(payload)
    # The app imports this at build time to render the frozen /c0../c3 routes,
    # so the ladder on the web is the deck table, never a second copy of it.
    (_REPO / "app" / "src" / "data" / "cards.json").write_text(payload)
    print(f"card-style diagrams re-rendered: {sum(counts.values())} ({counts})")
    print(f"  {(_OUT / 'manifest.json').relative_to(_REPO)}")
    for o in outputs:
        print(f"  {o.relative_to(_REPO)}")


if __name__ == "__main__":
    main()
