/**
 * Generate src/data/fullsets.gen.ts from the verified extraction
 * (src/data/extracted/jperm-raw.json). Also emits case "visual facts"
 * (for recognition-text writing) to a build-side JSON that never ships.
 *
 * Usage: node scripts/gen-cases.mjs
 */
import { readFile, writeFile } from "node:fs/promises";

const raw = JSON.parse(
  await readFile(new URL("../src/data/extracted/jperm-raw.json", import.meta.url), "utf8"),
);

const slug = (s) =>
  String(s)
    .replace(/\+$/, " plus")
    .replace(/-$/, " minus")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

const MAX_SCRAMBLES = 8;

function ollProbability(prob) {
  // JPerm OLL probs are numerators over 216.
  return prob ? `${prob}/216` : undefined;
}
function pllProbability(prob) {
  // JPerm PLL probs are numerators over 18 (T=1 → 1/18, N=0.25 → 1/72).
  if (!prob) return undefined;
  if (Number.isInteger(prob)) return `${prob}/18`;
  const denom = Math.round(18 / prob);
  return `1/${denom}`;
}

const cases = [];
const scrambles = {};

for (const c of raw.oll) {
  const id = `oll.${Number(c.name)}`;
  cases.push({
    id,
    group: `oll-${slug(c.group)}`,
    name: `OLL ${c.name}`,
    recognition: `${c.group} shape`, // placeholder — replaced by the recognition workflow
    algs: c.algs.map((moves, i) => ({ moves, ...(i === 0 ? { primary: true } : {}) })),
    stickering: "OLL",
    puzzle: "3x3x3",
    probability: ollProbability(c.prob),
    phase: "full-oll",
  });
  scrambles[id] = c.scrambles.slice(0, MAX_SCRAMBLES);
}

for (const c of raw.pll) {
  const id = `pll.${slug(c.name)}`;
  cases.push({
    id,
    group: `pll-${slug(c.group)}`,
    name: `${c.name}-Perm`,
    recognition: `${c.group}`, // placeholder — replaced by the recognition workflow
    algs: c.algs.map((moves, i) => ({ moves, ...(i === 0 ? { primary: true } : {}) })),
    stickering: "PLL",
    puzzle: "3x3x3",
    probability: pllProbability(c.prob),
    phase: "full-pll",
  });
  scrambles[id] = c.scrambles.slice(0, MAX_SCRAMBLES);
}

for (const [setName, prefix, phase] of [
  ["4x4oll", "444.oll", "444"],
  ["4x4pll", "444.pll", "444"],
]) {
  for (const c of raw[setName]) {
    const id = `${prefix}.${slug(c.name)}`;
    cases.push({
      id,
      group: `${setName}-${slug(c.group)}`,
      name: `${c.name} (4×4 ${setName.includes("oll") ? "OLL" : "PLL"})`,
      recognition: `${c.group}`,
      algs: c.algs.map((moves, i) => ({ moves, ...(i === 0 ? { primary: true } : {}) })),
      stickering: "full",
      puzzle: "4x4x4",
      phase,
    });
    scrambles[id] = c.scrambles.slice(0, MAX_SCRAMBLES);
  }
}

const header = `/**
 * GENERATED by scripts/gen-cases.mjs from the verified JPerm extraction —
 * do not edit by hand. Recognition text is refined by the content workflow;
 * everything else is machine-derived and machine-verified.
 */
import type { CaseDef } from "./algs";

`;

const body =
  `export const GENERATED_CASES: CaseDef[] = ${JSON.stringify(cases, null, 2)};\n\n` +
  `/** Verified per-case trainer scrambles (each produces its case). */\n` +
  `export const CASE_SCRAMBLES: Record<string, string[]> = ${JSON.stringify(scrambles, null, 2)};\n`;

await writeFile(new URL("../src/data/fullsets.gen.ts", import.meta.url), header + body);
console.log(`generated ${cases.length} cases (${Object.values(scrambles).flat().length} scrambles)`);
