/**
 * GENERATED by scripts/gen-cases.mjs from the verified JPerm extraction —
 * do not edit by hand. Recognition text is refined by the content workflow;
 * everything else is machine-derived and machine-verified.
 */
import type { CaseDef } from "./algs";

export const GENERATED_CASES: CaseDef[] = [
  {
    "id": "oll.1",
    "group": "oll-dot",
    "name": "OLL 1",
    "recognition": "Dot shape",
    "algs": [
      {
        "moves": "R U2 R' R' F R F' U2 R' F R F'",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "2/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.2",
    "group": "oll-dot",
    "name": "OLL 2",
    "recognition": "Dot shape",
    "algs": [
      {
        "moves": "r U r' U2 r U2 R' U2 R U' r'",
        "primary": true
      },
      {
        "moves": "y' F R U R' U' F' f R U R' U' f'"
      },
      {
        "moves": "y' F R U R' U' S R U R' U' f'"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.3",
    "group": "oll-dot",
    "name": "OLL 3",
    "recognition": "Dot shape",
    "algs": [
      {
        "moves": "r' R2 U R' U r U2 r' U M'",
        "primary": true
      },
      {
        "moves": "y F U R U' R' F' U F R U R' U' F'"
      },
      {
        "moves": "y' f R U R' U' f' U' F R U R' U' F'"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.4",
    "group": "oll-dot",
    "name": "OLL 4",
    "recognition": "Dot shape",
    "algs": [
      {
        "moves": "M U' r U2 r' U' R U' R' M'",
        "primary": true
      },
      {
        "moves": "y F U R U' R' F' U' F R U R' U' F'"
      },
      {
        "moves": "y' f R U R' U' f' U F R U R' U' F'"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.5",
    "group": "oll-square-shape",
    "name": "OLL 5",
    "recognition": "Square Shape shape",
    "algs": [
      {
        "moves": "l' U2 L U L' U l",
        "primary": true
      },
      {
        "moves": "y2 r' U2 R U R' U r"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.6",
    "group": "oll-square-shape",
    "name": "OLL 6",
    "recognition": "Square Shape shape",
    "algs": [
      {
        "moves": "r U2 R' U' R U' r'",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.7",
    "group": "oll-small-lightning-bolt",
    "name": "OLL 7",
    "recognition": "Small Lightning Bolt shape",
    "algs": [
      {
        "moves": "r U R' U R U2 r'",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.8",
    "group": "oll-small-lightning-bolt",
    "name": "OLL 8",
    "recognition": "Small Lightning Bolt shape",
    "algs": [
      {
        "moves": "l' U' L U' L' U2 l",
        "primary": true
      },
      {
        "moves": "R U2 R' U2 R' F R F'"
      },
      {
        "moves": "y2 r' U' R U' R' U2 r"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.9",
    "group": "oll-fish-shape",
    "name": "OLL 9",
    "recognition": "Fish Shape shape",
    "algs": [
      {
        "moves": "R U R' U' R' F R2 U R' U' F'",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.10",
    "group": "oll-fish-shape",
    "name": "OLL 10",
    "recognition": "Fish Shape shape",
    "algs": [
      {
        "moves": "R U R' U R' F R F' R U2 R'",
        "primary": true
      },
      {
        "moves": "y2 r U R' U R U' R' U' r' R (U R U' R')"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.11",
    "group": "oll-small-lightning-bolt",
    "name": "OLL 11",
    "recognition": "Small Lightning Bolt shape",
    "algs": [
      {
        "moves": "r U R' U R' F R F' R U2 r'",
        "primary": true
      },
      {
        "moves": "y2 r' R2 U R' U R U2 R' U M'"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.12",
    "group": "oll-small-lightning-bolt",
    "name": "OLL 12",
    "recognition": "Small Lightning Bolt shape",
    "algs": [
      {
        "moves": "M' R' U' R U' R' U2 R U' R r'",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.13",
    "group": "oll-knight-move-shape",
    "name": "OLL 13",
    "recognition": "Knight Move Shape shape",
    "algs": [
      {
        "moves": "F U R U' R2 F' R U R U' R'",
        "primary": true
      },
      {
        "moves": "r U' r' U' r U r' y' R' U R"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.14",
    "group": "oll-knight-move-shape",
    "name": "OLL 14",
    "recognition": "Knight Move Shape shape",
    "algs": [
      {
        "moves": "R' F R U R' F' R F U' F'",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.15",
    "group": "oll-knight-move-shape",
    "name": "OLL 15",
    "recognition": "Knight Move Shape shape",
    "algs": [
      {
        "moves": "l' U' l L' U' L U l' U l",
        "primary": true
      },
      {
        "moves": "y2 r' U' r R' U' R U r' U r"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.16",
    "group": "oll-knight-move-shape",
    "name": "OLL 16",
    "recognition": "Knight Move Shape shape",
    "algs": [
      {
        "moves": "r U r' R U R' U' r U' r'",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.17",
    "group": "oll-dot",
    "name": "OLL 17",
    "recognition": "Dot shape",
    "algs": [
      {
        "moves": "F R' F' R2 r' U R U' R' U' M'",
        "primary": true
      },
      {
        "moves": "y2 R U R' U R' F R F' U2 R' F R F'"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.18",
    "group": "oll-dot",
    "name": "OLL 18",
    "recognition": "Dot shape",
    "algs": [
      {
        "moves": "r U R' U R U2 r' r' U' R U' R' U2 r",
        "primary": true
      },
      {
        "moves": "y R U2 R' R' F R F' U2 M' (U R U' r')"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.19",
    "group": "oll-dot",
    "name": "OLL 19",
    "recognition": "Dot shape",
    "algs": [
      {
        "moves": "r' R U R U R' U' M' R' F R F'",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.20",
    "group": "oll-dot",
    "name": "OLL 20",
    "recognition": "Dot shape",
    "algs": [
      {
        "moves": "r U R' U' M2 U R U' R' U' M'",
        "primary": true
      },
      {
        "moves": "r' R U (R U R' U') M2 U R U' r'"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "1/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.21",
    "group": "oll-cross",
    "name": "OLL 21",
    "recognition": "Cross shape",
    "algs": [
      {
        "moves": "R U2 R' U' R U R' U' R U' R'",
        "primary": true
      },
      {
        "moves": "y R U R' U R U' R' U R U2 R'"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "2/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.22",
    "group": "oll-cross",
    "name": "OLL 22",
    "recognition": "Cross shape",
    "algs": [
      {
        "moves": "R U2 (R2 U' R2 U' R2) U2 R",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.23",
    "group": "oll-cross",
    "name": "OLL 23",
    "recognition": "Cross shape",
    "algs": [
      {
        "moves": "R2 D' R U2 R' D R U2 R",
        "primary": true
      },
      {
        "moves": "y2 R2 D R' U2 R D' R' U2 R'"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.24",
    "group": "oll-cross",
    "name": "OLL 24",
    "recognition": "Cross shape",
    "algs": [
      {
        "moves": "r U R' U' r' F R F'",
        "primary": true
      },
      {
        "moves": "y R U R D R' U' R D' R2"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.25",
    "group": "oll-cross",
    "name": "OLL 25",
    "recognition": "Cross shape",
    "algs": [
      {
        "moves": "F' r U R' U' r' F R",
        "primary": true
      },
      {
        "moves": "y' R' F R B' R' F' R B"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.26",
    "group": "oll-cross",
    "name": "OLL 26",
    "recognition": "Cross shape",
    "algs": [
      {
        "moves": "(R U2 R') U' R U' R'",
        "primary": true
      },
      {
        "moves": "y' R' U' R U' R' U2 R"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.27",
    "group": "oll-cross",
    "name": "OLL 27",
    "recognition": "Cross shape",
    "algs": [
      {
        "moves": "R U R' U R U2 R'",
        "primary": true
      },
      {
        "moves": "y' R' U2 (R U R' U) R"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.28",
    "group": "oll-corners-oriented",
    "name": "OLL 28",
    "recognition": "Corners Oriented shape",
    "algs": [
      {
        "moves": "r U R' U' r' R U R U' R'",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.29",
    "group": "oll-awkward-shape",
    "name": "OLL 29",
    "recognition": "Awkward Shape shape",
    "algs": [
      {
        "moves": "R U R' U' R U' R' F' U' F R U R'",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.30",
    "group": "oll-awkward-shape",
    "name": "OLL 30",
    "recognition": "Awkward Shape shape",
    "algs": [
      {
        "moves": "F R' F R2 U' R' U' R U R' F2",
        "primary": true
      },
      {
        "moves": "F U (R U2 R' U') R U2 R' U' F'"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.31",
    "group": "oll-p-shape",
    "name": "OLL 31",
    "recognition": "P Shape shape",
    "algs": [
      {
        "moves": "R' U' F U R U' R' F' R",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.32",
    "group": "oll-p-shape",
    "name": "OLL 32",
    "recognition": "P Shape shape",
    "algs": [
      {
        "moves": "L U F' U' L' U L F L'",
        "primary": true
      },
      {
        "moves": "y2 S R U R' U' R' F R f'"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.33",
    "group": "oll-t-shape",
    "name": "OLL 33",
    "recognition": "T Shape shape",
    "algs": [
      {
        "moves": "R U R' U' R' F R F'",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.34",
    "group": "oll-c-shape",
    "name": "OLL 34",
    "recognition": "C Shape shape",
    "algs": [
      {
        "moves": "R U R2 U' R' F R U R U' F'",
        "primary": true
      },
      {
        "moves": "R U R' U' B' R' F R F' B"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.35",
    "group": "oll-fish-shape",
    "name": "OLL 35",
    "recognition": "Fish Shape shape",
    "algs": [
      {
        "moves": "R U2 R' R' F R F' R U2 R'",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.36",
    "group": "oll-w-shape",
    "name": "OLL 36",
    "recognition": "W Shape shape",
    "algs": [
      {
        "moves": "L' U' L U' L' U L U L F' L' F",
        "primary": true
      },
      {
        "moves": "y2 R' U' R U' R' U R U R B' R' B"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.37",
    "group": "oll-fish-shape",
    "name": "OLL 37",
    "recognition": "Fish Shape shape",
    "algs": [
      {
        "moves": "F R' F' R U R U' R'",
        "primary": true
      },
      {
        "moves": "F R U' R' U' R U R' F'"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.38",
    "group": "oll-w-shape",
    "name": "OLL 38",
    "recognition": "W Shape shape",
    "algs": [
      {
        "moves": "R U R' U R U' R' U' R' F R F'",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.39",
    "group": "oll-big-lightning-bolt",
    "name": "OLL 39",
    "recognition": "Big Lightning Bolt shape",
    "algs": [
      {
        "moves": "L F' L' U' L U F U' L'",
        "primary": true
      },
      {
        "moves": "y2 R B' R' U' R U B U' R'"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.40",
    "group": "oll-big-lightning-bolt",
    "name": "OLL 40",
    "recognition": "Big Lightning Bolt shape",
    "algs": [
      {
        "moves": "R' F R U R' U' F' U R",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.41",
    "group": "oll-awkward-shape",
    "name": "OLL 41",
    "recognition": "Awkward Shape shape",
    "algs": [
      {
        "moves": "R U R' U R U2 R' F R U R' U' F'",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.42",
    "group": "oll-awkward-shape",
    "name": "OLL 42",
    "recognition": "Awkward Shape shape",
    "algs": [
      {
        "moves": "R' U' R U' R' U2 R F R U R' U' F'",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.43",
    "group": "oll-p-shape",
    "name": "OLL 43",
    "recognition": "P Shape shape",
    "algs": [
      {
        "moves": "F' U' L' U L F",
        "primary": true
      },
      {
        "moves": "R' U' F R' F' R U R"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.44",
    "group": "oll-p-shape",
    "name": "OLL 44",
    "recognition": "P Shape shape",
    "algs": [
      {
        "moves": "F U R U' R' F'",
        "primary": true
      },
      {
        "moves": "y2 f R U R' U' f'"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.45",
    "group": "oll-t-shape",
    "name": "OLL 45",
    "recognition": "T Shape shape",
    "algs": [
      {
        "moves": "F R U R' U' F'",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.46",
    "group": "oll-c-shape",
    "name": "OLL 46",
    "recognition": "C Shape shape",
    "algs": [
      {
        "moves": "R' U' R' F R F' U R",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.47",
    "group": "oll-small-l-shape",
    "name": "OLL 47",
    "recognition": "Small L Shape shape",
    "algs": [
      {
        "moves": "R' U' R' F R F' R' F R F' U R",
        "primary": true
      },
      {
        "moves": "F' L' U' L U L' U' L U F"
      },
      {
        "moves": "y' F U R U' R' F' R U R' U R U2 R'"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.48",
    "group": "oll-small-l-shape",
    "name": "OLL 48",
    "recognition": "Small L Shape shape",
    "algs": [
      {
        "moves": "F R U R' U' R U R' U' F'",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.49",
    "group": "oll-small-l-shape",
    "name": "OLL 49",
    "recognition": "Small L Shape shape",
    "algs": [
      {
        "moves": "r U' r2 U r2 U r2 U' r",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.50",
    "group": "oll-small-l-shape",
    "name": "OLL 50",
    "recognition": "Small L Shape shape",
    "algs": [
      {
        "moves": "r' U r2 U' r2 U' r2 U r'",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.51",
    "group": "oll-i-shape",
    "name": "OLL 51",
    "recognition": "I Shape shape",
    "algs": [
      {
        "moves": "F U R U' R' U R U' R' F'",
        "primary": true
      },
      {
        "moves": "y2 f R U R' U' R U R' U' f'"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.52",
    "group": "oll-i-shape",
    "name": "OLL 52",
    "recognition": "I Shape shape",
    "algs": [
      {
        "moves": "R U R' U R U' B U' B' R'",
        "primary": true
      },
      {
        "moves": "y2 R' F' U' F U' (R U R' U) R"
      },
      {
        "moves": "R U R' U R U' y R U' R' F'"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.53",
    "group": "oll-small-l-shape",
    "name": "OLL 53",
    "recognition": "Small L Shape shape",
    "algs": [
      {
        "moves": "l' U2 L U L' U' L U L' U l",
        "primary": true
      },
      {
        "moves": "y2 r' U2 (R U R' U') R U R' U r"
      },
      {
        "moves": "y r' U' R U' R' U R U' R' U2 r"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.54",
    "group": "oll-small-l-shape",
    "name": "OLL 54",
    "recognition": "Small L Shape shape",
    "algs": [
      {
        "moves": "(r U2 R' U') R U R' U' R U' r'",
        "primary": true
      },
      {
        "moves": "y r U R' U R U' R' U R U2 r'"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.55",
    "group": "oll-i-shape",
    "name": "OLL 55",
    "recognition": "I Shape shape",
    "algs": [
      {
        "moves": "R' F R U R U' R2 F' R2 U' R' U R U R'",
        "primary": true
      },
      {
        "moves": "y R U2 R2 U' R U' R' U2 F R F'"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "2/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.56",
    "group": "oll-i-shape",
    "name": "OLL 56",
    "recognition": "I Shape shape",
    "algs": [
      {
        "moves": "(r' U' r) U' R' U R U' R' U R r' U r",
        "primary": true
      },
      {
        "moves": "(r U r') U R U' R' U R U' R' (r U' r')"
      },
      {
        "moves": "(r U r') U R U' R' U R U' M' U' r'"
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "2/216",
    "phase": "full-oll"
  },
  {
    "id": "oll.57",
    "group": "oll-corners-oriented",
    "name": "OLL 57",
    "recognition": "Corners Oriented shape",
    "algs": [
      {
        "moves": "R U R' U' M' U R U' r'",
        "primary": true
      }
    ],
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "2/216",
    "phase": "full-oll"
  },
  {
    "id": "pll.h",
    "group": "pll-edges-only",
    "name": "H-Perm",
    "recognition": "Edges Only",
    "algs": [
      {
        "moves": "M2 U M2 U2 M2 U M2",
        "primary": true
      },
      {
        "moves": "M2 U' M2 U2 M2 U' M2"
      }
    ],
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "1/18",
    "phase": "full-pll"
  },
  {
    "id": "pll.z",
    "group": "pll-edges-only",
    "name": "Z-Perm",
    "recognition": "Edges Only",
    "algs": [
      {
        "moves": "M' U M2 U M2 U M' U2 M2",
        "primary": true
      },
      {
        "moves": "y M' U' M2 U' M2 U' M' U2 M2"
      },
      {
        "moves": "y M2 U M2 U M' U2 M2 U2 M'"
      },
      {
        "moves": "M2 U' M2 U' M' U2 M2 U2 M'"
      }
    ],
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "2/18",
    "phase": "full-pll"
  },
  {
    "id": "pll.ua",
    "group": "pll-edges-only",
    "name": "Ua-Perm",
    "recognition": "Edges Only",
    "algs": [
      {
        "moves": "M2 U M U2 M' U M2",
        "primary": true
      },
      {
        "moves": "R U' R U R U R U' R' U' R2"
      },
      {
        "moves": "y2 R2 U' R' U' R U R U R U' R"
      }
    ],
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll"
  },
  {
    "id": "pll.ub",
    "group": "pll-edges-only",
    "name": "Ub-Perm",
    "recognition": "Edges Only",
    "algs": [
      {
        "moves": "M2 U' M U2 M' U' M2",
        "primary": true
      },
      {
        "moves": "R2 U (R U R' U') R' U' R' U R'"
      },
      {
        "moves": "y2 R' U R' U' R' U' (R' U R U) R2"
      },
      {
        "moves": "y2 R' U R' U' R3 U' (R' U R U) R2"
      }
    ],
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll"
  },
  {
    "id": "pll.aa",
    "group": "pll-adjacent-corner-swap",
    "name": "Aa-Perm",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "x L2 D2 L' U' L D2 L' U L'",
        "primary": true
      },
      {
        "moves": "y' x' L' U L' D2 L U' L' D2 L2"
      },
      {
        "moves": "y x R' U R' D2 R U' R' D2 R2"
      },
      {
        "moves": "y2 x' R2 D2 R' U' R D2 R' U R'"
      }
    ],
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll"
  },
  {
    "id": "pll.ab",
    "group": "pll-adjacent-corner-swap",
    "name": "Ab-Perm",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "x' L2 D2 L U L' D2 L U' L",
        "primary": true
      },
      {
        "moves": "y x L U' L D2 L' U L D2 L2"
      },
      {
        "moves": "y2 x R2 D2 R U R' D2 R U' R"
      },
      {
        "moves": "y' x' R U' R D2 R' U R D2 R2"
      }
    ],
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll"
  },
  {
    "id": "pll.e",
    "group": "pll-diagonal-corner-swap",
    "name": "E-Perm",
    "recognition": "Diagonal Corner Swap",
    "algs": [
      {
        "moves": "x' L' U L D' L' U' L D L' U' L D' L' U L D",
        "primary": true
      },
      {
        "moves": "x' R U' R' D R U R' D' R U R' D R U' R' D'"
      }
    ],
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "2/18",
    "phase": "full-pll"
  },
  {
    "id": "pll.f",
    "group": "pll-adjacent-corner-swap",
    "name": "F-Perm",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R",
        "primary": true
      }
    ],
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll"
  },
  {
    "id": "pll.ja",
    "group": "pll-adjacent-corner-swap",
    "name": "Ja-Perm",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "x R2 F R F' R U2 r' U r U2",
        "primary": true
      },
      {
        "moves": "y2 L' U' L F L' U' L U L F' L2 U L"
      },
      {
        "moves": "y' R' U L' U2 R U' R' U2 R L"
      }
    ],
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll"
  },
  {
    "id": "pll.jb",
    "group": "pll-adjacent-corner-swap",
    "name": "Jb-Perm",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "R U R' F' R U R' U' R' F R2 U' R'",
        "primary": true
      }
    ],
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll"
  },
  {
    "id": "pll.ra",
    "group": "pll-adjacent-corner-swap",
    "name": "Ra-Perm",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "R U' R' U' R U R D R' U' R D' R' U2 R'",
        "primary": true
      },
      {
        "moves": "R U R' F' R U2 R' U2 R' F R U R U2 R'"
      },
      {
        "moves": "y' L U2 L' U2 L F' L' U' L U L F L2"
      }
    ],
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll"
  },
  {
    "id": "pll.rb",
    "group": "pll-adjacent-corner-swap",
    "name": "Rb-Perm",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "R2 F R U R U' R' F' R U2 R' U2 R",
        "primary": true
      },
      {
        "moves": "y' R' U2 R U2 R' F R U R' U' R' F' R2"
      },
      {
        "moves": "R' U2 R' D' R U' R' D R U R U' R' U' R"
      }
    ],
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll"
  },
  {
    "id": "pll.t",
    "group": "pll-adjacent-corner-swap",
    "name": "T-Perm",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "R U R' U' R' F R2 U' R' U' (R U R') F'",
        "primary": true
      }
    ],
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll"
  },
  {
    "id": "pll.y",
    "group": "pll-diagonal-corner-swap",
    "name": "Y-Perm",
    "recognition": "Diagonal Corner Swap",
    "algs": [
      {
        "moves": "F R U' R' U' R U R' F' R U R' U' R' F R F'",
        "primary": true
      },
      {
        "moves": "F R' F R2 U' R' U' R U R' F' R U R' U' F'"
      }
    ],
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll"
  },
  {
    "id": "pll.v",
    "group": "pll-diagonal-corner-swap",
    "name": "V-Perm",
    "recognition": "Diagonal Corner Swap",
    "algs": [
      {
        "moves": "R' U R' U' y R' F' R2 U' R' U R' F R F",
        "primary": true
      },
      {
        "moves": "R' U R' U' R D' R' D R' U D' R2 U' R2 D R2"
      },
      {
        "moves": "z D' R2 D R2 U R' D' R U' R U R' D R U' z'"
      },
      {
        "moves": "R U2 R' D R U' R U' R U R2 D R' U' R D2"
      },
      {
        "moves": "x' R' F R F' U R U2 R' U' R U' R' U2 R U R' U'"
      }
    ],
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll"
  },
  {
    "id": "pll.na",
    "group": "pll-diagonal-corner-swap",
    "name": "Na-Perm",
    "recognition": "Diagonal Corner Swap",
    "algs": [
      {
        "moves": "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'",
        "primary": true
      },
      {
        "moves": "z U R' D R2 U' R D' U R' D R2 U' R D'"
      }
    ],
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "1/18",
    "phase": "full-pll"
  },
  {
    "id": "pll.nb",
    "group": "pll-diagonal-corner-swap",
    "name": "Nb-Perm",
    "recognition": "Diagonal Corner Swap",
    "algs": [
      {
        "moves": "R' (U R U' R') F' U' F R U R' F R' F' R U' R",
        "primary": true
      },
      {
        "moves": "z D' R U' R2 D R' U D' R U' R2 D R' U"
      }
    ],
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "1/18",
    "phase": "full-pll"
  },
  {
    "id": "pll.ga",
    "group": "pll-adjacent-corner-swap",
    "name": "Ga-Perm",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "R2 U R' U R' U' R U' R2 (U' D) R' U R D'",
        "primary": true
      },
      {
        "moves": "R2 u R' U R' U' R u' R2 y' R' U R"
      }
    ],
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll"
  },
  {
    "id": "pll.gb",
    "group": "pll-adjacent-corner-swap",
    "name": "Gb-Perm",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "R' U' R (U D') R2 U R' U R U' R U' R2 D",
        "primary": true
      },
      {
        "moves": "y F' U' F R2 u R' U R U' R u' R2"
      }
    ],
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll"
  },
  {
    "id": "pll.gc",
    "group": "pll-adjacent-corner-swap",
    "name": "Gc-Perm",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "R2 U' R U' R U R' U R2 (U D') R U' R' D",
        "primary": true
      },
      {
        "moves": "y2 R2 F2 R U2 R U2 R' F R U R' U' R' F R2"
      },
      {
        "moves": "R2 u' R U' R U R' u R2 y R U' R'"
      }
    ],
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll"
  },
  {
    "id": "pll.gd",
    "group": "pll-adjacent-corner-swap",
    "name": "Gd-Perm",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "R U R' (U' D) R2 U' R U' R' U R' U R2 D'",
        "primary": true
      },
      {
        "moves": "R U R' y' R2 u' R U' R' U R' u R2"
      }
    ],
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll"
  },
  {
    "id": "444.oll.solved",
    "group": "4x4oll-4-corners",
    "name": "Solved (4×4 OLL)",
    "recognition": "4 Corners",
    "algs": [
      {
        "moves": "R U2 R' U' Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' F R' F' R",
        "primary": true
      },
      {
        "moves": "y' Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U' F U R U' R' F'"
      },
      {
        "moves": "y2 R U R' F' Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' F R U' R'"
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.u-f",
    "group": "4x4oll-2-corners",
    "name": "U (F) (4×4 OLL)",
    "recognition": "2 Corners",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw'",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.u-r",
    "group": "4x4oll-2-corners",
    "name": "U (R) (4×4 OLL)",
    "recognition": "2 Corners",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U' R U R' U R U2 R'",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.u-l",
    "group": "4x4oll-2-corners",
    "name": "U (L) (4×4 OLL)",
    "recognition": "2 Corners",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R U2 R' U' R U' R'",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.u-b",
    "group": "4x4oll-2-corners",
    "name": "U (B) (4×4 OLL)",
    "recognition": "2 Corners",
    "algs": [
      {
        "moves": "m Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' m'",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.t-f",
    "group": "4x4oll-2-corners",
    "name": "T (F) (4×4 OLL)",
    "recognition": "2 Corners",
    "algs": [
      {
        "moves": "R U R' U' R Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R' U R U' R'",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.t-r",
    "group": "4x4oll-2-corners",
    "name": "T (R) (4×4 OLL)",
    "recognition": "2 Corners",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R U R' U' R' F R F'",
        "primary": true
      },
      {
        "moves": "y2 F' L' U L U L' U' L F Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw'"
      },
      {
        "moves": "y2 L2 B2 L2 Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' L2 B2 L2"
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.t-l",
    "group": "4x4oll-2-corners",
    "name": "T (L) (4×4 OLL)",
    "recognition": "2 Corners",
    "algs": [
      {
        "moves": "F R U' R' U' R U R' F' Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw'",
        "primary": true
      },
      {
        "moves": "R2 B2 R2 Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R2 B2 R2"
      },
      {
        "moves": "y2 Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U2 R U R' U' R' F R F'"
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.t-b",
    "group": "4x4oll-2-corners",
    "name": "T (B) (4×4 OLL)",
    "recognition": "2 Corners",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U R U2 (R2 U' R2 U' R2) U2 R",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.l-fr",
    "group": "4x4oll-2-corners",
    "name": "L (FR) (4×4 OLL)",
    "recognition": "2 Corners",
    "algs": [
      {
        "moves": "R' U' R Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R' U R",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.l-fl",
    "group": "4x4oll-2-corners",
    "name": "L (FL) (4×4 OLL)",
    "recognition": "2 Corners",
    "algs": [
      {
        "moves": "L U L' Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' L U' L'",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.l-br",
    "group": "4x4oll-2-corners",
    "name": "L (BR) (4×4 OLL)",
    "recognition": "2 Corners",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U R' U2 R U R' U R",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.l-bl",
    "group": "4x4oll-2-corners",
    "name": "L (BL) (4×4 OLL)",
    "recognition": "2 Corners",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R' U' R U' R' U2 R",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.sune-fr",
    "group": "4x4oll-1-corner",
    "name": "Sune (FR) (4×4 OLL)",
    "recognition": "1 Corner",
    "algs": [
      {
        "moves": "m' U R U' 3Rw' Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U R U2 R'",
        "primary": true
      },
      {
        "moves": "y2 Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U2 F R U R' U' F'"
      },
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U2 R U2 (R2 U' R2 U' R2) U2 R"
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.sune-fl",
    "group": "4x4oll-1-corner",
    "name": "Sune (FL) (4×4 OLL)",
    "recognition": "1 Corner",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R U R' U R U2 R'",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.sune-br",
    "group": "4x4oll-1-corner",
    "name": "Sune (BR) (4×4 OLL)",
    "recognition": "1 Corner",
    "algs": [
      {
        "moves": "L F' L' F Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' L' U L",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.sune-bl",
    "group": "4x4oll-1-corner",
    "name": "Sune (BL) (4×4 OLL)",
    "recognition": "1 Corner",
    "algs": [
      {
        "moves": "F' L' U' L U F Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw'",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.antisune-fr",
    "group": "4x4oll-1-corner",
    "name": "Antisune (FR) (4×4 OLL)",
    "recognition": "1 Corner",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U' R U2 R' U' R U' R'",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.antisune-fl",
    "group": "4x4oll-1-corner",
    "name": "Antisune (FL) (4×4 OLL)",
    "recognition": "1 Corner",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R U2 (R2 U' R2 U' R2) U2 R",
        "primary": true
      },
      {
        "moves": "y2 Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' F R U R' U' F'"
      },
      {
        "moves": "m' U' L' U 3Lw Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U' L' U2 L"
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.antisune-br",
    "group": "4x4oll-1-corner",
    "name": "Antisune (BR) (4×4 OLL)",
    "recognition": "1 Corner",
    "algs": [
      {
        "moves": "F R U R' U' F' Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw'",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.antisune-bl",
    "group": "4x4oll-1-corner",
    "name": "Antisune (BL) (4×4 OLL)",
    "recognition": "1 Corner",
    "algs": [
      {
        "moves": "R' F R F' Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R U' R'",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.h-fb",
    "group": "4x4oll-0-corners",
    "name": "H (FB) (4×4 OLL)",
    "recognition": "0 Corners",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R2 D' R U2 R' D R U2 R",
        "primary": true
      },
      {
        "moves": "y2 Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U R' U' R' F R F' U R"
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.h-lr",
    "group": "4x4oll-0-corners",
    "name": "H (LR) (4×4 OLL)",
    "recognition": "0 Corners",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R U R' U R U' R' U R U2 R'",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.pi-f",
    "group": "4x4oll-0-corners",
    "name": "Pi (F) (4×4 OLL)",
    "recognition": "0 Corners",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U' R U2 (R2 U' R2 U' R2) U2 R",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.pi-r",
    "group": "4x4oll-0-corners",
    "name": "Pi (R) (4×4 OLL)",
    "recognition": "0 Corners",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U R' U' R U' R' U2 R",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.pi-l",
    "group": "4x4oll-0-corners",
    "name": "Pi (L) (4×4 OLL)",
    "recognition": "0 Corners",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R' U2 R U R' U R",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.oll.pi-b",
    "group": "4x4oll-0-corners",
    "name": "Pi (B) (4×4 OLL)",
    "recognition": "0 Corners",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U' 3Rw U R' U' 3Rw' F R F'",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.pll.pure-e",
    "group": "4x4pll-edges-only",
    "name": "Pure-E (4×4 PLL)",
    "recognition": "Edges Only",
    "algs": [
      {
        "moves": "2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.pll.adj-e",
    "group": "4x4pll-edges-only",
    "name": "Adj-E (4×4 PLL)",
    "recognition": "Edges Only",
    "algs": [
      {
        "moves": "R U R' U' 2R2 U2 2R2 Uw2 2R2 Uw2 U' R U' R'",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.pll.o-plus",
    "group": "4x4pll-edges-only",
    "name": "O+ (4×4 PLL)",
    "recognition": "Edges Only",
    "algs": [
      {
        "moves": "m' U' m2 U' m2 U' m' U2 m2 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.pll.o-minus",
    "group": "4x4pll-edges-only",
    "name": "O- (4×4 PLL)",
    "recognition": "Edges Only",
    "algs": [
      {
        "moves": "m' U' m2 U' m2 U' m' U2 m2 U' 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.pll.w",
    "group": "4x4pll-edges-only",
    "name": "W (4×4 PLL)",
    "recognition": "Edges Only",
    "algs": [
      {
        "moves": "R U' R U R U R U' R' U' R2 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.pll.ba",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "Ba (4×4 PLL)",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "2R2 U2 2R2 Uw2 2R2 Uw2 U R U R' F' R U R' U' R' F R2 U' R'",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.pll.bb",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "Bb (4×4 PLL)",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "R U R' U' R' F R2 U' R' 2R2 U2 2R2 Uw2 2R2 Uw2 U R U R' F'",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.pll.ca",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "Ca (4×4 PLL)",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "2R2 U2 2R2 Uw2 2R2 Uw2 U R' U2 R U2 R' F R U R' U' R' F' R2",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.pll.cb",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "Cb (4×4 PLL)",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "2R2 U2 2R2 Uw2 2R2 Uw2 R U R' F' R U2 R' U2 R' F R U R U2 R'",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.pll.da",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "Da (4×4 PLL)",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "R' U L' U2 R U' R' U2 R L U' 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.pll.db",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "Db (4×4 PLL)",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "R U R' F' R U R' U' R' F R2 U' R' 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.pll.pa",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "Pa (4×4 PLL)",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "R U R' F' R U R' U' R' F R2 U' R' U' 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.pll.pb",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "Pb (4×4 PLL)",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "2R2 U2 2R2 Uw2 2R2 Uw2 R U R' F' R U R' U' R' F R2 U' R'",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.pll.ka",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "Ka (4×4 PLL)",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "2R2 U2 2R2 Uw2 2R2 Uw2 x R2 D2 R U R' D2 R U' R",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.pll.kb",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "Kb (4×4 PLL)",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "2R2 U2 2R2 Uw2 2R2 Uw2 U x R' U R' D2 R U' R' D2 R2",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.pll.q",
    "group": "4x4pll-diagonal-corner-swap",
    "name": "Q (4×4 PLL)",
    "recognition": "Diagonal Corner Swap",
    "algs": [
      {
        "moves": "x' R U' R' D R U R' D' R U R' D R U' R' D' x U 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.pll.sa",
    "group": "4x4pll-diagonal-corner-swap",
    "name": "Sa (4×4 PLL)",
    "recognition": "Diagonal Corner Swap",
    "algs": [
      {
        "moves": "F R U' R' U' R U R' F' R U R' U' R' F R F' U' 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.pll.sb",
    "group": "4x4pll-diagonal-corner-swap",
    "name": "Sb (4×4 PLL)",
    "recognition": "Diagonal Corner Swap",
    "algs": [
      {
        "moves": "F R U' R' U' R U R' F' R U R' U' R' F R F' 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.pll.x",
    "group": "4x4pll-diagonal-corner-swap",
    "name": "X (4×4 PLL)",
    "recognition": "Diagonal Corner Swap",
    "algs": [
      {
        "moves": "x' R U' R' D R U R' D' R U R' D R U' R' D' x 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.pll.m",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "M (4×4 PLL)",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "R U R' U' R' F R2 U' R' U' R U R' F' 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.pll.adj-c",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "Adj-C (4×4 PLL)",
    "recognition": "Adjacent Corner Swap",
    "algs": [
      {
        "moves": "R U R' U' R' F R2 U' R' U' R U R' F' U' 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  },
  {
    "id": "444.pll.diag-c",
    "group": "4x4pll-diagonal-corner-swap",
    "name": "Diag-C (4×4 PLL)",
    "recognition": "Diagonal Corner Swap",
    "algs": [
      {
        "moves": "F R U' R' U' R U R' F' U' 2R2 U2 2R2 Uw2 2R2 Uw2 U' R U R' U' R' F R F'",
        "primary": true
      }
    ],
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444"
  }
];

/** Verified per-case trainer scrambles (each produces its case). */
export const CASE_SCRAMBLES: Record<string, string[]> = {
  "oll.1": [
    "F' U2 B L' U2 B L F' D2 R2 U B2 U F2 R2 B2 D B2 D L2",
    "L' B L B U2 L' B L U' R2 U R2 U' R2 F2 B2 D' L2 D F2",
    "R B' R' B' U2 R B' R U2 R2 D' R2 D R2 B2 U R2 U R2 U",
    "R B' R' B' U2 R B' R F2 R2 U R2 F2 D L2 D R2 U2 L2 B2",
    "F' U2 B L' U2 B L F B2 U R2 U R2 U2 R2 U' R2 U2 R2 U",
    "F' U2 B L' U2 B L F B2 R2 U2 R2 U R2 U2 R2 U' R2",
    "F' U2 B L' U2 B L F R2 U R2 U' B2 U' R2 D B2 U' D' B2",
    "F' U2 B L' U2 B L F R2 B2 U2 B2 U' B2 U R2 B2 R2 U2 R2"
  ],
  "oll.2": [
    "L U2 R' F U2 R' F' L' D' B2 D' F2 D B2 D' L2 F2 D2 R2",
    "R' U2 L F' U2 L F R D B2 D F2 D' B2 D R2 F2 D2 L2",
    "R U2 L' B U2 L' B' R' U' F2 D2 B2 R2 D B2 L2 U L2 D",
    "R U2 L' B U2 L' B' R' U F2 D2 R2 D B2 L2 U' L2 D2 R2 D'",
    "R' U2 L F' U2 L F R L2 U' B2 L2 U B2 U' B2 U' L2 U2",
    "B2 L' B' L' U2 L' B L U2 R2 D F2 U' F2 D F2 U L2 D2 R2",
    "R' U2 L F' U2 L F R U L2 B2 U2 B2 D' B2 R2 U' R2 D",
    "B2 R B R U2 R B' R' U2 L2 D' F2 U F2 D' F2 U' R2 D2 L2"
  ],
  "oll.3": [
    "R L' B' L U2 L' B' R B' L U2 D2 R2 L2 U2 D2 L2",
    "R L' B' L U2 L' B' R B' L F2 B2 L2 D R2 F2 B2 L2 U'",
    "L U2 F U2 R' F R F2 L' U B2 D F2 U2 D F2 D B2 D",
    "R' L F' R U2 R' F' L F' R' F2 R2 L2 B2 U R2 L2 D R2 L2",
    "R U2 B U2 L' B R D2 L' U R2 U L2 D' R2 B2 D' B2 R2 D'",
    "R U2 B U2 L' B L B2 R U' F2 U' F2 D R2 U2 B2 U' B2 D'",
    "F R U B' R B R2 U' F' L2 U' F2 U F2 U L2 F2 U2 F2",
    "F R U B' R B R2 U' F U2 L2 U' L2 U' L2 U2 L2 U F2"
  ],
  "oll.4": [
    "R L' B R' U2 R B L' B R U2 D2 R2 L2 U2 D2",
    "R L' B R' U2 R B L' B R U F2 B2 D2 F2 B2 U R2 L2",
    "R B U2 B' R' U2 R' F R F U' F2 U' R2 U F2 U F2 U' R2",
    "R' U2 F' U2 L F' L' F2 R U D2 F2 D' B2 D F2 D' B2 D'",
    "B' R2 F R U2 F' R B L2 U L2 F2 U F2 D' L2 B2 U' B2 D",
    "B' R2 F R U2 F' R B L2 U F2 U' L2 D L2 D' B2 U F2 B2",
    "B' R2 F R U2 F' R B L2 U L2 B2 U L2 U' B2 L2 D' B2 D",
    "F' L' U2 L2 F' L' F U2 F R2 U R2 D' F2 U' L2 U' L2 D F2"
  ],
  "oll.5": [
    "R' F' L F' R' D2 L F2 R2 U2 L2 B2 L2 U2 L2",
    "R L2 B' L2 B L2 B' R U' R2 U F2 L2 F2 U B2 U' R2 B2 U'",
    "L' B' R B' R' B2 L F2 R2 F2 B2 L2 B2 U F2 B2 D F2 B2",
    "R2 L F' R2 F R2 F' L U L2 B2 R2 D B2 U' B2 R2 B2",
    "R2 B' R F R F' R2 B U R2 F2 D2 B2 D' B2 D' F2 U",
    "R U F' L2 B' L2 F U R U' L2 U L2 D' B2 D B2 R2 U",
    "F2 U' B L F L F' L2 B' U D2 R2 D' R2 D' F2 L2 U L2 U",
    "R B' R2 F R F2 D2 R2 B' L2 U' B2 U L2 B2 U' L2 U2 R2 F2"
  ],
  "oll.6": [
    "L F R' F R F2 L U D' B2 U B2 U' D L2",
    "R2 L' B R2 B' R2 B L' U L2 U' F2 R2 F2 U' B2 U L2 B2 U",
    "R' L2 F L2 F' L2 F R F2 R2 B2 R2 F2 R2 D' F2 R2 L2 B2",
    "R B L' B R D2 L F2 R2 U2 L2 B2 L2 U' R2 L2 D R2 L2",
    "R U R' B' U' R2 U R B U2 F2 R2 B2 D' F2 B2 U' B2 L2 B2",
    "R B2 D' B D B R' U L2 D L2 D' L2 U2 L2 B2 U B2 U2",
    "R B2 D' B D B R D L2 F2 U L2 D2 F2 R2 D B2 U' L2 U2",
    "F U' L2 U2 R' D2 R' U B U2 B2 U' B2 U2 B2 U' B2 L2 D2 R2"
  ],
  "oll.7": [
    "F' L2 D L' D' L' F L2 U L2 U B2 D' B2 D L2 U2 L2",
    "B2 L' B R B R' B2 L U B2 L2 U' R2 D F2 L2 D' R2 B2 U2",
    "R B2 L' B' L B' R F2 R2 L2 B2 L2 U' R2 L2 D' R2 L2",
    "F2 R' F L F L' F2 R U R2 U L2 B2 D B2 L2 U' R2 F2",
    "B' R' F R' F' R2 B R2 U' F2 R2 F2 U2 F2 R2 F2 U' R2",
    "R2 U' F R2 U R' U' R' F U R2 D R2 B2 U' B2 D' F2 U' R2",
    "F R U R U2 R2 F2 D' F U' F2 L2 U B2 U' B2 D L2 F2",
    "B' R' F R' F' R2 B L2 U' F2 R2 B2 D2 B2 R2 F2 U' L2"
  ],
  "oll.8": [
    "R' F2 L F L' F R U2 R2 L2 U2 D2 R2 L2 D2",
    "B2 R B' L' B' R D2 L' U R2 F2 U' R2 D F2 L2 U F2 U2 F2",
    "F2 L F' R' F' R F2 L U' R2 B2 D B2 R2 U L2 U F2",
    "R' U2 L F R' F L U2 R2 U R2 U2 L2 B2 L2 D2 F2 D L2 B2",
    "R2 U F' R' B' R' B R2 F R2 F2 U L2 D R2 B2 D' R2 L2",
    "R' F2 R2 L' B L' B R F2 U L2 U' R2 L2 D L2 D' B2",
    "R' F2 R2 L' B L' B R B2 U R2 U' R2 L2 D R2 D' F2",
    "R' U' R' U D' R B' R B L2 U' F2 B2 D' R2 L2 U' L2 F2 B2"
  ],
  "oll.9": [
    "R' B' R U' R U B U' R B2 U B2 D' R2 D",
    "R' B' R U' R U B U' R' B2 U' R2 D R2 F2 U R2 F2 B2 L2",
    "R U2 R' F' U F' L' U' L F2 D R2 D' F2 R2 U' F2 U R2 F2",
    "L U' F' U' L U D F L2 D B2 R2 U D2 B2 L2 F2 U L2 U'",
    "R B2 D' B D B R U F2 U' R2 B2 D B2 U2 R2 F2 R2 U'",
    "L F R' F R F2 L F2 B2 U F2 U' F2 D F2 D' B2 L2",
    "B' R2 F' B2 L F' L B' R2 U' L2 U F2 B2 L2 D' R2 D B2",
    "L2 B L' F' L' F L2 B' D L2 D' F2 R2 D R2 F2 B2 U B2 U2"
  ],
  "oll.10": [
    "L' B' R B' R' B2 L' U L2 B2 U2 B2 U B2 U B2 U2 L2 U' L2",
    "F' L F L F2 B2 R D2 R D' R2 B2 U2 L2 U L2 U F2 L2 U",
    "R' F' L F' L' F2 R' U' F2 B2 D' F2 U R2 U2 F2 D' L2 D2 F2",
    "F U2 B' R2 F2 L F L' B U2 L2 U2 F2 U2 B2 D' F2 D' B2 L2",
    "L2 F' L B L B' L2 F' U F2 U' F2 L2 U' L2 D F2 D' L2 U",
    "F' L2 F' L U' L' F L2 F R2 U R2 F2 U F2 R2 U' R2 U2",
    "R B U B D2 F2 L2 D' L D2 F2 D B2 R2 U R2 U R2 U'",
    "L U' F' L F' U F D F U' D' B2 U F2 U' F2 B2 L2 U'"
  ],
  "oll.11": [
    "R B2 R' U2 L' B L B' L2 U' R2 F2 U' F2 U F2 R2 L2 U' B2",
    "L U' F2 U F' U2 F' U L F2 U' B2 D' R2 D2 F2 D' B2",
    "R B' R2 F R F2 U2 L2 F' D' R2 B2 L2 U2 R2 U' L2 D L2",
    "R' U2 R B2 L F' L F R2 U' R2 U R2 D' R2 D L2 B2 U2",
    "R' U F U R' U' D' F U R2 L2 U2 R2 U' R2 D2 B2 U L2 D'",
    "L' B' R B' R' B2 L' U L2 U2 B2 U' B2 U' L2 B2 U2 B2 U' L2",
    "L' B' R B' R' B2 L F2 U2 L2 U' F2 U2 F2 L2 U' L2 U2 L2 F2",
    "R F R' U R' U' F' U R U2 R2 U' R2 F2 D2 B2 D' B2 D' F2"
  ],
  "oll.12": [
    "F' L2 B L B' L F U R2 U' R2 U R2 B2 R2 U B2 U' R2 B2",
    "R2 F R' B' R' F D2 B' D B2 D B2 D F2 U2 B2 U R2 U'",
    "R B2 D' B D B R' L2 U' F2 D2 R2 D' R2 D' F2 L2 U2",
    "L2 B L' F' L' F L2 B D' B2 U' L2 D L2 D L2 F2 D' F2",
    "R' L2 F L2 F' L2 F R B2 D F2 R2 F2 D R2 D2 B2 L2 F2",
    "L U' F' U' L U D F U' F2 R2 U' R2 F2 U L2 D' B2 U B2",
    "R2 B' D' R' U' R U D B U' R2 F2 U2 F2 U F2 U F2",
    "R B' U' B' R U D B D' F2 L2 U' F2 D' R2 B2 D' F2 D F2"
  ],
  "oll.13": [
    "R2 B' R F R F' R2 B R2 F2 D2 L2 D L2 D F2 R2 U' R2 U'",
    "F U2 B' R' F R' B D R2 F2 L2 U2 F2 U' B2 U F2 U' L2",
    "R' F2 D F' D' F' R F2 U F2 L2 U L2 F2 U' F2 U",
    "L2 F' L B L F' D2 B R2 B2 U2 L2 U B2 R2 D' B2 U' L2 U",
    "R U F' L2 B' L2 F U R B2 U R2 D' R2 D B2 U' R2 U'",
    "R L2 B' L2 B L2 B' R U R2 F2 U B2 U' B2 D F2 U",
    "B L2 F B2 R' F R' B' L2 F2 U B2 U' B2 D B2 D' R2",
    "F2 U' B L F L F' L2 B' U R2 D2 B2 D' B2 D' R2 F2 U2"
  ],
  "oll.14": [
    "F R B2 R2 B2 R B2 R F D2 L2 F2 D' L2 D' B2 U R2 U2 F2",
    "R' U2 L F R' F L F2 U B2 L2 D F2 R2 U F2 U' R2 B2",
    "R' F2 L F L' F R F2 U' F2 D F2 D' L2 U L2 F2",
    "B2 R B' L' B' R D2 L' D' F2 U' F2 U L2 D' R2 U B2 U'",
    "R U2 D' R B' D B U2 R B2 D2 F2 B2 U' B2 D' L2 F2 B2 D",
    "F R B' R F D2 B' D2 F2 U' B2 L2 D' B2 D F2 D' F2 B2 L2",
    "F R B' R F D2 B U' B2 R2 U' L2 U' F2 D2 B2 D' R2 D2 L2",
    "B U' L' U' B U D L U B2 U' L2 D' L2 U' B2 D B2 D'"
  ],
  "oll.15": [
    "R' F' L F' R' D2 L D R2 B2 R2 D L2 F2 R2",
    "R L2 B' L2 B L2 B' R U R2 F2 D R2 L2 U' L2 U R2 F2 U'",
    "L' B' R B' R' B2 L U2 R2 U' F2 R2 F2 U2 F2 R2 F2 U' R2",
    "R2 L F' R2 F R2 F' L U' D F2 U R2 B2 D' R2 F2 R2 U' R2",
    "R2 B' R F R F' R2 B R2 F2 U' R2 D2 L2 B2 D L2 D R2 U'",
    "L' U B U L' U' D' B U B2 D2 F2 U' F2 L2 U2 L2 U L2 D'",
    "R2 F D R U R' U' D' F' U R2 U2 B2 U B2 U B2 U2 B2 U'",
    "R2 B' R F R F' R2 B U F2 D2 B2 L2 D' B2 D' F2 U"
  ],
  "oll.16": [
    "L F R' F R F2 L U' F2 R2 B2 D B2 R2 F2 U2 L2",
    "R2 L' B R2 B' R2 B L U R2 B2 U' B2 R2 B2 U' B2",
    "R' L2 F L2 F' L2 F R U' F2 L2 U L2 F2 L2 U L2",
    "R B L' B R D2 L U' F2 L2 B2 D R2 B2 R2 D2 L2 U2",
    "R U R' B' U' R2 U R B L2 F2 U L2 B2 R2 D B2",
    "R B2 D' B D B R D' L2 U' R2 U R2 B2 U' R2 U L2 F2 D",
    "R B2 D' B D B R U' R2 U2 B2 U' R2 D' B2 U2 B2 R2 B2 D",
    "F U2 D' F R' D R U2 F' R2 U' L2 F2 D L2 U' R2 U B2 U'"
  ],
  "oll.17": [
    "R' F R' F L2 D2 R' B' R D2 L2 D B2 D' F2 D B2 D' R2",
    "F U R F' D2 B U L' B' U2 B2 U L2 U B2 D' R2 U' R2 D'",
    "F R B U B' U R' U2 F' U2 F2 U2 F2 L2 U' F2 U' F2 U L2",
    "R2 B2 L D' R F R' D L' B2 R2 U2 L2 U' L2 U' L2 U2 L2",
    "F R F D2 L' B L2 B2 L' U' L2 U L2 D F2 U2 F2 D F2 U'",
    "F R F D2 L' B L2 B2 L' U L2 U2 L2 D' B2 U' B2 D' F2 U'",
    "F' U' R2 L' B R2 U L F L2 U2 R2 B2 D' B2 D' R2 D' L2 D",
    "F' U' R2 L' B R2 U L F' U L2 D' L2 D2 B2 D' B2 D' F2"
  ],
  "oll.18": [
    "R2 F2 L' D R' B' R D' L' B2 L2 D R2 F2 U B2 L2 U' B2 U2",
    "R2 F2 L' D R' B' R D' L U2 L2 U' R2 U R2 L2 U2 F2 R2 U'",
    "R B' R B' L2 D2 R F R F2 B2 L2 U2 R2 F2 R2 U'",
    "R B' R B' L2 D2 R F R F2 U2 R2 F2 L2 F2 L2 F2 D2 R2 U",
    "R2 B2 R' U L' B' L U' R U' R2 U B2 L2 D' F2 D R2 L2 U",
    "R2 F' B L' B' R F2 R' F U R2 U' F2 D R2 D' B2 D F2 B2",
    "F U R F' D2 B U L' B R2 U' F2 U2 B2 U R2 L2 F2",
    "R' F R' F L2 D2 R' B' R' D R2 B2 R2 D R2 B2 D' B2 L2 F2"
  ],
  "oll.19": [
    "R B' R B2 U L' B L' F2 U L2 B2 R2 D2 B2 U B2 D' R2 U'",
    "R B' R B2 U L' B L F2 B2 R2 F2 U' F2 U' F2 U R2 F2 U'",
    "R L' B' R' F' L2 F L' F2 U' B2 L2 D' F2 R2 U' D' B2 R2 B2",
    "R L' B' R' F' L2 F L D' L2 F2 D F2 D F2 U' F2 L2 U2 L2",
    "R B' R B2 U L' B L B2 U' R2 U' R2 U' R2 U2 R2 U' R2",
    "R B' R B2 U L' B L U R2 D L2 U' L2 U2 B2 D' R2 B2",
    "R B' R B2 U L' B L F2 D B2 L2 D' B2 D F2 U F2 L2 F2",
    "R B' R B2 U L' B L B2 U F2 B2 L2 D L2 F2 B2 U' R2 U'"
  ],
  "oll.20": [
    "R L' F2 D2 B R L U B2 D' L2 D' B2 U B2 U F2 U' L2 U2",
    "R L' F2 D2 B R L U B2 D' R2 L2 D2 R2 D B2 U F2 B2 L2",
    "R L' F2 D2 B R L F2 B2 L2 D F2 B2 U F2 B2 D F2 U' D2",
    "R L' F2 D2 B R L' F2 D F2 R2 L2 U B2 U B2 U B2 D2",
    "R L' F2 D2 B R L U' F2 L2 B2 D' L2 F2 U' B2 U D2",
    "R L' F2 D2 B R L U B2 R2 F2 D F2 U F2 L2 F2 B2 U D2",
    "R L' F2 D2 B R L F2 U' L2 D' R2 U' B2 R2 F2 R2 D L2",
    "R L' F2 D2 B R L D L2 F2 U' B2 L2 D R2 U F2"
  ],
  "oll.21": [
    "R U B2 R' B2 R2 U' R' U L2 F2 R2 U L2 U L2 U' F2 U' L2",
    "R U B2 R' B2 R2 U' R U R2 B2 L2 D2 B2 L2 U F2 U R2 F2",
    "R U B2 R' B2 R2 U' R' B2 L2 D2 L2 U L2 D R2 D R2 L2 U2",
    "R' U' F2 R F2 R2 U R F2 L2 D2 F2 L2 U B2 U R2 B2 U",
    "R U B2 R' B2 R2 U' R U2 L2 D' R2 F2 U' D2 F2 L2 D' B2",
    "R U B2 R' B2 R2 U' R L2 F2 R2 D2 R2 L2 U' L2 D' R2 D' L2",
    "R U B2 R' B2 R2 U' R F2 L2 B2 D L2 F2 B2 U' R2 U' R2",
    "R U B2 R' B2 R2 U' R U2 F2 B2 D L2 B2 D' B2 L2 D L2 F2"
  ],
  "oll.22": [
    "R D L2 B2 D' B2 D' R U2 F2 R2 D' L2 U' L2 U L2 D' B2 D'",
    "R D B2 D B2 L2 D' R U' R2 U' R2 D2 L2 D R2 F2 D' F2 D",
    "F R2 F' U L2 B' D' B L2 F2 U' L2 U' B2 D B2 U L2 F2",
    "F R2 F' U R2 F' U' F R2 B2 R2 U' R2 U' B2 U B2 U B2",
    "F U2 F' U R2 F' D' F U F2 B2 L2 D L2 D' L2 B2 D F2 U2",
    "F U2 F' U R2 F' D' F' L2 U L2 U R2 U' F2 U2 R2 D' F2 D2",
    "R D L2 B2 D' B2 D' R U R2 U F2 R2 D R2 D' F2 D' L2 D2",
    "R' D' F2 D' F2 L2 D R' U' R2 U' R2 D2 L2 D F2 D F2 R2 D"
  ],
  "oll.23": [
    "F D B2 D' F U' F2 U' R2 D R2 B2 U2 B2 D B2 D2",
    "F D B2 D' F L2 U R2 F2 U' L2 D R2 D' F2 U2",
    "R' D' L2 D R U2 R2 L2 D' R2 U F2 U R2 D2 R2 U' F2",
    "R' D' L2 D R U R2 U' R2 D L2 F2 U L2 B2 D' L2 F2 D R2",
    "F D B2 D' F R2 U L2 U L2 U' B2 D R2 F2 L2 B2 U2",
    "F D B2 D' F D' F2 B2 R2 U' R2 D B2 L2 D2 L2 U B2 D2",
    "F D B2 D' F R2 B2 U' R2 U D2 B2 R2 U' B2 D' F2 D2 B2",
    "F D B2 D' F D F2 U R2 U' F2 D2 L2 D F2 U2 R2"
  ],
  "oll.24": [
    "R' F' L F' L' F' R F' R2 U2 F' U2 F R2 B' R2 B R2 U2",
    "L D R2 D' L U F2 U L2 D2 R2 F2 U2 F2 D2 B2",
    "R D L2 D' R U2 L2 F2 R2 U L2 B2 D' L2 D2",
    "R D L2 D' R F2 L2 F2 D' F2 D F2 D' L2 F2 R2 U",
    "L D R2 D' L D2 B2 L2 F2 U F2 U L2 B2 R2 L2",
    "L D R2 D' L U R2 U' L2 U' F2 U' R2 U' R2 F2 U",
    "B' D' F2 D B D' F2 U F2 U2 F2 D R2 U R2 U2",
    "L D R2 D' L D2 R2 D B2 L2 U' L2 B2 D L2 U"
  ],
  "oll.25": [
    "R U2 R F2 R' U2 R' U R2 U F2 U' R2 D R2 D' R2 U'",
    "R U2 R F2 R' U2 R F2 D' F2 D B2 D' F2 D L2 D2 L2 B2 R2",
    "R F2 R' B2 R F2 R F2 R2 U L2 U L2 U' R2 D L2 F2 R2",
    "R F2 R' B2 R F2 R B2 L2 U F2 D F2 U' L2 U R2 B2 R2",
    "R U2 R F2 R' U2 R' F2 R2 F2 R2 U R2 D' L2 U L2 F2 D F2",
    "R U2 R F2 R' U2 R B2 U' F2 U F2 D' F2 D L2 D2 L2 B2 R2",
    "R U2 R F2 R' U2 R F2 U' L2 U R2 U' L2 F2 U' F2 U2",
    "R U2 R F2 R' U2 R L2 B2 D' F2 R2 L2 U B2 D' R2 D F2"
  ],
  "oll.26": [
    "R U R2 U' R2 U R U2 F2 R2 F2 U2 F2 R2 F2 U",
    "R U R2 U' R2 U R L2 D' R2 D' R2 D' R2 D' R2 D' L2",
    "F' D' B D F' D' B U R2 L2 B2 U' R2 D B2 U2 B2 L2 B2",
    "F' D' B D F' D' B U B2 U' F2 R2 U' F2 L2 F2 R2 B2 U2",
    "R U R2 U' R2 U R L2 F2 U' B2 R2 F2 D' B2 U",
    "R U R2 U' R2 U R F2 U' L2 B2 R2 D' B2 L2 U",
    "R U R2 U' R2 U R F2 R2 B2 U' R2 F2 R2 D R2 L2 D'",
    "R U R2 U' R2 U R U' F2 R2 F2 U F2 R2 F2 U'"
  ],
  "oll.27": [
    "F' U B U' F U B U F2 R2 U R2 U' R2 D R2 D' F2 B2",
    "R U2 R' U' R U' R U' R2 U R2 B2 R2 U B2 U' R2 B2",
    "R D L' D' R D L U2 B2 U2 L2 U L2 B2 U B2 D' B2 U2 R2",
    "R D L' D' R D L' U L2 U L2 U2 L2 D' R2 U R2 U R2 U2",
    "R U2 R' U' R U' R F2 U' F2 U F2 R2 B2 D L2 D' B2",
    "R U2 R' U' R U' R U2 F2 L2 B2 D' B2 L2 F2 U R2",
    "R U2 R' U' R U' R U' F2 R2 F2 U2 F2 R2 F2 U' R2",
    "R U2 R' U' R U' R U2 F2 L2 B2 D B2 L2 F2 U' R2"
  ],
  "oll.28": [
    "F U F' R' F2 U' F' U R L2 F2 R2 D' L2 B2 L2 D R2 L2",
    "R F D B2 R D2 F U' L' U D F2 R2 U' F2 D B2 D' F2 U2",
    "R U' D F R2 F' U D' R U F2 R2 F2 U' R2 F2 U2",
    "R U R' B' R2 U' R' U B R2 F2 U2 R2 F2 R2 U2 F2",
    "R' F' L U2 L' F R B2 U' L2 U2 B2 U B2 U L2 B2 U B2 U2",
    "R L F R2 F R L B2 R2 D' B2 L2 F2 U2 R2 U' R2",
    "R L F U2 F R L F2 R2 F2 R2 F2 D' F2 D R2 L2 U2 R2",
    "R F R' F2 L F' L F2 U R2 U' F2 U2 F2 R2 B2 D R2 D B2"
  ],
  "oll.29": [
    "F U R U' R' F U R2 B2 U' F2 D L2 U2 B2 D' R2 U' R2 U2",
    "F2 U' B L2 B D2 R F R' U2 F2 U' B2 D2 F2 B2 D F2 D' B2",
    "R2 F U' R' U' R U R F' R2 U R2 U R2 U' R2 U R2 U",
    "B U L U' L' B R2 U B2 D' B2 D L2 U' R2 L2 B2 U'",
    "R B' R D B2 L' B L' U' L2 U' R2 U B2 U2 R2 D B2 D2",
    "B' U' R' U R B' U2 R2 U L2 U' R2 B2 U' B2 U2 L2 U B2 U'",
    "B' U' R' U R B U L2 B2 U L2 D' L2 D F2 U' F2 B2 L2",
    "F' L' U' L U F U B2 U' B2 D L2 F2 U F2 D' L2"
  ],
  "oll.30": [
    "F R U R' U' F U F2 U F2 U' F2 U L2 U' L2 D F2 D' F2",
    "F R U R' U' F U R2 L2 U F2 U F2 U2 L2 U R2 U2 F2 U",
    "R B' R D B2 L' B L B2 L2 U R2 D' F2 D L2 F2 U L2 F2",
    "R B' R D B2 L' B L D2 R2 U R2 B2 U B2 U' B2 D R2",
    "R2 B' R U2 R' U2 R' B U2 B2 U2 R2 F2 D B2 D' F2 U2 R2 B2",
    "F L' B2 D' R' D B2 L F' U L2 U' F2 U F2 U L2 F2 U2 F2",
    "B U L U' L' B U F2 D2 R2 U' R2 U' F2 D2 B2 L2 D' L2 D",
    "L' B' L U L' B L U B2 U2 B2 U' L2 D F2 D F2 D2 L2"
  ],
  "oll.31": [
    "F R L2 U R' U' L2 F U L2 U L2 U' L2 F2 L2 D F2 D' L2",
    "F R L2 U R' U' L2 F U' F2 R2 U2 R2 F2 U F2 U2 R2 U' R2",
    "R2 U B' D R D' R' B U' R2 U F2 D' F2 D R2 U' R2 U'",
    "F U F U' F' L F' L U2 R2 F2 L2 D2 L2 D' R2 L2 U B2 U'",
    "R B' U B' U' B R U B2 U' R2 U B2 D' R2 D B2 U",
    "R U' B' R' D2 R2 D B' U' B2 D R2 U' F2 U' L2 D2 L2 U F2",
    "L B L2 B' L U' B2 U' L2 U' L2 U B2 L2 U2 L2 U'",
    "F' L U' L U L' F R2 B2 U2 R2 U' B2 R2 F2 B2 D F2"
  ],
  "oll.32": [
    "R U R U' R' F R' F L2 U R2 U' L2 F2 B2 D L2 D' B2 U'",
    "F2 U F' U R U' R' F U2 L2 U2 R2 B2 D B2 R2 U' L2 F2 U2",
    "F' U' F' U F R' F R U' R2 F2 L2 D R2 B2 R2 D' R2 L2",
    "R F2 B U B' U' F2 R U F2 U' R2 U R2 U F2 U' R2",
    "R' B' R2 B R F2 D B2 U' B2 R2 U2 D' F2 R2 F2",
    "F R' U R' U' R F U' L2 D B2 R2 D' L2 U2 F2 R2 F2 U'",
    "R2 B2 L B' L2 B L U R2 U2 L2 U L2 U R2 U' B2 R2 U",
    "F U' R' F' U2 B2 D L' F2 R2 D' B2 L2 B2 R2 D' B2 L2 U L2"
  ],
  "oll.33": [
    "R2 B R' U' B' R' U R2 F R2 B' R2 F D2 B D2 F2 R2",
    "R L D2 R' B L2 B' L D F2 U2 F2 L2 D' R2 D L2 F2 D R2",
    "R U' B' R' U2 L2 D F U R2 B2 U B2 R2 U' L2 U L2 F2 L2",
    "L B L2 B' L U L2 D F2 L2 D2 B2 R2 U D B2",
    "R2 U B' D R D' R' B' U D B2 U F2 U L2 F2 R2 U2 B2 U'",
    "F2 R2 B R' B2 R B L2 D L2 D F2 L2 D R2 B2 U L2 F2 U2",
    "F2 R2 B R' B2 R B U R2 F2 D' F2 U L2 D' L2 F2 B2 D2 B2",
    "R' U' R' U R B' R B U' R2 F2 U2 R2 F2 R2 U2 F2 U"
  ],
  "oll.34": [
    "R F R2 F' R U D' L2 D R2 D' L2 U' D R2",
    "L2 U L B' U' B U L U B2 U' B2 U' L2 B2 U2 B2 U' L2 U",
    "R F R2 F' D L2 D' R F2 B2 U' L2 U B2 D2 L2 U' R2 B2 D'",
    "L B L2 B' L U' L2 U F2 D2 B2 D B2 D F2 L2",
    "R2 U B' D R D' R' B' U B2 U' L2 U B2 R2 U2 L2 U F2 D",
    "F2 R2 B R' B2 R B U' L2 U' F2 L2 D' R2 B2 U' F2 L2 D2 L2",
    "F' R' F' R2 B' R B U2 F2 U F2 U' F2 U' R2 U2 F2 U R2",
    "F2 U' L D' F' D F L D' L2 U' F2 L2 D L2 U' F2 U' F2 U2"
  ],
  "oll.35": [
    "R' B' R2 B R U' F2 R2 U F2 L2 D2 L2 U F2 U2 L2 D' B2 L2",
    "L' U B L U2 R2 D' F R2 U B2 U2 R2 D' L2 D' F2 L2 D' R2",
    "F L F2 L' F R2 U L2 U' B2 D' B2 U L2 F2 U F2 U' R2",
    "R' B' R2 B D' L2 D R' U2 F2 U2 D B2 D2 F2 L2 D F2 R2 F2",
    "R' B' R' B2 L' B L U2 R2 B2 R2 U2 B2 U R2 U R2",
    "R U R U' R' F R' F U' B2 U B2 D' R2 D R2 F2 U2",
    "L U F' U' F' U F U' L' U F2 D R2 D' F2 R2 U' F2 U R2",
    "R' B' R' B2 L' B L F2 U2 R2 F2 R2 U2 F2 U' B2 U' R2 B2"
  ],
  "oll.36": [
    "F' L F U2 R B2 R F2 D L2 F2 L2 D R2 B2 U R2 F2 R2",
    "R' U2 R' F R F' U2 R U2 B2 R2 U B2 U B2 U2 R2 B2 U2",
    "R2 B' D R D' R' B R2 F2 R2 D B2 U' B2 R2 U' D' F2",
    "R2 F' L F' U L U' L' U2 R2 B2 D L2 F2 R2 F2 D2 B2 L2 U2",
    "R2 F D' R' D R F D F2 B2 L2 F2 D' B2 U' F2 U R2 F2",
    "R B R U R' B' R U B2 U R2 U2 R2 B2 U B2 U2 B2 R2 U2",
    "F2 R2 F L' U' L U F' U' F2 D B2 R2 B2 R2 U B2 D' F2 R2",
    "R2 F D' R' D R F D L2 B2 U' R2 B2 L2 B2 U B2 D' R2"
  ],
  "oll.37": [
    "B U' L U2 L' U B U2 B2 U2 B2 U B2 U B2 U' B2 U",
    "F R F U F' R' F R2 U B2 L2 F2 D L2 B2 U' F2",
    "R2 F2 R' B U B' U' R F2 B2 U B2 U' B2 D B2 D' R2 U2",
    "R2 F2 L F' D' F D L' U' R2 D R2 D' F2 B2 L2 F2 D' L2 B2",
    "R B' R' U R2 B D B U F2 U' L2 U F2 D' B2 R2 U' R2",
    "R2 B2 R U' F' U F R L2 U' B2 U R2 L2 B2 D' F2 D R2 U2",
    "B2 L' D B D' B' L F2 B2 U F2 R2 U' F2 U2 R2 F2 R2 F2",
    "F2 L D' F' D F L D' R2 D' L2 U' L2 B2 R2 B2 D' B2 L2"
  ],
  "oll.38": [
    "R2 F D' R' D R F D' F2 R2 F2 R2 U R2 D F2 L2 D L2",
    "R B2 R B' L' B D2 L' F2 R2 U B2 U' B2 U' R2 F2 R2 L2 U",
    "R U2 R B' R' B U2 R U' R2 U F2 R2 U' F2 U R2 F2 R2",
    "L2 B D' L' D L B R2 B2 D' B2 U R2 F2 R2 B2 U D F2",
    "R B R U R' B' R U2 F2 R2 F2 U2 F2 R2 F2 U' R2",
    "L2 U F' B2 R' F2 R F U F2 U B2 L2 B2 U2 R2 D R2 B2",
    "R' U2 R' F R F' U2 R U F2 R2 L2 D' R2 B2 U' B2 U L2 F2",
    "F2 R2 F L' U' L U F' R2 F2 L2 U' L2 D L2 D' B2 U B2 L2"
  ],
  "oll.39": [
    "F2 R' D F D' F' R U F2 U' R2 B2 U' L2 B2 R2 U F2 D'",
    "F2 U R' L2 B' R2 B R' L2 U2 R2 U R2 L2 B2 R2 D' B2 L2 U2",
    "R2 B2 R U' F' U F R' U B2 R2 D B2 D' B2 R2 U' R2 U'",
    "L' B L U2 B U2 B' U B2 U2 R2 U B2 U2 R2 U' B2 U2 R2 U",
    "R2 F2 R' B U B' U' R U R2 D' R2 D B2 U' F2 B2 R2 U",
    "R B' R' U2 F' L2 F R2 U' B2 R2 F2 D' F2 U2 R2 B2 R2",
    "R B' R' U2 F' L2 F L2 B2 U L2 B2 L2 U B2 U2",
    "F U' R U2 R' U F' U2 F2 U F2 U' F2 U2 F2 U F2 U' F2 U'"
  ],
  "oll.40": [
    "F2 L D' F' D F L U R2 U' R2 U' B2 U R2 D R2 L2 F2 R2",
    "R B' R' U R2 B D B' D' R2 U2 B2 U' B2 U' B2 U2 B2 U",
    "R B' R' U2 B' U2 B U L2 U2 B2 U' L2 U2 B2 U L2 U2 B2 U",
    "L F' L' U R2 B U B U' B2 U' B2 U B2 U F2 R2 L2 B2 L2",
    "R2 B2 R U' F' U F R U D' F2 U' L2 D B2 U' F2 D B2 D'",
    "R B U B U F2 D2 L' D L2 D F2 D' R2 D B2 R2 B2 U' R2",
    "F R F U F' R' F B2 U2 R2 U' R2 U' F2 D2 B2 L2 D' L2 D'",
    "R2 B2 R U' F' U F R U F2 U' F2 L2 D' L2 D R2 D' B2 R2"
  ],
  "oll.41": [
    "R' U' F' U F R F2 U2 R2 B2 L2 D' L2 B2 R2 U F2",
    "B2 L' F R2 B' R2 F' L U B2 U F2 R2 B2 R2 U F2 D' L2 D",
    "F2 R' F U2 F' U2 F' R' F2 R2 U' R2 D' F2 D R2 U' F2 U'",
    "L' U' B' U B L U2 R2 U' F2 L2 B2 D B2 L2 F2 U2 R2",
    "R B U B' U' R U' F2 R2 F2 U2 F2 R2 F2 U' R2",
    "B2 R F' L2 B L2 F R' U' F2 U' L2 U F2 U' F2 L2 F2 B2 U'",
    "R F' L2 D' B' D L2 F R U R2 F2 L2 D2 B2 D' B2 D' L2 F2",
    "F U F R' F' R U' F U2 R2 B2 L2 D L2 B2 R2 U' F2"
  ],
  "oll.42": [
    "F2 R' F U2 F' U2 F' R U B2 U L2 U' B2 U B2 L2 F2 B2 U",
    "L' U' B' U B L F2 U' R2 B2 L2 D L2 B2 R2 U2 F2",
    "R' U' F' U F R U2 R2 U F2 L2 B2 D' B2 L2 F2 U2 R2",
    "B2 R2 L' D B D' B' L U2 R2 U' B2 U2 R2 F2 L2 B2 D' L2 F2",
    "R' F' U' F U R F2 U2 R2 B2 L2 D' L2 B2 R2 U F2",
    "R U B U' B' R B2 U B2 U' B2 R2 F2 D' L2 D F2",
    "R U B U' B' R U F2 L2 B2 D' B2 L2 F2 U2 R2",
    "F U R' U' F' R' U R U2 F2 R2 B2 D' F2 B2 U' B2 L2 B2"
  ],
  "oll.43": [
    "B L U L' U' B U R2 F2 L2 D' L2 F2 R2 U2 B2",
    "F' L' U' L U F R2 U R2 U' R2 F2 R2 U' F2 U R2 F2",
    "R U B' U' R' B' U B U' R2 U2 F2 L2 B2 D2 L2 F2 U'",
    "R2 F2 U' R' F R2 F' R U2 B2 D' B2 U' B2 D2 F2 L2 B2 R2 U'",
    "B' U' R' U R B R2 U F2 L2 B2 D' B2 L2 F2 U2 R2",
    "F U R U' R' F U' R2 B2 L2 D L2 B2 R2 U2 F2",
    "R' U' R' F' B2 L F' D L' B2 U R2 U' F2 B2 D L2 D' B2 R2",
    "R U R F2 B L' B D' L U D' B2 U R2 B2 U D' L2 B2 D'"
  ],
  "oll.44": [
    "B' R' U' R U B R2 U' B2 R2 B2 U2 B2 R2 B2 U' R2",
    "F R U R' U' F U R2 U B2 L2 F2 D L2 B2 U' F2",
    "L U F' U' L' F' U F U2 L2 B2 R2 U' B2 L2 F2 D'",
    "R U R B' R' B U' R F2 R2 L2 B2 L2 U' R2 L2 D' R2 L2",
    "R2 F2 B' D R D' R' B U2 B2 D' L2 D2 F2 D F2 D' F2 B2 U'",
    "R' U2 F U2 F2 U2 F' U2 R F2 R2 F2 U2 F2 U F2 R2 F2 U R2",
    "B U L U' L' B U2 R2 F2 L2 D' L2 F2 R2 U B2",
    "F' U' L' U L F R2 U2 F2 L2 B2 D B2 L2 F2 U' R2"
  ],
  "oll.45": [
    "F U R U' R' F' U F2 R2 L2 F2 B2 R2 L2 B2",
    "R B2 U' L U' L B R B' L2 B2 R2 U B2 U B2 U B2 U' B2",
    "R U' B' R' U' B' R2 U B R2 B2 U' B2 R2 B2 U' B2 U2",
    "B U L U' L' B R2 L2 F2 D F2 R2 L2 B2 U",
    "R U R B' R' B U' R B2 U B2 U' B2 R2 F2 D' L2 D F2",
    "B' U' R' U R B U F2 R2 L2 F2 B2 R2 L2 B2",
    "B' U' R' U R B U R2 F2 B2 L2 D' R2 F2 B2 L2",
    "F' L' U' L U F R2 U2 F2 L2 B2 D B2 L2 F2 U' R2"
  ],
  "oll.46": [
    "F' U' L' U L F R2 U' R2 U R2 B2 R2 U B2 U' R2 B2",
    "R2 F2 B' D R D' R' B U2 R2 F2 U F2 U2 R2 U' F2 R2 U2",
    "B' U' R' U R B R2 F2 R2 L2 B2 L2 U R2 L2 D R2 L2",
    "L2 F' B2 D L D' L' F U2 B2 L2 B2 L2 U B2 U2 L2 U' B2 L2",
    "R2 F B2 D' R' D R F B2 U2 R2 F2 U F2 U2 R2 U' F2 R2 U2",
    "R U B' U' R' B' U B R2 F2 R2 U' R2 L2 D' R2 B2 L2 U2",
    "F R U R' U' F U' R2 B2 L2 D L2 B2 R2 U2 F2",
    "R2 F B2 D' R' D R F' U2 R2 B2 U' B2 U2 R2 U B2 R2 U2"
  ],
  "oll.47": [
    "R D L2 D2 B' D B R D2 F2 R2 U' R2 F2 L2 D2 R2 U'",
    "R D L2 D2 B' D B R L2 B2 L2 D B2 L2 B2 D' R2 U' L2 U'",
    "R' F R' D R2 B2 D2 R' F' R' B2 D' L2 U2 F2 L2 D' F2 U F2",
    "F D' F2 L' U' L U2 F2 D F U2 R2 U' R2 U' F2 R2 U R2",
    "L F2 R2 F L F2 R2 F' U B2 R2 F2 D L2 D F2 R2 L2 B2 U",
    "L F2 L2 B L F2 L2 B U2 D2 F2 U2 B2 R2 B2 U2 R2 D2",
    "R U2 B' R F2 B' L' B' L B' L2 U' L2 D F2 R2 D' R2 U R2",
    "R B2 L F' D2 F B' L' B' R' B2 R2 U L2 U' F2 D2 F2 R2 B2"
  ],
  "oll.48": [
    "F U R U' R' U R U' R' F U2 D2 F2 B2 U2 D2 B2",
    "R2 B' D R F D R' B R2 F' U R2 B2 U B2 D' B2 U' B2 R2",
    "R D L2 D2 B' D B R U2 R2 D' B2 L2 U L2 B2 L2 D2",
    "R' D' L2 D2 F D' F' R F2 R2 U' L2 F2 L2 D B2 U F2 D'",
    "R B2 L2 B R F2 R2 B' U2 B2 L2 B2 U2 L2 U' R2 L2 D' R2 L2",
    "R B2 R2 F R F2 L2 F' R2 U R2 B2 L2 D R2 U' F2 R2 F2 U",
    "F' U' B L F' L F B' U F U' F2 U R2 B2 D B2 R2 U' F2",
    "F R2 B D2 F2 L' B L' F' D2 F2 U L2 U' R2 U L2 U' B2"
  ],
  "oll.49": [
    "L F2 L2 B L F2 L2 B R2 U2 L2 F2 R2 D2 F2",
    "F2 R' F' R L2 B D2 B' L2 U2 L2 U' B2 U' L2 U F2 U' R2 D'",
    "B2 L' B' R2 L B R2 B R2 U B2 D B2 D' R2 B2 U' R2 U' B2",
    "R B2 R2 F R F2 L2 F' U2 F2 L2 F2 U2 L2 U' R2 L2 D' R2 L2",
    "F D' F2 U L' U F' L2 D' L D B2 L2 U B2 U' L2 B2 D F2",
    "L F2 R2 F L F2 R2 F R2 U F2 L2 B2 D B2",
    "L F2 R2 F L F2 R2 F R2 F2 B2 U F2 R2 B2 D F2",
    "R D L2 D2 B' D B R' U B2 L2 B2 U B2 U2 B2 U L2 B2 U"
  ],
  "oll.50": [
    "L F2 R2 F L F2 R2 F R2 U2 L2 B2 R2 D2 B2",
    "B2 R B R' L2 F' D2 F L2 U2 L2 U F2 U L2 U' B2 U R2 D",
    "R B2 L2 B R F2 R2 B' U2 B2 L2 B2 U2 L2 U R2 L2 D R2 L2",
    "F2 L F R2 L' F' R2 F' R2 U' F2 D' F2 D R2 F2 U R2 U F2",
    "R U2 R2 D' F' R2 U2 R2 F R U R2 B2 L2 D' L2 B2 D R2 U2",
    "R D L2 D2 B' D B R D2 L2 D' B2 L2 D' L2 B2 R2",
    "F L' B2 D' R' D R2 B2 L F R2 F2 B2 L2 U' L2 U L2 U B2",
    "F2 R' F' R B2 D2 B' L2 B D2 L2 D L2 B2 U2 F2 D' F2 D F2"
  ],
  "oll.51": [
    "F' L2 B' D2 F2 R B' R F U2 B2 U R2 U' R2 D R2 D' F2 D2",
    "L F2 L2 B L F2 L2 B R2 U F2 R2 B2 D F2 U2",
    "R B2 R2 F R F2 L2 F U R2 D R2 L2 U' L2 U2 L2 F2 L2 U'",
    "R U2 L' F' B' U2 B' L F' R' B2 U R2 U' R2 D' B2 D F2 U2",
    "R D L2 D2 B' D B R U' B2 U R2 F2 D' R2 L2 B2 D' R2 F2",
    "F' L2 F U L2 D R' F R F2 D' F2 U2 F2 L2 F2 U L2 U F2",
    "R' U2 R U2 R' B L' B D2 L' D2 L2 U R2 U' R2 U' B2 U2 R2",
    "F' D' L' U' L' U L2 F2 U2 F D2 R2 U D2 F2 D F2 R2 U' F2"
  ],
  "oll.52": [
    "R D L2 D2 B' D B R' F2 U F2 D' L2 D2 L2 F2 U' F2 L2 D'",
    "R F2 U2 B U' B' R F2 D R' U D2 F2 L2 U2 L2 D R2 U",
    "B' R' U' R' B R2 B2 U B' U R2 B2 R2 B2 U B2 U B2 U2",
    "F R U R F' R2 F2 U' F U' R2 F2 R2 F2 U' F2 U' F2 U2",
    "R2 F' L F' B2 R' U2 R B2 R2 U' R2 D2 R2 U B2 L2 U B2",
    "F' L' B L' D2 L2 F L2 B U F2 D R2 B2 D F2 U",
    "F2 R' F' R L2 F L2 F U2 L2 U L2 U' F2 L2 U2 F2 U",
    "B2 R B R' L2 F' D2 F L2 B2 R2 B2 U2 B2 R2 U' B2 U B2 U"
  ],
  "oll.53": [
    "F' U L F' U' L U D' L F2 B2 U F2 U L2 F2 U D R2 U",
    "R2 U R B' R U2 F' L2 F R2 B2 U F2 L2 U2 F2 D B2 D2",
    "R B U' B' R U B' D B' D L2 F2 L2 D' L2 D L2 D2 B2",
    "R2 U R B' R U2 F' L2 F' U' L2 D2 L2 F2 R2 B2 D' B2 R2",
    "R U R B2 U D2 F L' F L2 U F2 D2 R2 B2 R2 B2 U' R2 U",
    "R' F' U F R' U' F D' F D' F2 B2 U' B2 U F2 D2 F2 R2 U2",
    "F R' F' B2 R B R2 B R U' B2 L2 D2 B2 L2 U F2 U R2 F2",
    "F U2 F U2 D F R F' R D R2 D L2 U2 B2 D' B2 D2 L2 F2"
  ],
  "oll.54": [
    "R2 U' R' F R' U2 F U2 F U2 B2 R2 F2 D' F2 R2 D' F2 D2 B2",
    "L2 U' L' B L' U2 F R2 F D' F2 U2 B2 L2 B2 U' F2 R2 D2 F2",
    "R' F' U F R' U' F D' F' U2 F2 D R2 F2 U F2 R2 F2 U' R2",
    "F U' R' F U R' U' D R L2 D' B2 L2 D L2 F2 U2 R2 B2 U",
    "F' U2 R B2 L B2 R' U2 F U' L2 D' B2 D L2 B2 U L2 U' B2",
    "R' U' R B2 U D F' L F' D R2 L2 D B2 U' F2 U2 R2 D L2",
    "F U R2 U' B' R' B R' F' R2 U2 B2 U' R2 U B2 R2 D B2 D'",
    "F R' F' B2 L U R2 U L D' L2 U2 R2 B2 R2 L2 D' R2 D' L2"
  ],
  "oll.55": [
    "R U' B2 R2 L2 F' D' F' R U L2 U' R2 D' B2 R2 F2 L2 U2 F2",
    "R' U' R U R' U2 F R' F' U2 R2 B2 U B2 D' R2 D R2 U2",
    "R U' B2 R2 L2 F' D' F' R' D2 F2 L2 D B2 D' B2 R2 U' B2",
    "R B' R' L2 B L B2 L B U' L2 B2 U' R2 F2 D' F2 R2 U B2",
    "R U2 R U2 D R B R' B' L2 D F2 L2 D R2 D R2 U' R2 B2",
    "R B' R B' U D2 F L2 F' D2 B2 U' B2 R2 U F2 D' L2 D F2",
    "R' U F2 R2 L2 B D B R D2 B2 L2 D' F2 D F2 R2 U F2",
    "F' U' F U F2 U2 R' F R F2 R2 U R2 D' F2 D F2 U"
  ],
  "oll.56": [
    "F2 U F R' F U2 R' U2 R B2 L2 D' R2 F2 D F2 R2 D2 L2 B2",
    "R F' B L' B L' F B2 R U' F2 U B2 U' L2 D' F2 D B2 D'",
    "R F' B L' B L' F B2 R U' F2 U B2 D' B2 U' F2 U R2 U",
    "F2 U F R' F U2 R' U2 R B2 L2 D R2 F2 D2 B2 L2 U' R2 F2",
    "F2 U' F' L F' U2 L U2 L' B2 R2 D L2 F2 D' F2 L2 D2 R2 B2",
    "F U R' U' F D R' U R' U F2 L2 F2 U' F2 U B2 D2 L2 U2",
    "R U B2 U' L' B' L B' R F2 B2 D' L2 D F2 B2 R2 D' R2 D",
    "R' F' B L F' L F2 B' R' U B2 U' F2 U L2 D B2 D' F2 D"
  ],
  "oll.57": [
    "R L F R2 F R L U2 L2 F2 L2 U2 L2 F2 U' R2 U' R2",
    "R L F U2 F R L U2 L2 B2 R2 D R2 U2 D R2 U' B2 U' B2",
    "R L F R2 F R L D L2 U L2 B2 L2 F2 U' R2 F2 U'",
    "R L F U2 F R L' U' B2 R2 L2 D' B2 L2 U' F2 R2 F2 U",
    "R U R' B' R2 U' R' U B U' F2 R2 F2 U F2 R2 F2",
    "R' F' L U2 L' F R B2 U B2 L2 D F2 U' F2 L2 D' B2",
    "R' L F' U2 F R L U R2 L2 D' R2 U' L2 B2 U' R2 F2 R2",
    "R F D B2 R D2 F U' L F2 D R2 D' F2 D F2"
  ],
  "pll.h": [
    "R L D2 R L D2 R2 B2 D2 B2 L2 F2 U2 R2 F2 U2",
    "F B D2 F B D2 F2 R2 D2 R2 B2 L2 U2 F2 L2 U2",
    "B F D2 B F D2 B2 L2 D2 L2 F2 R2 U2 B2 R2 U2",
    "L R D2 L R D2 L2 F2 D2 F2 R2 B2 U2 L2 B2 U2"
  ],
  "pll.z": [
    "R L U2 R L' U' R2 U' R2 U' R2 U' R2 U' R2 B2 R2 B2",
    "F B U2 F B' U R2 F2 R2 U F2 U R2 F2 R2 U F2 U'",
    "B F U2 B F' U L2 B2 L2 U B2 U L2 B2 L2 U B2 U'",
    "L R U2 L R' U' L2 U' L2 U' L2 U' L2 U' L2 F2 L2 F2"
  ],
  "pll.ua": [
    "F2 D F2 R2 F2 D R2 F2 D2 F2 B2 L2 B2 R2 D2 R2",
    "R2 U' B2 R2 B2 U B2 R2 B2 U2 B2 U2 R2 B2 R2 U2 B2",
    "R2 U' F2 R2 F2 U R' L F2 D2 B2 U2 R L B2 D2",
    "R2 D' R2 F2 R2 D R L' F2 D2 B2 U2 R' L' B2 D2"
  ],
  "pll.ub": [
    "F2 U' L2 F2 L2 U F2 L2 U2 L2 F2 L2 U2 F2 L2 U2 F2",
    "F2 D' F2 R2 B2 U R D2 F2 B2 U2 L' F2 R2 U2 B2 U2",
    "F2 D' F2 L2 F2 D F2 L2 D2 L2 B2 R2 U2 F2 R2 U2 B2",
    "L2 U B2 L2 B2 U B2 U2 B2 U2 L2 B2 L2 U2 L2 U2"
  ],
  "pll.aa": [
    "R L U2 R L' U F2 U2 R2 F2 R2 U' B2 U' F2 U R2 B2",
    "F B U2 F B L2 U R2 B2 U L2 U' B2 R2 U' L2 F2 B2",
    "B F U2 B F R2 U F2 L2 D B2 U' F2 R2 D' R2 B2 F2",
    "L R U2 L R' D F2 D' F2 U2 L2 F2 L2 U L2 U L2 F2"
  ],
  "pll.ab": [
    "R L U2 R L U' D' F2 D L2 F2 D B2 D' F2 L2 U' L2",
    "F B U2 F B' R2 U L2 U' B2 U2 B2 L2 F2 D L2 D L2",
    "B F U2 B' F R2 U L2 U' B2 U2 B2 L2 F2 D L2 D L2",
    "L R U2 L R U' D' B2 D B2 R2 U L2 U' R2 B2 U' R2"
  ],
  "pll.e": [
    "R L F2 R L' U' L2 D2 F2 U' B2 U' R2 F2 D2 B2 U' R2",
    "F B L2 F' B' L2 U R2 D' L2 B2 L2 D R2 U F2 U2 L2",
    "B F R2 B' F' R2 U L2 D' R2 F2 R2 D L2 U B2 U2 R2",
    "L R B2 L R' U' R2 D2 B2 U' F2 U' L2 B2 D2 F2 U' L2"
  ],
  "pll.f": [
    "R L' F2 R L' U' R2 U' R2 L2 F2 U L2 D' B2 D L2 F2",
    "F B D2 F B' D' L2 B2 D' L2 B2 U' F2 L2 R2 U L2 D'",
    "B F D2 B' F D' R2 L2 F2 U B2 L2 D B2 L2 U L2 D'",
    "L R' B2 L R' U R2 U L2 R2 B2 U' L2 D F2 D' L2 B2"
  ],
  "pll.ja": [
    "R L U2 R L' B2 U R2 F2 B2 U' L2 U L2 B2 D F2 U'",
    "F B U2 F B' U F2 D' F2 D R2 F2 L2 B2 D B2 L2 U",
    "B F U2 B' F U R2 B2 D B2 D' L2 U F2 R2 B2 R2 D",
    "L R U2 L' R B2 U L2 U' R2 U R2 F2 D F2 L2 R2 U'"
  ],
  "pll.jb": [
    "R L U2 R L U D' F2 U' F2 D R2 D' F2 D L2 U2",
    "F B U2 F B U L2 U B2 U' L2 R2 F2 U F2 U' L2 D",
    "B F U2 B F U L2 U B2 U' R2 L2 F2 U F2 U' L2 D",
    "L R U2 L R U D' F2 U' F2 D R2 D' F2 D L2 U2"
  ],
  "pll.ra": [
    "R L U2 R L' U' R2 L2 B2 U L2 D' R2 F2 B2 D R2 U2",
    "F B U2 F B U R2 U' L2 U F2 U' L2 D B2 D' F2 B2",
    "B F U2 B F U R2 U' L2 U F2 U' L2 D B2 D' B2 F2",
    "L R U2 L R' D' L2 F2 U' L2 U R2 U' B2 R2 F2 L2 U2"
  ],
  "pll.rb": [
    "R L U2 R L' U L2 U' L2 D F2 D' F2 R2 L2 F2 L2 U2",
    "F B U2 F B L2 U' F2 R2 D' F2 D L2 D' R2 F2",
    "B F U2 B F L2 U' F2 R2 D' F2 D L2 D' R2 F2",
    "L R U2 L R' U L2 B2 L2 R2 D B2 D' F2 D R2 F2 U2"
  ],
  "pll.t": [
    "R L F2 R L U R2 U' L2 F2 U' F2 U F2 R2 U' R2 F2",
    "F B L2 F B' U2 F2 U F2 U' R2 B2 U' L2 U B2 D' R2",
    "B F R2 B' F' U' R2 U R2 D' R2 D2 B2 U B2 D' R2",
    "L R B2 L' R D B2 U2 F2 R2 F2 U L2 U R2 U' F2 U"
  ],
  "pll.y": [
    "R L B2 R' L' U' L2 U' L2 U B2 D B2 D' R2 U R2 U",
    "F B U2 F B' U' L2 U R2 D' R2 U' B2 D R2 D' L2 U'",
    "B F U2 B' F U' L2 U R2 D' R2 U' B2 D R2 D' L2 U'",
    "L R B2 L' R' U' L2 U' L2 U B2 D B2 D' R2 U R2 U"
  ],
  "pll.v": [
    "F B U2 F B U F2 U2 L2 U' L2 F2 U2 F2 U L2 U2 B2",
    "L R U2 L R U B2 U2 L2 D' L2 F2 D2 F2 U R2 U2 F2",
    "R L U2 R L U B2 U2 L2 D' L2 F2 D2 F2 U R2 U2 F2",
    "B F U2 B F U F2 U2 L2 U' L2 F2 U2 F2 U L2 U2 B2"
  ],
  "pll.na": [
    "R L' U2 R' L U2 F2 L2 U' L2 U2 F2 U L2 U2 L2 F2 U'",
    "F B' U2 F' B U2 L2 B2 U' B2 U2 L2 U B2 U2 B2 L2 U",
    "B F' U2 B' F U2 R2 F2 U' F2 U2 R2 U F2 U2 F2 R2 U",
    "L R' U2 L' R U2 B2 R2 U' R2 U2 B2 U R2 U2 R2 B2 U'"
  ],
  "pll.nb": [
    "R L' U2 R' L U2 F2 R2 U R2 U2 F2 U' R2 U2 R2 F2 U",
    "F B' U2 F' B U2 L2 F2 U F2 U2 L2 U' F2 U2 F2 L2 U'",
    "B F' U2 B' F U2 R2 B2 U B2 U2 R2 U' B2 U2 B2 R2 U'",
    "L R' U2 L' R U2 B2 L2 U L2 U2 B2 U' L2 U2 L2 B2 U"
  ],
  "pll.ga": [
    "R L U2 R' L F2 U' B2 R2 F2 L2 D' R2 D L2 D' B2 U",
    "F B U2 F B' L2 R2 U' R2 U F2 U' R2 D F2 B2 R2 D'",
    "B F U2 B F' U' B2 L2 U' L2 U F2 U' B2 U F2 L2 B2",
    "L R U2 L R' F2 U' B2 R2 F2 L2 D' R2 D L2 D' B2 U"
  ],
  "pll.gb": [
    "R L U2 R L F2 U L2 U' R2 U B2 R2 D B2 R2 U",
    "F B U2 F B' U' R2 F2 U' F2 U F2 R2 D R2 D'",
    "B F U2 B F' U D' R2 U' F2 U B2 U' B2 D L2 U' R2",
    "L R U2 L R F2 U L2 U' R2 U B2 R2 D B2 R2 U"
  ],
  "pll.gc": [
    "R L U2 R L' B2 U R2 F2 L2 B2 U B2 U' L2 D F2 U'",
    "F B U2 F B' U L2 B2 R2 B2 L2 D' F2 D R2 U' F2 U",
    "B F U2 B F' U R2 U' B2 U R2 D' B2 L2 U' B2 L2 F2",
    "L R U2 L' R B2 U L2 U' L2 D F2 D' L2 R2 B2 L2 U'"
  ],
  "pll.gd": [
    "R L U2 R L' F2 U F2 U' L2 U R2 L2 B2 R2 D B2 U'",
    "F B U2 F B' D' L2 U L2 B2 D F2 D' B2 D R2 F2 R2",
    "B F U2 B F' U B2 R2 U R2 U' F2 U B2 U' B2 R2 F2",
    "L R U2 L R' F2 U B2 U' R2 U B2 L2 B2 F2 D B2 U'"
  ],
  "444.oll.solved": [
    "U' B2 R2 B2 R2 U' F2 D' B2 D F U B U2 L2 F U' B'",
    "U' F2 U' R2 B2 D B2 F2 R2 U2 F U B U2 L2 F U' B'",
    "U2 R2 U R2 D' F2 D F2 U2 R' U F2 U F2 U' R",
    "D' L2 B2 U L2 U' B2 L2 D' B2 D2 L U' F2 U' F2 U L'"
  ],
  "444.oll.u-f": [
    "R2 B2 D F2 D' R2 D B2 R2 U F2 L' R' U2 L' R'",
    "U' R2 F2 L2 R2 D B2 D' R2 U R2 U' F2 L' R U2 L' R'",
    "L2 U2 F2 U' R2 U2 R2 F2 U F2 U2 R2 U' L' R' U2 L' R'",
    "B2 R2 B2 R2 U' R2 U' R2 U' R2 U' R2 U' L R' U2 L' R'"
  ],
  "444.oll.u-r": [
    "U B2 R2 D F2 R2 B2 U L2 U L' U' L U' R' F2 R",
    "R2 D B2 D' F2 D B2 D' F2 R2 U L' U' L U' L' U2 L",
    "D' L2 R2 B2 U R2 B2 U' B2 U2 L' B2 L' D R D R' F2",
    "R2 D' R2 B2 D' B2 D B2 U' B2 U' L' U' L U' R' F2 R"
  ],
  "444.oll.u-l": [
    "U2 B2 U L2 U' R2 U L2 U' R2 B' U' F' U B' U' F",
    "U' F2 U R2 B2 L2 D' L2 B2 R2 U2 F U2 F U F' U F",
    "R2 D B2 D' F2 D B2 D' F2 R2 U' F' U2 F U F' U F",
    "R2 B2 U B2 D' R2 D R2 U' R' U R' U R U2 R'"
  ],
  "444.oll.u-b": [
    "U F2 R2 F2 U2 F2 R2 F2 R' U2 R U2 R U2 R U2 R'",
    "B2 D B2 D' R2 B2 U B2 U R' D' U2 R2 F2 U' F2 D R",
    "D' B2 F2 U' L2 R2 U' R2 U2 L' B2 F2 R' D2 U2 R' U2 R2",
    "D R2 B2 U L2 D L2 U' L2 U L' D2 B2 R F2 R2 U2 R'"
  ],
  "444.oll.t-f": [
    "U' R2 D' R2 U L2 U' L2 U' R2 D' R' F' L B2 L' F R'",
    "U' L2 U' B2 R2 F2 L2 F2 D' R2 U R D L2 D' R D R2",
    "B2 U2 B2 D B2 D' R2 U R2 U B2 L U' R2 U L' U' R2",
    "U' B2 F2 D B2 F2 U B2 R2 B2 U2 F U2 F L2 F' U2 F'"
  ],
  "444.oll.t-r": [
    "D L2 D' B2 U B2 L2 U L2 U' B2 L' F2 L B2 L' F2 L'",
    "B2 D' R2 B2 D F2 U' R2 F2 D F2 L F2 R' U2 L D2 R'",
    "U' F2 U R2 U' L2 U B2 L2 D F2 L' B2 L F2 R' U2 R'",
    "U2 F2 L2 D' B2 U B2 L2 D R D2 L' U2 L D2 R'"
  ],
  "444.oll.t-l": [
    "U' R2 D L2 R2 F2 U L2 U' F2 R' D L2 D' R U F2",
    "D R2 D' F2 U F2 R2 U R2 U' F2 R' B2 R F2 R' B2 R'",
    "R2 B2 D' F2 D B2 D' F2 D F2 R' B2 R F2 R' B2 R'",
    "U' F2 D' L2 U L2 F2 D R2 U' B2 R F2 R' B2 R F2 R"
  ],
  "444.oll.t-b": [
    "U B2 U B2 D' B2 D2 L2 U' L' D' L' B2 U L' U2 L",
    "R2 D' L2 B2 D R2 U' L2 U' L' U L F2 U' R U2 R'",
    "R2 F2 L2 D L2 B2 F2 R' B2 R' U R2 B2 R' U' R'",
    "F2 U' R2 D2 L2 D' F2 U L2 D B' U' F R2 F U B' L2"
  ],
  "444.oll.l-fr": [
    "U' L2 U' L2 D L2 U' L2 U L2 U R2 D' L' D R2 D' L'",
    "F2 D2 B2 D' R2 U2 F2 U R2 D' L2 F2 U' L D R2 D' L'",
    "L2 U' L2 D' B2 U L2 D2 R2 D' F2 U2 L' D R2 D' L'",
    "F2 D2 B2 D' R2 U2 F2 U R2 D' L2 F2 U' L D R2 D' L'"
  ],
  "444.oll.l-fl": [
    "R2 D R2 U' R2 D B2 L2 D2 R2 F2 U R' D' L2 D R",
    "L2 F2 R2 D F2 D R2 B2 D R2 U' L2 D' B' D F2 D' B'",
    "D' L2 D' B2 U' B2 D2 F2 U' F2 U R' D' L2 D R",
    "U2 R2 D' L2 R2 B2 D' B2 D B2 U' B2 U R' D' L2 D R"
  ],
  "444.oll.l-br": [
    "L2 U L2 B2 U F2 U' B2 U F2 U' B' U' B U' F' L2 F",
    "R2 U B2 R2 U' B2 U R2 B2 R2 F R2 F' U B U B' R2",
    "F2 U' F2 R2 U R2 D R2 D' B U2 B' U B U B' R2",
    "U2 R2 U B2 U' F2 U L2 F2 D B2 L' U' L2 U L2 U' L'"
  ],
  "444.oll.l-bl": [
    "R2 D' F2 D B2 D' F2 D B2 R2 U' R' U2 R U R' U R",
    "U2 R2 U' L2 B2 U B2 L2 U F D2 F D' F' D' F' R2",
    "U' F2 R2 D R2 F2 U' R2 D B' L2 B D' F' D' F R2",
    "R2 D' F2 D F2 U' F2 U F2 R2 U' R' U2 R U R' U R"
  ],
  "444.oll.sune-fr": [
    "R2 U B2 R2 U' B2 U R2 B2 R2 B U' B' R2 U F' U2 F",
    "B2 U R2 U R2 B2 D' R2 D F' U F R2 U' F R2 F'",
    "F2 L2 U B2 U' L2 B2 D2 B2 D F U F R2 U' F R2 F'",
    "F2 D R2 D B2 R2 D' F2 U2 F D' F' L2 U F' U2 F"
  ],
  "444.oll.sune-fl": [
    "D R2 D' F2 U F2 R2 U R2 U' R' U2 R' U' R U' R'",
    "B2 D B2 D' B2 U R2 U' R2 B2 U R' U' R2 U R2 U' R'",
    "B2 L2 D' R2 D L2 D' B2 U' F' U B2 R2 D2 B' L2 D' B'",
    "L2 U' B2 U F2 U' R2 F2 D' B2 R' U' R2 U R2 U' R'"
  ],
  "444.oll.sune-br": [
    "D B2 L2 D F2 U' F2 L2 D F2 U2 F2 D F D B2 D' F'",
    "B2 R2 B2 D2 F2 D R2 U' F2 L2 R2 D U' F' D B2 D' F'",
    "U R2 B2 U B2 U R2 U2 B2 R2 U R2 U' F D B2 D' F'",
    "D B2 L2 D F2 U' F2 L2 D F2 U2 F2 D F D B2 D' F'"
  ],
  "444.oll.sune-bl": [
    "B2 D L2 D' L2 U L2 U2 R' U L2 U' R U B2",
    "F2 U' F2 L2 D' L2 D F2 L2 U2 R U' L2 U R' U' F2",
    "R2 U2 F2 U' R2 U' R2 U F2 R2 U2 F U' R2 U' R2 U F'",
    "U2 R2 F2 D2 L2 D' L2 U' F2 D2 B' D F2 D' B U F2 R2"
  ],
  "444.oll.antisune-fr": [
    "U' R2 U2 F2 L2 B2 D B2 L2 F2 U' R' U' L' U R' U' L",
    "U2 F2 D R2 D' L2 D R2 D' L2 F' U F' U F U2 F'",
    "F2 D' L2 U L2 F2 D R2 U' R' U' L' U R' U' L",
    "L2 U F2 U L2 U' L2 U2 B2 D R2 F D' B' D F D' B'"
  ],
  "444.oll.antisune-fl": [
    "R2 D2 B2 D R2 U' L2 U' F2 R D2 L2 B2 U B2 D' U' R'",
    "L2 B2 D' R2 D B2 L2 F2 R' F2 U' F2 U R F2 U' F2",
    "R2 U' R2 U R2 U' B2 D B2 U B D' B' R2 U B' U2 B",
    "D F2 R2 U R2 D' F2 U2 L2 U' F U' F' L2 U B' U2 B"
  ],
  "444.oll.antisune-br": [
    "U L2 F2 U' L2 D R2 F2 R2 F2 U R' D' L2 D R' D' F2",
    "L2 D L2 B2 D' R2 U R2 B2 U B U' L2 U' L2 U B'",
    "D F2 L2 U F2 U' L2 F2 L2 F2 D' B D F2 D' B U B2",
    "U B2 L2 U' B2 U L2 B2 U' L2 U2 B U' L2 U' L2 U B'"
  ],
  "444.oll.antisune-bl": [
    "L2 D' B2 D B2 U' B2 U B2 U L2 U' R' U L2 U' L2 R",
    "U F2 D' L2 D L2 D' B2 D L2 U' L2 U F D' B2 D F",
    "U F2 D' L2 D L2 D' B2 D L2 U' L2 U F D' B2 D F",
    "U' R2 D B2 F2 R2 U R2 F2 L2 R' D L' U2 L' D' R'"
  ],
  "444.oll.h-fb": [
    "D' F2 D' L2 F2 D2 B2 U R2 U' B2 R U' B2 U' B2 U R'",
    "U' B2 R2 D L2 F2 D' R2 U L2 U R U' B2 U' B2 U R'",
    "F2 L2 D F2 D' F2 D B2 F2 L2 F2 R' D L2 D' R U R2",
    "U R2 U' B2 U2 B2 U R2 U' R U' B2 U' B2 U R'"
  ],
  "444.oll.h-lr": [
    "F2 U R2 D L2 D' F2 U2 B' D U2 L2 U' R2 B2 D' F'",
    "B2 L2 U' R2 F2 D' B2 L2 D B D2 R2 F L2 F2 U2 F'",
    "U' R2 D L2 D' R2 U' L2 F2 R2 B D2 R2 F L2 F2 U2 F'",
    "L2 D' B2 D2 R2 D' L2 U' R2 F' U2 R2 F U2 F2 R2 F'"
  ],
  "444.oll.pi-f": [
    "B2 U' L2 D2 R2 D' B2 U R2 D F' U' B L2 B U F' R2",
    "U2 F2 R2 U R2 D R2 U' R' D' R' F2 U R' U2 R",
    "D' L2 B2 U F2 D' R2 U2 B2 D' R D' R' F2 U R' U2 R",
    "U L2 U L2 U B2 L2 U2 L2 U' R' U R B2 U' R B2 R'"
  ],
  "444.oll.pi-r": [
    "D' F2 D L2 F2 D' U' R2 F2 L' U B2 D F2 D2 U' R'",
    "F2 D' F2 D R2 F2 U F2 D U' L' D' R' D L D' R'",
    "U2 R2 D B2 D' B2 D L2 U' L2 U L' D' R' D L D' R'",
    "R2 D B2 U' B2 R2 D' F2 U F2 U' L U L' U L U2 L'"
  ],
  "444.oll.pi-l": [
    "U2 R2 U F2 L2 B2 D' B2 L2 F2 U2 R U' R U' R' U2 R",
    "U' B2 D' R2 D R2 U' R2 U R2 B' U2 B' U' B U' B'",
    "U L2 F2 D' B2 D F2 D' B' D' R2 B' D2 L2 U F'",
    "R2 D' F2 U F2 R2 D B2 U' B2 U' B U2 B' U' B U' B'"
  ],
  "444.oll.pi-b": [
    "U2 F2 D F2 L2 D' B2 U B2 L' F2 U' R U R' F2 L'",
    "U2 R2 U' B2 D L2 U' L2 B2 D' U R' D' R U2 R' D R'",
    "U' R2 F2 D' L2 U L2 U' F2 D2 R' U R D' R' U' R'",
    "R2 B2 D' F2 D B2 D' F2 D2 R' U R D' R' U' R'"
  ],
  "444.pll.pure-e": [
    "U R2 B2 D2 F2 R2 B2 U2 R2 F2 L' R' U2 L' R'",
    "U' R2 B2 D2 F2 R2 B2 U2 R2 F2 L' R' U2 L' R'",
    "U2 R2 B2 D2 F2 R2 B2 U2 R2 F2 L' R' U2 L' R'",
    "R2 B2 D2 F2 R2 B2 U2 R2 F2 L' R' U2 L' R'"
  ],
  "444.pll.adj-e": [
    "R2 B2 R2 U2 F2 D R2 U' B2 U R2 F2 U L' R U2 L' R'",
    "R2 B2 R2 U2 F2 D' L2 U B2 U' L2 F2 U' L R' U2 L' R'",
    "B2 U B2 U B2 U' B2 L2 U2 L2 U' L2 U L' R B2 L' R'",
    "F2 L2 D' B2 D L2 U' F2 L2 R2 U R2 U L R' F2 L R'"
  ],
  "444.pll.o-plus": [
    "U L2 R2 U' F2 R2 D2 L2 F2 R2 U2 B2 R2 U' L' R' U2 L' R'",
    "U' L2 R2 D B2 R2 U2 L2 F2 L2 U2 F2 R2 D' L' R' U2 L' R'",
    "R2 U' B2 R2 B2 U' R2 U' B2 R2 B2 U' L R' U2 L' R'",
    "U B2 R2 B2 R2 U' R2 U' R2 U' R2 U' R2 U' L R' U2 L' R'"
  ],
  "444.pll.o-minus": [
    "L2 R2 U' F2 R2 D2 L2 F2 R2 U2 B2 R2 U' L' R' U2 L' R'",
    "L2 R2 D B2 R2 U2 L2 F2 L2 U2 F2 R2 D' L' R' U2 L' R'",
    "U R2 U' B2 R2 B2 U' R2 U' B2 R2 B2 U' L R' U2 L' R'",
    "B2 R2 B2 R2 U' R2 U' R2 U' R2 U' R2 U' L R' U2 L' R'"
  ],
  "444.pll.w": [
    "U R2 B2 F2 R2 D' B2 R2 F2 U' L' R' U2 L' R'",
    "D' F2 L2 R2 F2 U' F2 L2 B2 U' L' R' U2 L' R'",
    "U' R2 B2 F2 R2 D F2 L2 B2 U L' R' U2 L' R'",
    "D F2 L2 R2 F2 U B2 R2 F2 U L' R' U2 L' R'"
  ],
  "444.pll.ba": [
    "U B2 L2 D' B2 D F2 D' L2 R2 F2 R2 U' L R' U2 L' R'",
    "R2 B2 R2 U B2 U' B2 L2 U' R2 U L2 U' L R' U2 L' R'",
    "R2 B2 D F2 D' R2 D B2 R2 U F2 L' R' U2 L' R'",
    "U2 L2 F2 D B2 D' L2 D F2 L2 U B2 L' R' U2 L' R'"
  ],
  "444.pll.bb": [
    "D B2 D' L2 R2 B2 U L2 U' B2 L2 R2 U L R' U2 L' R'",
    "U' R2 B2 L2 F2 U L2 U' R2 U B2 R2 D L R' U2 L' R'",
    "L2 R2 D R2 D' B2 U L2 U' B2 U F2 U' L' R' U2 L' R'",
    "F2 D' B2 F2 R2 D F2 U' B2 L2 F2 R2 U L R' F2 L' R'"
  ],
  "444.pll.ca": [
    "U' D B2 D' L2 R2 B2 U L2 U' B2 L2 R2 U L R' U2 L' R'",
    "R2 B2 L2 F2 U L2 U' R2 U B2 R2 D L R' U2 L' R'",
    "U' L2 R2 D R2 D' B2 U L2 U' B2 U F2 U' L' R' U2 L' R'",
    "U F2 D' B2 F2 R2 D F2 U' B2 L2 F2 R2 U L R' F2 L' R'"
  ],
  "444.pll.cb": [
    "U' D' B2 D R2 L2 B2 U' R2 U B2 R2 L2 U' R' L U2 R L",
    "U2 L2 B2 R2 F2 U' R2 U L2 U' B2 L2 D' R' L U2 R L",
    "U' R2 L2 D' L2 D B2 U' R2 U B2 U' F2 U R L U2 R L",
    "U F2 D B2 F2 L2 D' F2 U B2 R2 F2 L2 U' R' L F2 R L"
  ],
  "444.pll.da": [
    "U2 R2 U' F2 U L2 R2 F2 L2 R2 U' F2 U L R' U2 L' R'",
    "R2 B2 F2 D' R2 D R2 U' B2 U B2 F2 L R' U2 L' R'",
    "U F2 D R2 D' L2 D R2 B2 L2 F2 U B2 L R' U2 L' R'",
    "U' B2 D L2 D' R2 D L2 F2 R2 B2 U F2 L' R U2 L' R'"
  ],
  "444.pll.db": [
    "L2 U F2 U' F2 R2 F2 L2 U' R2 U L2 F2 L' R' U2 L' R'",
    "U2 R2 U B2 D' R2 D F2 L2 B2 L2 F2 U' L R' U2 L' R'",
    "U' R2 F2 L2 R2 D B2 D' R2 U R2 U' F2 L' R U2 L' R'",
    "U F2 D' L2 U B2 U' B2 L2 F2 R2 U' B2 L R' U2 L' R'"
  ],
  "444.pll.pa": [
    "L2 D' F2 D B2 L2 B2 F2 U F2 U' L2 F2 R L U2 R L",
    "U2 F2 R2 D R2 F2 L2 B2 D L2 D' L2 U R' L U2 R L",
    "R2 B2 L2 D' R2 D' L2 D L2 U' F2 U B2 R' L U2 R L",
    "U' F2 D B2 R2 U R2 U' B2 F2 L2 U B2 R' L U2 R L"
  ],
  "444.pll.pb": [
    "R2 D F2 D' B2 R2 B2 F2 U' F2 U R2 F2 L' R' U2 L' R'",
    "U2 F2 L2 D' L2 F2 R2 B2 D' R2 D R2 U' L R' U2 L' R'",
    "L2 B2 R2 D L2 D R2 D' R2 U F2 U' B2 L R' U2 L' R'",
    "U F2 D' B2 L2 U' L2 U B2 F2 R2 U' B2 L R' U2 L' R'"
  ],
  "444.pll.ka": [
    "R2 U B2 U R2 U' R2 U2 B2 U B2 U L R' U2 L' R'",
    "D B2 D' B2 F2 R2 U F2 U' R2 B2 F2 U L R' U2 L' R'",
    "B2 D' R2 D R2 U2 B2 R2 B2 U' B2 U' B2 L R' U2 L' R'",
    "L2 R2 F2 U B2 L2 U F2 U' L2 B2 U' F2 L' R' U2 L' R'"
  ],
  "444.pll.kb": [
    "D F2 U R2 F2 U B2 U' F2 R2 D' R2 U2 L' R' U2 L' R'",
    "D' F2 U R2 F2 U B2 U' F2 R2 D' R2 D2 L' R' U2 L' R'",
    "F2 D R2 D' L2 D R2 D B2 L2 F2 U2 B2 L R' U2 L' R'",
    "B2 D' B2 D' L2 B2 R2 U2 R2 U B2 U' F2 L' R U2 L' R'"
  ],
  "444.pll.q": [
    "B2 U' L2 U2 F2 U R2 U' F2 U2 L2 U' B F R2 B' F'",
    "B2 U' L2 U2 F2 U R2 U' F2 U2 L2 U' B F R2 B' F'",
    "U R2 U' B2 U2 L2 U F2 U' L2 U2 B2 U' L R F2 L' R'",
    "U' R2 U B2 D2 F2 R2 U B2 U F2 D2 L2 U L R' F2 L' R'"
  ],
  "444.pll.sa": [
    "U' B2 U' L2 U2 F2 U R2 U' F2 U2 L2 U' B F R2 B' F'",
    "U B2 U' L2 U2 F2 U R2 U' F2 U2 L2 U' B F R2 B' F'",
    "R2 U' B2 U2 L2 U F2 U' L2 U2 B2 U' L R F2 L' R'",
    "R2 U B2 D2 F2 R2 U B2 U F2 D2 L2 U L R' F2 L' R'"
  ],
  "444.pll.sb": [
    "U B2 D F2 D' R2 U F2 D F2 U' B2 U L' R U2 L' R'",
    "U' F2 D B2 D' L2 U B2 D B2 U' F2 U L R' U2 L' R'",
    "U D F2 D' L2 U L2 U' F2 U' R2 U R2 U L R F2 L' R'",
    "R2 U' R2 D B2 D' B2 U' L2 U L2 U L R B2 L' R'"
  ],
  "444.pll.x": [
    "U2 B2 D F2 D' R2 U F2 D F2 U' B2 U L' R U2 L' R'",
    "F2 D B2 D' L2 U B2 D B2 U' F2 U L R' U2 L' R'",
    "D F2 D' L2 U L2 U' F2 U' R2 U R2 U L R F2 L' R'",
    "U' R2 U' R2 D B2 D' B2 U' L2 U L2 U L R B2 L' R'"
  ],
  "444.pll.m": [
    "R2 D' L2 B2 R2 U2 F2 R2 D' B2 U B2 U' L R' U2 L' R'",
    "R2 D L2 B2 L2 D2 R2 U' F2 D R2 B2 U L R' U2 L' R'",
    "U B2 U L2 U' R2 U' B2 L2 B2 U2 F2 D' L' R F2 L' R'",
    "F2 R2 U R2 F2 U' F2 U F2 L2 U R2 U' L' R' F2 L' R'"
  ],
  "444.pll.adj-c": [
    "R2 B2 R2 U2 F2 D R2 U' B2 U R2 F2 U L' R U2 L' R'",
    "R2 B2 R2 U2 F2 D' L2 U B2 U' L2 F2 U' L R' U2 L' R'",
    "B2 U B2 U B2 U' B2 L2 U2 L2 U' L2 U L' R B2 L' R'",
    "F2 L2 D' B2 D L2 U' F2 L2 R2 U R2 U L R' F2 L R'"
  ],
  "444.pll.diag-c": [
    "B2 L2 U2 R2 D R2 F2 D2 F2 U F2 L2 U2 L R' U2 L' R'",
    "R2 U2 B2 D B2 L2 D2 F2 R2 D' F2 L2 D2 L R' U2 L' R'",
    "U' F2 L2 U2 L2 U' F2 U2 L2 U L2 F2 U2 L' R U2 L R'",
    "U F2 L2 U2 L2 U' F2 U2 L2 U L2 F2 U2 L' R U2 L R'"
  ]
};
