/**
 * GENERATED by scripts/gen-cases.mjs from the verified JPerm extraction —
 * do not edit by hand. Build-time companion to fullsets.gen.ts: recognition text and alternate algorithms per generated case. Never import from client code.
 */
import type { AlgVariant } from "./algs";

export const RICH: Record<string, { recognition: string; alternates: AlgVariant[] }> = {
  "oll.1": {
    "recognition": "Dot; full yellow bars on both the left and right faces.",
    "alternates": []
  },
  "oll.2": {
    "recognition": "Dot; one full yellow bar, on the back face only.",
    "alternates": [
      {
        "moves": "y' F R U R' U' F' f R U R' U' f'"
      },
      {
        "moves": "y' F R U R' U' S R U R' U' f'"
      }
    ]
  },
  "oll.3": {
    "recognition": "Dot plus one yellow corner at front-left; back face yellow on its left half.",
    "alternates": [
      {
        "moves": "y F U R U' R' F' U F R U R' U' F'"
      },
      {
        "moves": "y' f R U R' U' f' U' F R U R' U' F'"
      }
    ]
  },
  "oll.4": {
    "recognition": "Dot plus one yellow corner at front-right; back face yellow on its right half.",
    "alternates": [
      {
        "moves": "y F U R U' R' F' U' F R U R' U' F'"
      },
      {
        "moves": "y' f R U R' U' f' U F R U R' U' F'"
      }
    ]
  },
  "oll.5": {
    "recognition": "Yellow 2x2 square in the back-left; two side yellows on the right face toward the back.",
    "alternates": [
      {
        "moves": "y2 r' U2 R U R' U r"
      }
    ]
  },
  "oll.6": {
    "recognition": "Yellow 2x2 square in the back-right; two side yellows on the left face toward the back.",
    "alternates": []
  },
  "oll.7": {
    "recognition": "Small bolt down the left, tip corner at front-left; front face yellow on its right half.",
    "alternates": []
  },
  "oll.8": {
    "recognition": "Small bolt down the right, tip corner at front-right; front face yellow on its left half.",
    "alternates": [
      {
        "moves": "R U2 R' U2 R' F R F'"
      },
      {
        "moves": "y2 r' U' R U' R' U2 r"
      }
    ]
  },
  "oll.9": {
    "recognition": "Small fish hugging back-left, lone corner front-right; front face yellow on its left half.",
    "alternates": []
  },
  "oll.10": {
    "recognition": "Small fish hugging front-left, lone corner back-right; back face yellow on its left half.",
    "alternates": [
      {
        "moves": "y2 r U R' U R U' R' U' r' R (U R U' R')"
      }
    ]
  },
  "oll.11": {
    "recognition": "Small bolt along the back, tip corner at back-right; front face yellow on its right half.",
    "alternates": [
      {
        "moves": "y2 r' R2 U R' U R U2 R' U M'"
      }
    ]
  },
  "oll.12": {
    "recognition": "Small bolt along the back, tip corner at back-left; front face yellow on its left half.",
    "alternates": []
  },
  "oll.13": {
    "recognition": "Middle bar with corner at front-left; back face yellow on its left half.",
    "alternates": [
      {
        "moves": "r U' r' U' r U r' y' R' U R"
      }
    ]
  },
  "oll.14": {
    "recognition": "Middle bar with corner at front-right; back face yellow on its right half.",
    "alternates": []
  },
  "oll.15": {
    "recognition": "Middle bar with corner at back-left; front face yellow on its right half.",
    "alternates": [
      {
        "moves": "y2 r' U' r R' U' R U r' U r"
      }
    ]
  },
  "oll.16": {
    "recognition": "Middle bar with corner at back-right; front face yellow on its left half.",
    "alternates": []
  },
  "oll.17": {
    "recognition": "Dot with two corners up on the diagonal: back-left and front-right.",
    "alternates": [
      {
        "moves": "y2 R U R' U R' F R F' U2 R' F R F'"
      }
    ]
  },
  "oll.18": {
    "recognition": "Dot with both back corners up; full yellow bar on the front face.",
    "alternates": [
      {
        "moves": "y R U2 R' R' F R F' U2 M' (U R U' r')"
      }
    ]
  },
  "oll.19": {
    "recognition": "Dot, both back corners up; left and right faces yellow at middle and front (no bar).",
    "alternates": []
  },
  "oll.20": {
    "recognition": "Dot with all four corners up; every side face shows a single mid yellow.",
    "alternates": [
      {
        "moves": "r' R U (R U R' U') M2 U R U' r'"
      }
    ]
  },
  "oll.21": {
    "recognition": "Cross only: yellow headlights face you and repeat on the back; left and right show none.",
    "alternates": [
      {
        "moves": "y R U R' U R U' R' U R U2 R'"
      }
    ]
  },
  "oll.22": {
    "recognition": "Cross only: headlights on the left face; front and back each show one yellow, right end.",
    "alternates": []
  },
  "oll.23": {
    "recognition": "Cross plus both front corners solved; headlights on the back, no other side yellows.",
    "alternates": [
      {
        "moves": "y2 R2 D R' U2 R D' R' U2 R'"
      }
    ]
  },
  "oll.24": {
    "recognition": "Cross plus both right corners solved; front and back each show a yellow at the left end.",
    "alternates": [
      {
        "moves": "y R U R D R' U' R D' R2"
      }
    ]
  },
  "oll.25": {
    "recognition": "Cross plus a diagonal pair; yellow faces you front-right, another at the back of the left face.",
    "alternates": [
      {
        "moves": "y' R' F R B' R' F' R B"
      }
    ]
  },
  "oll.26": {
    "recognition": "Cross plus one corner, back-right; a lone yellow faces you at the front-left.",
    "alternates": [
      {
        "moves": "y' R' U' R U' R' U2 R"
      }
    ]
  },
  "oll.27": {
    "recognition": "Cross plus one corner, front-left; a lone yellow faces you at the front-right.",
    "alternates": [
      {
        "moves": "y' R' U2 (R U R' U) R"
      }
    ]
  },
  "oll.28": {
    "recognition": "All corners up; two adjacent edges (right and front) flipped, middle yellows on those faces.",
    "alternates": []
  },
  "oll.29": {
    "recognition": "Both right-side corners up with back and left edges; front face yellow on its left half.",
    "alternates": []
  },
  "oll.30": {
    "recognition": "Both front corners up, back and left edges; back face shows no yellow.",
    "alternates": [
      {
        "moves": "F U (R U2 R' U') R U2 R' U' F'"
      }
    ]
  },
  "oll.31": {
    "recognition": "P along the right edge; no solid side bar — yellow pair on the front's left.",
    "alternates": []
  },
  "oll.32": {
    "recognition": "P along the left edge; no solid side bar — yellow pair on the front's right.",
    "alternates": [
      {
        "moves": "y2 S R U R' U' R' F R f'"
      }
    ]
  },
  "oll.33": {
    "recognition": "Sideways T, stem left; left face clean, front and back each show a pair on the left half.",
    "alternates": []
  },
  "oll.34": {
    "recognition": "C shape opening toward the front; lone mid yellow on both the back and front faces.",
    "alternates": [
      {
        "moves": "R U R' U' B' R' F R F' B"
      }
    ]
  },
  "oll.35": {
    "recognition": "2x2 yellow block at front-right, lone corner back-left; one yellow on every side face.",
    "alternates": []
  },
  "oll.36": {
    "recognition": "W runs back-left to front-right; right face clean, left face pair toward the front.",
    "alternates": [
      {
        "moves": "y2 R' U' R U' R' U R U R B' R' B"
      }
    ]
  },
  "oll.37": {
    "recognition": "2x2 yellow block at back-left, lone corner front-right; no yellow on the back or left faces.",
    "alternates": [
      {
        "moves": "F R U' R' U' R U R' F'"
      }
    ]
  },
  "oll.38": {
    "recognition": "W runs back-right to front-left; left face clean, right face pair toward the front.",
    "alternates": []
  },
  "oll.39": {
    "recognition": "Big bolt, corners at back-right and front-left; back face yellow on its left half.",
    "alternates": [
      {
        "moves": "y2 R B' R' U' R U B U' R'"
      }
    ]
  },
  "oll.40": {
    "recognition": "Big bolt, corners at back-left and front-right; back face yellow on its right half.",
    "alternates": []
  },
  "oll.41": {
    "recognition": "Both front corners up, back and left edges; yellow headlights on the back face.",
    "alternates": []
  },
  "oll.42": {
    "recognition": "Both back corners up, left and front edges; yellow headlights on the front face.",
    "alternates": []
  },
  "oll.43": {
    "recognition": "P along the right edge; solid yellow bar on the left face.",
    "alternates": [
      {
        "moves": "R' U' F R' F' R U R"
      }
    ]
  },
  "oll.44": {
    "recognition": "P along the left edge; solid yellow bar on the right face.",
    "alternates": [
      {
        "moves": "y2 f R U R' U' f'"
      }
    ]
  },
  "oll.45": {
    "recognition": "Sideways T, stem left; headlights on the left face, single mid yellows on front and back.",
    "alternates": []
  },
  "oll.46": {
    "recognition": "C shape opening toward the left; full yellow bar on the right face.",
    "alternates": []
  },
  "oll.47": {
    "recognition": "L in the back-right; right face shows yellow at both ends, no solid bar anywhere.",
    "alternates": [
      {
        "moves": "F' L' U' L U L' U' L U F"
      },
      {
        "moves": "y' F U R U' R' F' R U R' U R U2 R'"
      }
    ]
  },
  "oll.48": {
    "recognition": "L in the back-left; left face shows yellow at both ends, no solid bar anywhere.",
    "alternates": []
  },
  "oll.49": {
    "recognition": "L in the back-right; solid yellow bar on the left face, yellow pair on the front's right.",
    "alternates": []
  },
  "oll.50": {
    "recognition": "L in the front-right; solid yellow bar on the left face, yellow pair on the back's right.",
    "alternates": []
  },
  "oll.51": {
    "recognition": "Middle bar; back and front faces yellow on their left halves, headlights on the right.",
    "alternates": [
      {
        "moves": "y2 f R U R' U' R U R' U' f'"
      }
    ]
  },
  "oll.52": {
    "recognition": "Vertical bar running back to front; full yellow bar on the right face.",
    "alternates": [
      {
        "moves": "y2 R' F' U' F U' (R U R' U) R"
      },
      {
        "moves": "R U R' U R U' y R U' R' F'"
      }
    ]
  },
  "oll.53": {
    "recognition": "L in the back-right; solid yellow bar faces you on the front, headlights on the back.",
    "alternates": [
      {
        "moves": "y2 r' U2 (R U R' U') R U R' U r"
      },
      {
        "moves": "y r' U' R U' R' U R U' R' U2 r"
      }
    ]
  },
  "oll.54": {
    "recognition": "L in the back-left; solid yellow bar faces you on the front, headlights on the back.",
    "alternates": [
      {
        "moves": "y r U R' U R U' R' U R U2 r'"
      }
    ]
  },
  "oll.55": {
    "recognition": "Middle bar; full yellow bars on both the back and front faces.",
    "alternates": [
      {
        "moves": "y R U2 R2 U' R U' R' U2 F R F'"
      }
    ]
  },
  "oll.56": {
    "recognition": "Middle bar; headlights on both left and right faces, lone mid yellow front and back.",
    "alternates": [
      {
        "moves": "(r U r') U R U' R' U R U' R' (r U' r')"
      },
      {
        "moves": "(r U r') U R U' R' U R U' M' U' r'"
      }
    ]
  },
  "oll.57": {
    "recognition": "All corners up, H on top; two opposite edges (back and front) flipped, middle yellows there.",
    "alternates": []
  },
  "pll.h": {
    "recognition": "Headlights on all four sides with the opposite color between them; each edge swaps across.",
    "alternates": [
      {
        "moves": "M2 U' M2 U2 M2 U' M2"
      }
    ]
  },
  "pll.z": {
    "recognition": "Headlights on every side with an adjacent color between them—H shows the opposite instead.",
    "alternates": [
      {
        "moves": "y M' U' M2 U' M2 U' M' U2 M2"
      },
      {
        "moves": "y M2 U M2 U M' U2 M2 U2 M'"
      },
      {
        "moves": "M2 U' M2 U' M' U2 M2 U2 M'"
      }
    ]
  },
  "pll.ua": {
    "recognition": "3-bar at the back; the other three edges cycle counterclockwise—front edge goes right.",
    "alternates": [
      {
        "moves": "R U' R U R U R U' R' U' R2"
      },
      {
        "moves": "y2 R2 U' R' U' R U R U R U' R"
      }
    ]
  },
  "pll.ub": {
    "recognition": "3-bar at the back; the other three edges cycle clockwise—front edge goes left.",
    "alternates": [
      {
        "moves": "R2 U (R U R' U') R' U' R' U R'"
      },
      {
        "moves": "y2 R' U R' U' R' U' (R' U R U) R2"
      },
      {
        "moves": "y2 R' U R' U' R3 U' (R' U R U) R2"
      }
    ]
  },
  "pll.aa": {
    "recognition": "Left headlights, all edges solved; 2-blocks meet at the front-right corner, which stays.",
    "alternates": [
      {
        "moves": "y' x' L' U L' D2 L U' L' D2 L2"
      },
      {
        "moves": "y x R' U R' D2 R U' R' D2 R2"
      },
      {
        "moves": "y2 x' R2 D2 R' U' R D2 R' U R'"
      }
    ]
  },
  "pll.ab": {
    "recognition": "Left headlights, all edges solved; 2-blocks meet at the back-right corner, which stays.",
    "alternates": [
      {
        "moves": "y x L U' L D2 L' U L D2 L2"
      },
      {
        "moves": "y2 x R2 D2 R U R' D2 R U' R"
      },
      {
        "moves": "y' x' R U' R D2 R' U R D2 R2"
      }
    ]
  },
  "pll.e": {
    "recognition": "No headlights anywhere; every edge already matches its center—corners swap front to back.",
    "alternates": [
      {
        "moves": "x' R U' R' D R U R' D' R U R' D R U' R' D'"
      }
    ]
  },
  "pll.f": {
    "recognition": "Solved 3-bar on the left, nothing else pairs; the right corners and front/back edges swap.",
    "alternates": []
  },
  "pll.ja": {
    "recognition": "Bar on the left joins the front 2-block—solved L around front-left; right corners swap.",
    "alternates": [
      {
        "moves": "y2 L' U' L F L' U' L U L F' L2 U L"
      },
      {
        "moves": "y' R' U L' U2 R U' R' U2 R L"
      }
    ]
  },
  "pll.jb": {
    "recognition": "Bar on the left joins the back 2-block—the L wraps back-left, not front-left as in Ja.",
    "alternates": []
  },
  "pll.ra": {
    "recognition": "Headlights on the left with a 2-block on the front beside them; Rb's block is on the back.",
    "alternates": [
      {
        "moves": "R U R' F' R U2 R' U2 R' F R U R U2 R'"
      },
      {
        "moves": "y' L U2 L' U2 L F' L' U' L U L F L2"
      }
    ]
  },
  "pll.rb": {
    "recognition": "Headlights on the left with a 2-block on the back beside them; Ra's block is on the front.",
    "alternates": [
      {
        "moves": "y' R' U2 R U2 R' F R U R' U' R' F' R2"
      },
      {
        "moves": "R' U2 R' D' R U' R' D R U R U' R' U' R"
      }
    ]
  },
  "pll.t": {
    "recognition": "Headlights on the left with 2-blocks on both front and back; the two right corners swap.",
    "alternates": []
  },
  "pll.y": {
    "recognition": "No headlights; solved 2-blocks at front-left and back-right; the other two corners swap.",
    "alternates": [
      {
        "moves": "F R' F R2 U' R' U' R U R' F' R U R' U' F'"
      }
    ]
  },
  "pll.v": {
    "recognition": "No headlights; solved blocks wrap the front-left corner; back-left and front-right swap.",
    "alternates": [
      {
        "moves": "R' U R' U' R D' R' D R' U D' R2 U' R2 D R2"
      },
      {
        "moves": "z D' R2 D R2 U R' D' R U' R U R' D R U' z'"
      },
      {
        "moves": "R U2 R' D R U' R U' R U R2 D R' U' R D2"
      },
      {
        "moves": "x' R' F R F' U R U2 R' U' R U' R' U2 R U R' U'"
      }
    ]
  },
  "pll.na": {
    "recognition": "Every side has a 2-block; the front block is on the right—back-right and front-left swap.",
    "alternates": [
      {
        "moves": "z U R' D R2 U' R D' U R' D R2 U' R D'"
      }
    ]
  },
  "pll.nb": {
    "recognition": "Every side has a 2-block; the front block is on the left—back-left and front-right swap.",
    "alternates": [
      {
        "moves": "z D' R U' R2 D R' U D' R U' R2 D R' U"
      }
    ]
  },
  "pll.ga": {
    "recognition": "Headlights left; lone 2-block on the front's right side; back color between the lights.",
    "alternates": [
      {
        "moves": "R2 u R' U R' U' R u' R2 y' R' U R"
      }
    ]
  },
  "pll.gb": {
    "recognition": "Headlights left; lone 2-block on the back end of the right face (Gd: front end).",
    "alternates": [
      {
        "moves": "y F' U' F R2 u R' U R U' R u' R2"
      }
    ]
  },
  "pll.gc": {
    "recognition": "Headlights left; lone 2-block on the back's right side; front color between the lights.",
    "alternates": [
      {
        "moves": "y2 R2 F2 R U2 R U2 R' F R U R' U' R' F R2"
      },
      {
        "moves": "R2 u' R U' R U R' u R2 y R U' R'"
      }
    ]
  },
  "pll.gd": {
    "recognition": "Headlights left; lone 2-block on the front end of the right face (Gb: back end).",
    "alternates": [
      {
        "moves": "R U R' y' R2 u' R U' R' U R' u R2"
      }
    ]
  },
  "f2l.1": {
    "recognition": "Free Pairs",
    "alternates": []
  },
  "f2l.2": {
    "recognition": "Free Pairs",
    "alternates": []
  },
  "f2l.3": {
    "recognition": "Free Pairs",
    "alternates": []
  },
  "f2l.4": {
    "recognition": "Free Pairs",
    "alternates": []
  },
  "f2l.5": {
    "recognition": "Disconnected Pairs",
    "alternates": [
      {
        "moves": "y U l' U L U' L' U' l"
      }
    ]
  },
  "f2l.6": {
    "recognition": "Disconnected Pairs",
    "alternates": [
      {
        "moves": "U' r U' R' U R U r'"
      }
    ]
  },
  "f2l.7": {
    "recognition": "Disconnected Pairs",
    "alternates": [
      {
        "moves": "y l U2 L2' U' L2 U' l'"
      }
    ]
  },
  "f2l.8": {
    "recognition": "Disconnected Pairs",
    "alternates": [
      {
        "moves": "r' U2 R2 U R2' U r"
      }
    ]
  },
  "f2l.9": {
    "recognition": "Disconnected Pairs",
    "alternates": [
      {
        "moves": "y U2 (L' U L) U (L' U' L)"
      }
    ]
  },
  "f2l.10": {
    "recognition": "Disconnected Pairs",
    "alternates": [
      {
        "moves": "U2 (R U' R') U' (R U R')"
      }
    ]
  },
  "f2l.11": {
    "recognition": "Connected Pairs",
    "alternates": [
      {
        "moves": "y (L' U L) U' (L' U L) U2 (L' U L)"
      },
      {
        "moves": "U' (R U2 R') U y (L' U' L)"
      }
    ]
  },
  "f2l.12": {
    "recognition": "Connected Pairs",
    "alternates": [
      {
        "moves": "(R U' R') U (R U' R') U2 (R U' R')"
      },
      {
        "moves": "y U L' U2 L U' y' R U R'"
      }
    ]
  },
  "f2l.13": {
    "recognition": "Connected Pairs",
    "alternates": []
  },
  "f2l.14": {
    "recognition": "Connected Pairs",
    "alternates": []
  },
  "f2l.15": {
    "recognition": "Connected Pairs",
    "alternates": [
      {
        "moves": "y (L' U L) y' U2 (R U R')"
      },
      {
        "moves": "y' (R2' F R F' R) U2 (R' U R)"
      },
      {
        "moves": "y2 (f' L f) U2 (L U L')"
      }
    ]
  },
  "f2l.16": {
    "recognition": "Connected Pairs",
    "alternates": [
      {
        "moves": "(R U' R') y U2 (L' U' L)"
      },
      {
        "moves": "y2 (L2 F' L' F L') U2 (L U' L')"
      },
      {
        "moves": "y' (f R' f') U2 R' U' R"
      }
    ]
  },
  "f2l.17": {
    "recognition": "Connected Pairs",
    "alternates": []
  },
  "f2l.18": {
    "recognition": "Connected Pairs",
    "alternates": []
  },
  "f2l.19": {
    "recognition": "Disconnected Pairs",
    "alternates": []
  },
  "f2l.20": {
    "recognition": "Disconnected Pairs",
    "alternates": []
  },
  "f2l.21": {
    "recognition": "Disconnected Pairs",
    "alternates": [
      {
        "moves": "y F R U2 R' F'"
      }
    ]
  },
  "f2l.22": {
    "recognition": "Disconnected Pairs",
    "alternates": [
      {
        "moves": "F' L' U2 L F"
      }
    ]
  },
  "f2l.23": {
    "recognition": "Connected Pairs",
    "alternates": [
      {
        "moves": "U (F R' F' R) U (R U R')"
      },
      {
        "moves": "y U L' U' (L2 F' L' F) (L' U L)"
      },
      {
        "moves": "y F' (U' L' U L) F (L' U L)"
      }
    ]
  },
  "f2l.24": {
    "recognition": "Connected Pairs",
    "alternates": [
      {
        "moves": "y U' (F' L F L') U' (L' U' L)"
      },
      {
        "moves": "U' R U (R2' F R F') (R U' R')"
      },
      {
        "moves": "F (U R U' R') F' (R U' R')"
      }
    ]
  },
  "f2l.25": {
    "recognition": "Corner In Slot",
    "alternates": [
      {
        "moves": "(R' F' R) (U R U' R') F"
      },
      {
        "moves": "U' F' (R U R' U') (R' F R)"
      },
      {
        "moves": "y U' (L' U L) (F' L F L')"
      },
      {
        "moves": "y2 U' M U L U' M' U L'"
      },
      {
        "moves": "y' U' R' U M U' R U M'"
      }
    ]
  },
  "f2l.26": {
    "recognition": "Corner In Slot",
    "alternates": [
      {
        "moves": "y (L F L') (U' L' U L) F'"
      },
      {
        "moves": "y U F (L' U' L U) (L F' L')"
      },
      {
        "moves": "U (R U' R') (F R' F' R)"
      },
      {
        "moves": "y' U M U' R' U M' U' R"
      },
      {
        "moves": "y2 U L U' M U L' U' M'"
      }
    ]
  },
  "f2l.27": {
    "recognition": "Corner In Slot",
    "alternates": []
  },
  "f2l.28": {
    "recognition": "Corner In Slot",
    "alternates": []
  },
  "f2l.29": {
    "recognition": "Corner In Slot",
    "alternates": [
      {
        "moves": "M' (U R U' R') (U R U' r')"
      },
      {
        "moves": "(R' F R F')2"
      }
    ]
  },
  "f2l.30": {
    "recognition": "Corner In Slot",
    "alternates": [
      {
        "moves": "y M' (U' L' U L) (U' L' U l)"
      },
      {
        "moves": "y (L F' L' F)2"
      }
    ]
  },
  "f2l.31": {
    "recognition": "Edge In Slot",
    "alternates": [
      {
        "moves": "(R U' R') (F' U2 F)"
      },
      {
        "moves": "y' R' U R' F R F' R"
      },
      {
        "moves": "y' U' (R' U2 R) (f R f')"
      }
    ]
  },
  "f2l.32": {
    "recognition": "Edge In Slot",
    "alternates": []
  },
  "f2l.33": {
    "recognition": "Edge In Slot",
    "alternates": [
      {
        "moves": "y U (L' U2 L) U' (L' U' L)"
      },
      {
        "moves": "U' R U' R' U2 R U' R'"
      }
    ]
  },
  "f2l.34": {
    "recognition": "Edge In Slot",
    "alternates": [
      {
        "moves": "U' (R U2 R') U (R U R')"
      },
      {
        "moves": "y U (L' U L) U2 (L' U L)"
      }
    ]
  },
  "f2l.35": {
    "recognition": "Edge In Slot",
    "alternates": [
      {
        "moves": "U2 (R U R') (F R' F' R)"
      },
      {
        "moves": "U M' (U R U' r') (R U' R')"
      },
      {
        "moves": "y2 U2 (L U L') y' U' (L' U L)"
      },
      {
        "moves": "y2 U2 L U M U L' U' M'"
      },
      {
        "moves": "y' U' (f R f') U (R' U' R)"
      }
    ]
  },
  "f2l.36": {
    "recognition": "Edge In Slot",
    "alternates": [
      {
        "moves": "y U2 (L' U' L) (F' L F L')"
      },
      {
        "moves": "y U' M' (U' L' U l) (L' U L)"
      },
      {
        "moves": "y' U2 (R' U' R) y U (R U' R')"
      },
      {
        "moves": "y' U2 R' U' M U' R U M'"
      },
      {
        "moves": "y2 U (f' L' f) U' (L U L')"
      }
    ]
  },
  "f2l.37": {
    "recognition": "Pieces In Slot",
    "alternates": [
      {
        "moves": "y L2 U2 F' L2' F U2 L U' L"
      },
      {
        "moves": "y' (f R' f') U (R' U2' R) U (R' U2' R)"
      },
      {
        "moves": "y2 (f' L f) U' (L U2 L') U' (L U2 L')"
      }
    ]
  },
  "f2l.38": {
    "recognition": "Pieces In Slot",
    "alternates": []
  },
  "f2l.39": {
    "recognition": "Pieces In Slot",
    "alternates": []
  },
  "f2l.40": {
    "recognition": "Pieces In Slot",
    "alternates": [
      {
        "moves": "(F' L' U2 L F) (R U R')"
      },
      {
        "moves": "y' R2' F' U' F U R U' R"
      },
      {
        "moves": "y2 L U' L U F U' F' L2'"
      }
    ]
  },
  "f2l.41": {
    "recognition": "Pieces In Slot",
    "alternates": [
      {
        "moves": "y (F R U2' R' F') (L' U' L)"
      },
      {
        "moves": "y2 L2 F U F' U' L' U L'"
      },
      {
        "moves": "y' R' U R' U' F' U F R2"
      }
    ]
  },
  "555.l2e-1": {
    "recognition": "Last two edges (5×5)",
    "alternates": []
  },
  "555.l2e-2": {
    "recognition": "Last two edges (5×5)",
    "alternates": [
      {
        "moves": "z y Uw F' D' F D' L D L' Uw' y' z'"
      }
    ]
  },
  "555.l2e-3": {
    "recognition": "Last two edges (5×5)",
    "alternates": [
      {
        "moves": "r' l U' R' U R' F R F' r l'"
      },
      {
        "moves": "x' z' E' L' U' L U' F U F' E z x"
      }
    ]
  },
  "555.l2e-4": {
    "recognition": "Last two edges (5×5)",
    "alternates": [
      {
        "moves": "Rw2 F2 U2 r2 U2 F2 Rw2"
      },
      {
        "moves": "z' y' Uw2' R2 F2 Uw2' F2 R2' Uw2'"
      },
      {
        "moves": "y x' Uw2 L2 F2 Uw2 F2 L2 Uw2"
      }
    ]
  },
  "555.l2e-5": {
    "recognition": "Last two edges (5×5)",
    "alternates": [
      {
        "moves": "r2 B2 r' U2 r' U2 x' U2 r' U2 r U2 r' U2 r2 U2"
      }
    ]
  },
  "555.l2e-6": {
    "recognition": "The last edge group looks flipped: its two wings show the side colour on top and yellow on the side, the middle piece is right. Hold it at UF.",
    "alternates": [
      {
        "moves": "Rw' U2 3Rw U2 3Rw' F2 Rw2 U2 Rw U2 Rw' U2 F2 Rw2 F2"
      },
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 3Rw' U2 Rw U2 Rw' U2 Rw'"
      },
      {
        "moves": "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2"
      }
    ]
  },
  "555.l2e-7": {
    "recognition": "Last two edges (5×5)",
    "alternates": [
      {
        "moves": "Lw' U2 Lw' U2 F2 Lw' F2 Rw U2 Rw' U2 Lw2"
      }
    ]
  },
  "555.l2e-8": {
    "recognition": "Last two edges (5×5)",
    "alternates": [
      {
        "moves": "l2 F2 U2 r U2 r2 F2 r U2 l2 U2 F2 l' F2"
      },
      {
        "moves": "F2 Rw U2 Rw U2' Rw' F2 Rw' U2 Rw' U2' Rw U2 Rw' U2' Rw2"
      }
    ]
  },
  "555.l2e-9": {
    "recognition": "Last two edges (5×5)",
    "alternates": [
      {
        "moves": "r2 F2 U2 r U2 r2 F2 r U2 r2 U2 F2 r F2"
      },
      {
        "moves": "x' U2 Rw U2 Rw U2' Rw' F2 Rw' U2 Rw' U2' Rw U2 Rw' U2' Rw2 U2 F2 U2 F2 x"
      },
      {
        "moves": "Rw2 F2 U2 Lw' U2 Lw2 F2 Lw' U2 Rw2 U2 F2 Rw F2"
      }
    ]
  },
  "555.l2e-10": {
    "recognition": "Last two edges (5×5)",
    "alternates": []
  },
  "555.l2e-11": {
    "recognition": "Last two edges (5×5)",
    "alternates": []
  },
  "555.l2e-12": {
    "recognition": "Last two edges (5×5)",
    "alternates": [
      {
        "moves": "Rw' U2 Rw' U2 B2 Rw' B2 Rw' F2 Lw2 F2 Rw U2 Rw2"
      }
    ]
  },
  "555.l2e-13": {
    "recognition": "Last two edges (5×5)",
    "alternates": [
      {
        "moves": "Rw U R U' Rw2 U' R U Rw2 U R U' Rw'"
      }
    ]
  },
  "444.oll.solved": {
    "recognition": "4 Corners",
    "alternates": [
      {
        "moves": "y' Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U' F U R U' R' F'"
      },
      {
        "moves": "y2 R U R' F' Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' F R U' R'"
      }
    ]
  },
  "444.oll.u-f": {
    "recognition": "2 Corners",
    "alternates": []
  },
  "444.oll.u-r": {
    "recognition": "2 Corners",
    "alternates": []
  },
  "444.oll.u-l": {
    "recognition": "2 Corners",
    "alternates": []
  },
  "444.oll.u-b": {
    "recognition": "2 Corners",
    "alternates": []
  },
  "444.oll.t-f": {
    "recognition": "2 Corners",
    "alternates": []
  },
  "444.oll.t-r": {
    "recognition": "2 Corners",
    "alternates": [
      {
        "moves": "y2 F' L' U L U L' U' L F Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw'"
      },
      {
        "moves": "y2 L2 B2 L2 Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' L2 B2 L2"
      }
    ]
  },
  "444.oll.t-l": {
    "recognition": "2 Corners",
    "alternates": [
      {
        "moves": "R2 B2 R2 Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R2 B2 R2"
      },
      {
        "moves": "y2 Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U2 R U R' U' R' F R F'"
      }
    ]
  },
  "444.oll.t-b": {
    "recognition": "2 Corners",
    "alternates": []
  },
  "444.oll.l-fr": {
    "recognition": "2 Corners",
    "alternates": []
  },
  "444.oll.l-fl": {
    "recognition": "2 Corners",
    "alternates": []
  },
  "444.oll.l-br": {
    "recognition": "2 Corners",
    "alternates": []
  },
  "444.oll.l-bl": {
    "recognition": "2 Corners",
    "alternates": []
  },
  "444.oll.sune-fr": {
    "recognition": "1 Corner",
    "alternates": [
      {
        "moves": "y2 Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U2 F R U R' U' F'"
      },
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U2 R U2 (R2 U' R2 U' R2) U2 R"
      }
    ]
  },
  "444.oll.sune-fl": {
    "recognition": "1 Corner",
    "alternates": []
  },
  "444.oll.sune-br": {
    "recognition": "1 Corner",
    "alternates": []
  },
  "444.oll.sune-bl": {
    "recognition": "1 Corner",
    "alternates": []
  },
  "444.oll.antisune-fr": {
    "recognition": "1 Corner",
    "alternates": []
  },
  "444.oll.antisune-fl": {
    "recognition": "1 Corner",
    "alternates": [
      {
        "moves": "y2 Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' F R U R' U' F'"
      },
      {
        "moves": "m' U' L' U 3Lw Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U' L' U2 L"
      }
    ]
  },
  "444.oll.antisune-br": {
    "recognition": "1 Corner",
    "alternates": []
  },
  "444.oll.antisune-bl": {
    "recognition": "1 Corner",
    "alternates": []
  },
  "444.oll.h-fb": {
    "recognition": "0 Corners",
    "alternates": [
      {
        "moves": "y2 Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U R' U' R' F R F' U R"
      }
    ]
  },
  "444.oll.h-lr": {
    "recognition": "0 Corners",
    "alternates": []
  },
  "444.oll.pi-f": {
    "recognition": "0 Corners",
    "alternates": []
  },
  "444.oll.pi-r": {
    "recognition": "0 Corners",
    "alternates": []
  },
  "444.oll.pi-l": {
    "recognition": "0 Corners",
    "alternates": []
  },
  "444.oll.pi-b": {
    "recognition": "0 Corners",
    "alternates": []
  },
  "444.pll.pure-e": {
    "recognition": "Both last-layer edge pairs on one axis are swapped with the pair opposite them. The corners look shuffled here — that is a free U2, and the algorithm ignores it.",
    "alternates": []
  },
  "444.pll.adj-e": {
    "recognition": "Edges Only",
    "alternates": []
  },
  "444.pll.o-plus": {
    "recognition": "Edges Only",
    "alternates": []
  },
  "444.pll.o-minus": {
    "recognition": "Edges Only",
    "alternates": []
  },
  "444.pll.w": {
    "recognition": "Edges Only",
    "alternates": []
  },
  "444.pll.ba": {
    "recognition": "Adjacent Corner Swap",
    "alternates": []
  },
  "444.pll.bb": {
    "recognition": "Adjacent Corner Swap",
    "alternates": []
  },
  "444.pll.ca": {
    "recognition": "Adjacent Corner Swap",
    "alternates": []
  },
  "444.pll.cb": {
    "recognition": "Adjacent Corner Swap",
    "alternates": []
  },
  "444.pll.da": {
    "recognition": "Adjacent Corner Swap",
    "alternates": []
  },
  "444.pll.db": {
    "recognition": "Adjacent Corner Swap",
    "alternates": []
  },
  "444.pll.pa": {
    "recognition": "Adjacent Corner Swap",
    "alternates": []
  },
  "444.pll.pb": {
    "recognition": "Adjacent Corner Swap",
    "alternates": []
  },
  "444.pll.ka": {
    "recognition": "Adjacent Corner Swap",
    "alternates": []
  },
  "444.pll.kb": {
    "recognition": "Adjacent Corner Swap",
    "alternates": []
  },
  "444.pll.q": {
    "recognition": "Diagonal Corner Swap",
    "alternates": []
  },
  "444.pll.sa": {
    "recognition": "Diagonal Corner Swap",
    "alternates": []
  },
  "444.pll.sb": {
    "recognition": "Diagonal Corner Swap",
    "alternates": []
  },
  "444.pll.x": {
    "recognition": "Diagonal Corner Swap",
    "alternates": []
  },
  "444.pll.m": {
    "recognition": "Adjacent Corner Swap",
    "alternates": []
  },
  "444.pll.adj-c": {
    "recognition": "Adjacent Corner Swap",
    "alternates": []
  },
  "444.pll.diag-c": {
    "recognition": "Diagonal Corner Swap",
    "alternates": []
  }
};

/** One facelet-slot patch on the solved pattern. */
export type StickerDelta = { orbit: string; slot: number; piece: number; orientation: number };

/**
 * Cases whose drawn state is NOT `solved · alg⁻¹` — the 5x5 L2E set — as the
 * displayed hold the diagram is built from, keyed by primary algorithm.
 */
export const L2E_HOLDS: Record<string, StickerDelta[]> = {
  "Rw' U' R' U R' F R F' Rw": [
    {
      "orbit": "EDGES",
      "slot": 8,
      "piece": 16,
      "orientation": 0
    },
    {
      "orbit": "EDGES",
      "slot": 16,
      "piece": 8,
      "orientation": 0
    },
    {
      "orbit": "EDGES2",
      "slot": 11,
      "piece": 11,
      "orientation": 1
    }
  ],
  "Lw U' R' U R' F R F' Lw'": [
    {
      "orbit": "EDGES",
      "slot": 0,
      "piece": 2,
      "orientation": 0
    },
    {
      "orbit": "EDGES",
      "slot": 2,
      "piece": 0,
      "orientation": 0
    },
    {
      "orbit": "EDGES2",
      "slot": 11,
      "piece": 11,
      "orientation": 1
    }
  ],
  "x' M' U' R' U R' F R F' M x": [
    {
      "orbit": "EDGES",
      "slot": 0,
      "piece": 16,
      "orientation": 1
    },
    {
      "orbit": "EDGES",
      "slot": 16,
      "piece": 0,
      "orientation": 1
    },
    {
      "orbit": "EDGES2",
      "slot": 11,
      "piece": 11,
      "orientation": 1
    }
  ],
  "Rw2 F2 U2 Rw2 U2 F2 Rw2": [
    {
      "orbit": "EDGES",
      "slot": 0,
      "piece": 2,
      "orientation": 0
    },
    {
      "orbit": "EDGES",
      "slot": 2,
      "piece": 0,
      "orientation": 0
    },
    {
      "orbit": "EDGES",
      "slot": 8,
      "piece": 16,
      "orientation": 0
    },
    {
      "orbit": "EDGES",
      "slot": 16,
      "piece": 8,
      "orientation": 0
    }
  ],
  "Rw2 B2 Rw' U2 Rw' U2' x' U2 Rw' U2' Rw U2 Rw' U2' Rw2 U2 x": [
    {
      "orbit": "EDGES",
      "slot": 0,
      "piece": 2,
      "orientation": 0
    },
    {
      "orbit": "EDGES",
      "slot": 2,
      "piece": 16,
      "orientation": 1
    },
    {
      "orbit": "EDGES",
      "slot": 8,
      "piece": 0,
      "orientation": 1
    },
    {
      "orbit": "EDGES",
      "slot": 16,
      "piece": 8,
      "orientation": 0
    }
  ],
  "Rw U2 x Rw U2 Rw U2 3Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw'": [
    {
      "orbit": "EDGES",
      "slot": 2,
      "piece": 8,
      "orientation": 1
    },
    {
      "orbit": "EDGES",
      "slot": 8,
      "piece": 2,
      "orientation": 1
    }
  ],
  "y2 Rw U2 Rw U2' x U2 Rw U2' 3Rw' U2 Lw U2' Rw2": [
    {
      "orbit": "EDGES",
      "slot": 2,
      "piece": 16,
      "orientation": 1
    },
    {
      "orbit": "EDGES",
      "slot": 16,
      "piece": 2,
      "orientation": 1
    }
  ],
  "Lw2 F2 U2 Lw' U2 Lw2 F2 Lw' U2 Lw2 U2 F2 Lw' F2": [
    {
      "orbit": "EDGES",
      "slot": 8,
      "piece": 16,
      "orientation": 0
    },
    {
      "orbit": "EDGES",
      "slot": 16,
      "piece": 8,
      "orientation": 0
    }
  ],
  "B2 Rw' U2 Rw' U2' Rw B2 Rw U2 Rw U2' Rw' U2 Rw U2' Rw2": [
    {
      "orbit": "EDGES",
      "slot": 0,
      "piece": 2,
      "orientation": 0
    },
    {
      "orbit": "EDGES",
      "slot": 2,
      "piece": 0,
      "orientation": 0
    }
  ],
  "Rw' U2 Rw2 U2 Rw U2 Rw' U2 Rw U2 Rw2 U2 Rw'": [
    {
      "orbit": "EDGES",
      "slot": 0,
      "piece": 8,
      "orientation": 1
    },
    {
      "orbit": "EDGES",
      "slot": 2,
      "piece": 16,
      "orientation": 1
    },
    {
      "orbit": "EDGES",
      "slot": 8,
      "piece": 2,
      "orientation": 1
    },
    {
      "orbit": "EDGES",
      "slot": 16,
      "piece": 0,
      "orientation": 1
    }
  ],
  "Rw U2 Rw2 U2 Rw' U2 Rw U2 Rw' U2 Rw2 U2 Rw": [
    {
      "orbit": "EDGES",
      "slot": 0,
      "piece": 16,
      "orientation": 1
    },
    {
      "orbit": "EDGES",
      "slot": 2,
      "piece": 8,
      "orientation": 1
    },
    {
      "orbit": "EDGES",
      "slot": 8,
      "piece": 0,
      "orientation": 1
    },
    {
      "orbit": "EDGES",
      "slot": 16,
      "piece": 2,
      "orientation": 1
    }
  ],
  "Rw' U2 Rw U2 3Lw' U2 Rw U2 Rw U2' Rw' U2 Rw U2' Rw2 D2 F2 U2 D2": [
    {
      "orbit": "EDGES",
      "slot": 0,
      "piece": 8,
      "orientation": 1
    },
    {
      "orbit": "EDGES",
      "slot": 8,
      "piece": 0,
      "orientation": 1
    },
    {
      "orbit": "EDGES2",
      "slot": 9,
      "piece": 11,
      "orientation": 0
    },
    {
      "orbit": "EDGES2",
      "slot": 11,
      "piece": 9,
      "orientation": 0
    }
  ],
  "r U R' U' r2 U' R' U r2 U R' U' r'": [
    {
      "orbit": "EDGES",
      "slot": 0,
      "piece": 16,
      "orientation": 1
    },
    {
      "orbit": "EDGES",
      "slot": 2,
      "piece": 8,
      "orientation": 1
    },
    {
      "orbit": "EDGES",
      "slot": 8,
      "piece": 2,
      "orientation": 1
    },
    {
      "orbit": "EDGES",
      "slot": 16,
      "piece": 0,
      "orientation": 1
    },
    {
      "orbit": "EDGES2",
      "slot": 9,
      "piece": 11,
      "orientation": 0
    },
    {
      "orbit": "EDGES2",
      "slot": 11,
      "piece": 9,
      "orientation": 0
    }
  ]
};
