/**
 * GENERATED by scripts/gen-cases.mjs from the verified JPerm extraction —
 * do not edit by hand. Lean runtime dataset: primary algs only — recognition and alternates live in fullsets.rich.gen.ts.
 */
import type { CaseDef } from "./algs";

export const GENERATED_CASES: CaseDef[] = [
  {
    "id": "oll.1",
    "group": "oll-dot",
    "name": "OLL 1",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "2/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "R U2 R' R' F R F' U2 R' F R F'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_01.svg"
  },
  {
    "id": "oll.2",
    "group": "oll-dot",
    "name": "OLL 2",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "r U r' U2 r U2 R' U2 R U' r'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_02.svg"
  },
  {
    "id": "oll.3",
    "group": "oll-dot",
    "name": "OLL 3",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "r' R2 U R' U r U2 r' U M'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_03.svg"
  },
  {
    "id": "oll.4",
    "group": "oll-dot",
    "name": "OLL 4",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "M U' r U2 r' U' R U' R' M'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_04.svg"
  },
  {
    "id": "oll.5",
    "group": "oll-square-shape",
    "name": "OLL 5",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "l' U2 L U L' U l",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_05.svg"
  },
  {
    "id": "oll.6",
    "group": "oll-square-shape",
    "name": "OLL 6",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "r U2 R' U' R U' r'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_06.svg"
  },
  {
    "id": "oll.7",
    "group": "oll-small-lightning-bolt",
    "name": "OLL 7",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "r U R' U R U2 r'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_07.svg"
  },
  {
    "id": "oll.8",
    "group": "oll-small-lightning-bolt",
    "name": "OLL 8",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "l' U' L U' L' U2 l",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_08.svg"
  },
  {
    "id": "oll.9",
    "group": "oll-fish-shape",
    "name": "OLL 9",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "R U R' U' R' F R2 U R' U' F'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_09.svg"
  },
  {
    "id": "oll.10",
    "group": "oll-fish-shape",
    "name": "OLL 10",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "R U R' U R' F R F' R U2 R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_10.svg"
  },
  {
    "id": "oll.11",
    "group": "oll-small-lightning-bolt",
    "name": "OLL 11",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "r U R' U R' F R F' R U2 r'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_11.svg"
  },
  {
    "id": "oll.12",
    "group": "oll-small-lightning-bolt",
    "name": "OLL 12",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "M' R' U' R U' R' U2 R U' R r'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_12.svg"
  },
  {
    "id": "oll.13",
    "group": "oll-knight-move-shape",
    "name": "OLL 13",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "F U R U' R2 F' R U R U' R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_13.svg"
  },
  {
    "id": "oll.14",
    "group": "oll-knight-move-shape",
    "name": "OLL 14",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "R' F R U R' F' R F U' F'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_14.svg"
  },
  {
    "id": "oll.15",
    "group": "oll-knight-move-shape",
    "name": "OLL 15",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "l' U' l L' U' L U l' U l",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_15.svg"
  },
  {
    "id": "oll.16",
    "group": "oll-knight-move-shape",
    "name": "OLL 16",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "r U r' R U R' U' r U' r'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_16.svg"
  },
  {
    "id": "oll.17",
    "group": "oll-dot",
    "name": "OLL 17",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "F R' F' R2 r' U R U' R' U' M'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_17.svg"
  },
  {
    "id": "oll.18",
    "group": "oll-dot",
    "name": "OLL 18",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "r U R' U R U2 r' r' U' R U' R' U2 r",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_18.svg"
  },
  {
    "id": "oll.19",
    "group": "oll-dot",
    "name": "OLL 19",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "r' R U R U R' U' M' R' F R F'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_19.svg"
  },
  {
    "id": "oll.20",
    "group": "oll-dot",
    "name": "OLL 20",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "1/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "r U R' U' M2 U R U' R' U' M'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_20.svg"
  },
  {
    "id": "oll.21",
    "group": "oll-cross",
    "name": "OLL 21",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "2/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "R U2 R' U' R U R' U' R U' R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_21.svg"
  },
  {
    "id": "oll.22",
    "group": "oll-cross",
    "name": "OLL 22",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "R U2 (R2 U' R2 U' R2) U2 R",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_22.svg"
  },
  {
    "id": "oll.23",
    "group": "oll-cross",
    "name": "OLL 23",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "R2 D' R U2 R' D R U2 R",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_23.svg"
  },
  {
    "id": "oll.24",
    "group": "oll-cross",
    "name": "OLL 24",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "r U R' U' r' F R F'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_24.svg"
  },
  {
    "id": "oll.25",
    "group": "oll-cross",
    "name": "OLL 25",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "F' r U R' U' r' F R",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_25.svg"
  },
  {
    "id": "oll.26",
    "group": "oll-cross",
    "name": "OLL 26",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "(R U2 R') U' R U' R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_26.svg"
  },
  {
    "id": "oll.27",
    "group": "oll-cross",
    "name": "OLL 27",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "R U R' U R U2 R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_27.svg"
  },
  {
    "id": "oll.28",
    "group": "oll-corners-oriented",
    "name": "OLL 28",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "r U R' U' r' R U R U' R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_28.svg"
  },
  {
    "id": "oll.29",
    "group": "oll-awkward-shape",
    "name": "OLL 29",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "R U R' U' R U' R' F' U' F R U R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_29.svg"
  },
  {
    "id": "oll.30",
    "group": "oll-awkward-shape",
    "name": "OLL 30",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "F R' F R2 U' R' U' R U R' F2",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_30.svg"
  },
  {
    "id": "oll.31",
    "group": "oll-p-shape",
    "name": "OLL 31",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "R' U' F U R U' R' F' R",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_31.svg"
  },
  {
    "id": "oll.32",
    "group": "oll-p-shape",
    "name": "OLL 32",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "L U F' U' L' U L F L'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_32.svg"
  },
  {
    "id": "oll.33",
    "group": "oll-t-shape",
    "name": "OLL 33",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "R U R' U' R' F R F'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_33.svg"
  },
  {
    "id": "oll.34",
    "group": "oll-c-shape",
    "name": "OLL 34",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "R U R2 U' R' F R U R U' F'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_34.svg"
  },
  {
    "id": "oll.35",
    "group": "oll-fish-shape",
    "name": "OLL 35",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "R U2 R' R' F R F' R U2 R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_35.svg"
  },
  {
    "id": "oll.36",
    "group": "oll-w-shape",
    "name": "OLL 36",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "L' U' L U' L' U L U L F' L' F",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_36.svg"
  },
  {
    "id": "oll.37",
    "group": "oll-fish-shape",
    "name": "OLL 37",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "F R' F' R U R U' R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_37.svg"
  },
  {
    "id": "oll.38",
    "group": "oll-w-shape",
    "name": "OLL 38",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "R U R' U R U' R' U' R' F R F'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_38.svg"
  },
  {
    "id": "oll.39",
    "group": "oll-big-lightning-bolt",
    "name": "OLL 39",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "L F' L' U' L U F U' L'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_39.svg"
  },
  {
    "id": "oll.40",
    "group": "oll-big-lightning-bolt",
    "name": "OLL 40",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "R' F R U R' U' F' U R",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_40.svg"
  },
  {
    "id": "oll.41",
    "group": "oll-awkward-shape",
    "name": "OLL 41",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "R U R' U R U2 R' F R U R' U' F'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_41.svg"
  },
  {
    "id": "oll.42",
    "group": "oll-awkward-shape",
    "name": "OLL 42",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "R' U' R U' R' U2 R F R U R' U' F'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_42.svg"
  },
  {
    "id": "oll.43",
    "group": "oll-p-shape",
    "name": "OLL 43",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "F' U' L' U L F",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_43.svg"
  },
  {
    "id": "oll.44",
    "group": "oll-p-shape",
    "name": "OLL 44",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "F U R U' R' F'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_44.svg"
  },
  {
    "id": "oll.45",
    "group": "oll-t-shape",
    "name": "OLL 45",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "F R U R' U' F'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_45.svg"
  },
  {
    "id": "oll.46",
    "group": "oll-c-shape",
    "name": "OLL 46",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "R' U' R' F R F' U R",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_46.svg"
  },
  {
    "id": "oll.47",
    "group": "oll-small-l-shape",
    "name": "OLL 47",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "R' U' R' F R F' R' F R F' U R",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_47.svg"
  },
  {
    "id": "oll.48",
    "group": "oll-small-l-shape",
    "name": "OLL 48",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "F R U R' U' R U R' U' F'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_48.svg"
  },
  {
    "id": "oll.49",
    "group": "oll-small-l-shape",
    "name": "OLL 49",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "r U' r2 U r2 U r2 U' r",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_49.svg"
  },
  {
    "id": "oll.50",
    "group": "oll-small-l-shape",
    "name": "OLL 50",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "r' U r2 U' r2 U' r2 U r'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_50.svg"
  },
  {
    "id": "oll.51",
    "group": "oll-i-shape",
    "name": "OLL 51",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "F U R U' R' U R U' R' F'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_51.svg"
  },
  {
    "id": "oll.52",
    "group": "oll-i-shape",
    "name": "OLL 52",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "R U R' U R U' B U' B' R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_52.svg"
  },
  {
    "id": "oll.53",
    "group": "oll-small-l-shape",
    "name": "OLL 53",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "l' U2 L U L' U' L U L' U l",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_53.svg"
  },
  {
    "id": "oll.54",
    "group": "oll-small-l-shape",
    "name": "OLL 54",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "4/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "(r U2 R' U') R U R' U' R U' r'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_54.svg"
  },
  {
    "id": "oll.55",
    "group": "oll-i-shape",
    "name": "OLL 55",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "2/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "R' F R U R U' R2 F' R2 U' R' U R U R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_55.svg"
  },
  {
    "id": "oll.56",
    "group": "oll-i-shape",
    "name": "OLL 56",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "2/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "(r' U' r) U' R' U R U' R' U R r' U r",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_56.svg"
  },
  {
    "id": "oll.57",
    "group": "oll-corners-oriented",
    "name": "OLL 57",
    "stickering": "OLL",
    "puzzle": "3x3x3",
    "probability": "2/216",
    "phase": "full-oll",
    "algs": [
      {
        "moves": "R U R' U' M' U R U' r'",
        "primary": true
      }
    ],
    "icon": "/diagrams/oll-full/oll_57.svg"
  },
  {
    "id": "pll.h",
    "group": "pll-edges-only",
    "name": "H-Perm",
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "1/18",
    "phase": "full-pll",
    "algs": [
      {
        "moves": "M2 U M2 U2 M2 U M2",
        "primary": true
      }
    ],
    "icon": "/diagrams/pll-full/pll_full_h.svg"
  },
  {
    "id": "pll.z",
    "group": "pll-edges-only",
    "name": "Z-Perm",
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "2/18",
    "phase": "full-pll",
    "algs": [
      {
        "moves": "M' U M2 U M2 U M' U2 M2",
        "primary": true
      }
    ],
    "icon": "/diagrams/pll-full/pll_full_z.svg"
  },
  {
    "id": "pll.ua",
    "group": "pll-edges-only",
    "name": "Ua-Perm",
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll",
    "algs": [
      {
        "moves": "M2 U M U2 M' U M2",
        "primary": true
      }
    ],
    "icon": "/diagrams/pll-full/pll_full_ua.svg"
  },
  {
    "id": "pll.ub",
    "group": "pll-edges-only",
    "name": "Ub-Perm",
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll",
    "algs": [
      {
        "moves": "M2 U' M U2 M' U' M2",
        "primary": true
      }
    ],
    "icon": "/diagrams/pll-full/pll_full_ub.svg"
  },
  {
    "id": "pll.aa",
    "group": "pll-adjacent-corner-swap",
    "name": "Aa-Perm",
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll",
    "algs": [
      {
        "moves": "x L2 D2 L' U' L D2 L' U L'",
        "primary": true
      }
    ],
    "icon": "/diagrams/pll-full/pll_full_aa.svg"
  },
  {
    "id": "pll.ab",
    "group": "pll-adjacent-corner-swap",
    "name": "Ab-Perm",
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll",
    "algs": [
      {
        "moves": "x' L2 D2 L U L' D2 L U' L",
        "primary": true
      }
    ],
    "icon": "/diagrams/pll-full/pll_full_ab.svg"
  },
  {
    "id": "pll.e",
    "group": "pll-diagonal-corner-swap",
    "name": "E-Perm",
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "2/18",
    "phase": "full-pll",
    "algs": [
      {
        "moves": "x' L' U L D' L' U' L D L' U' L D' L' U L D",
        "primary": true
      }
    ],
    "icon": "/diagrams/pll-full/pll_full_e.svg"
  },
  {
    "id": "pll.f",
    "group": "pll-adjacent-corner-swap",
    "name": "F-Perm",
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll",
    "algs": [
      {
        "moves": "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R",
        "primary": true
      }
    ],
    "icon": "/diagrams/pll-full/pll_full_f.svg"
  },
  {
    "id": "pll.ja",
    "group": "pll-adjacent-corner-swap",
    "name": "Ja-Perm",
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll",
    "algs": [
      {
        "moves": "x R2 F R F' R U2 r' U r U2",
        "primary": true
      }
    ],
    "icon": "/diagrams/pll-full/pll_full_ja.svg"
  },
  {
    "id": "pll.jb",
    "group": "pll-adjacent-corner-swap",
    "name": "Jb-Perm",
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll",
    "algs": [
      {
        "moves": "R U R' F' R U R' U' R' F R2 U' R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/pll-full/pll_full_jb.svg"
  },
  {
    "id": "pll.ra",
    "group": "pll-adjacent-corner-swap",
    "name": "Ra-Perm",
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll",
    "algs": [
      {
        "moves": "R U' R' U' R U R D R' U' R D' R' U2 R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/pll-full/pll_full_ra.svg"
  },
  {
    "id": "pll.rb",
    "group": "pll-adjacent-corner-swap",
    "name": "Rb-Perm",
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll",
    "algs": [
      {
        "moves": "R2 F R U R U' R' F' R U2 R' U2 R",
        "primary": true
      }
    ],
    "icon": "/diagrams/pll-full/pll_full_rb.svg"
  },
  {
    "id": "pll.t",
    "group": "pll-adjacent-corner-swap",
    "name": "T-Perm",
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll",
    "algs": [
      {
        "moves": "R U R' U' R' F R2 U' R' U' (R U R') F'",
        "primary": true
      }
    ],
    "icon": "/diagrams/pll-full/pll_full_t.svg"
  },
  {
    "id": "pll.y",
    "group": "pll-diagonal-corner-swap",
    "name": "Y-Perm",
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll",
    "algs": [
      {
        "moves": "F R U' R' U' R U R' F' R U R' U' R' F R F'",
        "primary": true
      }
    ],
    "icon": "/diagrams/pll-full/pll_full_y.svg"
  },
  {
    "id": "pll.v",
    "group": "pll-diagonal-corner-swap",
    "name": "V-Perm",
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll",
    "algs": [
      {
        "moves": "R' U R' U' y R' F' R2 U' R' U R' F R F",
        "primary": true
      }
    ],
    "icon": "/diagrams/pll-full/pll_full_v.svg"
  },
  {
    "id": "pll.na",
    "group": "pll-diagonal-corner-swap",
    "name": "Na-Perm",
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "1/18",
    "phase": "full-pll",
    "algs": [
      {
        "moves": "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/pll-full/pll_full_na.svg"
  },
  {
    "id": "pll.nb",
    "group": "pll-diagonal-corner-swap",
    "name": "Nb-Perm",
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "1/18",
    "phase": "full-pll",
    "algs": [
      {
        "moves": "R' (U R U' R') F' U' F R U R' F R' F' R U' R",
        "primary": true
      }
    ],
    "icon": "/diagrams/pll-full/pll_full_nb.svg"
  },
  {
    "id": "pll.ga",
    "group": "pll-adjacent-corner-swap",
    "name": "Ga-Perm",
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll",
    "algs": [
      {
        "moves": "R2 U R' U R' U' R U' R2 (U' D) R' U R D'",
        "primary": true
      }
    ],
    "icon": "/diagrams/pll-full/pll_full_ga.svg"
  },
  {
    "id": "pll.gb",
    "group": "pll-adjacent-corner-swap",
    "name": "Gb-Perm",
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll",
    "algs": [
      {
        "moves": "R' U' R (U D') R2 U R' U R U' R U' R2 D",
        "primary": true
      }
    ],
    "icon": "/diagrams/pll-full/pll_full_gb.svg"
  },
  {
    "id": "pll.gc",
    "group": "pll-adjacent-corner-swap",
    "name": "Gc-Perm",
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll",
    "algs": [
      {
        "moves": "R2 U' R U' R U R' U R2 (U D') R U' R' D",
        "primary": true
      }
    ],
    "icon": "/diagrams/pll-full/pll_full_gc.svg"
  },
  {
    "id": "pll.gd",
    "group": "pll-adjacent-corner-swap",
    "name": "Gd-Perm",
    "stickering": "PLL",
    "puzzle": "3x3x3",
    "probability": "4/18",
    "phase": "full-pll",
    "algs": [
      {
        "moves": "R U R' (U' D) R2 U' R U' R' U R' U R2 D'",
        "primary": true
      }
    ],
    "icon": "/diagrams/pll-full/pll_full_gd.svg"
  },
  {
    "id": "f2l.1",
    "group": "f2l-free-pairs",
    "name": "F2L 1",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "U (R U' R')",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_01.svg"
  },
  {
    "id": "f2l.2",
    "group": "f2l-free-pairs",
    "name": "F2L 2",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "y U' (L' U L)",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_02.svg"
  },
  {
    "id": "f2l.3",
    "group": "f2l-free-pairs",
    "name": "F2L 3",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "y (L' U' L)",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_03.svg"
  },
  {
    "id": "f2l.4",
    "group": "f2l-free-pairs",
    "name": "F2L 4",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "(R U R')",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_04.svg"
  },
  {
    "id": "f2l.5",
    "group": "f2l-disconnected-pairs",
    "name": "F2L 5",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "U' (R U R') U2 (R U' R')",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_05.svg"
  },
  {
    "id": "f2l.6",
    "group": "f2l-disconnected-pairs",
    "name": "F2L 6",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "y U (L' U' L) U2 (L' U L)",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_06.svg"
  },
  {
    "id": "f2l.7",
    "group": "f2l-disconnected-pairs",
    "name": "F2L 7",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "U' (R U2 R') U2 (R U' R')",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_07.svg"
  },
  {
    "id": "f2l.8",
    "group": "f2l-disconnected-pairs",
    "name": "F2L 8",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "y U (L' U2 L) U2 (L' U L)",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_08.svg"
  },
  {
    "id": "f2l.9",
    "group": "f2l-disconnected-pairs",
    "name": "F2L 9",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "y U (L' U' L) U' (L' U' L)",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_09.svg"
  },
  {
    "id": "f2l.10",
    "group": "f2l-disconnected-pairs",
    "name": "F2L 10",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "U' (R U R') U (R U R')",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_10.svg"
  },
  {
    "id": "f2l.11",
    "group": "f2l-connected-pairs",
    "name": "F2L 11",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "y L U2 L2' U' L2 U' L'",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_11.svg"
  },
  {
    "id": "f2l.12",
    "group": "f2l-connected-pairs",
    "name": "F2L 12",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "R' U2 R2 U R2' U R",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_12.svg"
  },
  {
    "id": "f2l.13",
    "group": "f2l-connected-pairs",
    "name": "F2L 13",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "y U (L' U L) U' (L' U' L)",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_13.svg"
  },
  {
    "id": "f2l.14",
    "group": "f2l-connected-pairs",
    "name": "F2L 14",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "U' (R U' R') U (R U R')",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_14.svg"
  },
  {
    "id": "f2l.15",
    "group": "f2l-connected-pairs",
    "name": "F2L 15",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "M U (L F' L') U' M'",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_15.svg"
  },
  {
    "id": "f2l.16",
    "group": "f2l-connected-pairs",
    "name": "F2L 16",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "y M U' (R' F R) U M'",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_16.svg"
  },
  {
    "id": "f2l.17",
    "group": "f2l-connected-pairs",
    "name": "F2L 17",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "(R U2 R') U' (R U R')",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_17.svg"
  },
  {
    "id": "f2l.18",
    "group": "f2l-connected-pairs",
    "name": "F2L 18",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "y (L' U2 L) U (L' U' L)",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_18.svg"
  },
  {
    "id": "f2l.19",
    "group": "f2l-disconnected-pairs",
    "name": "F2L 19",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "U (R U2 R') U (R U' R')",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_19.svg"
  },
  {
    "id": "f2l.20",
    "group": "f2l-disconnected-pairs",
    "name": "F2L 20",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "y U' (L' U2 L) U' (L' U L)",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_20.svg"
  },
  {
    "id": "f2l.21",
    "group": "f2l-disconnected-pairs",
    "name": "F2L 21",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "U2 (R U R') U (R U' R')",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_21.svg"
  },
  {
    "id": "f2l.22",
    "group": "f2l-disconnected-pairs",
    "name": "F2L 22",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "y U2 (L' U' L) U' (L' U L)",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_22.svg"
  },
  {
    "id": "f2l.23",
    "group": "f2l-connected-pairs",
    "name": "F2L 23",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "U (R U' R') U' (R U' R' U R U' R')",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_23.svg"
  },
  {
    "id": "f2l.24",
    "group": "f2l-connected-pairs",
    "name": "F2L 24",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "y U' (L' U L) U (L' U L U' L' U L)",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_24.svg"
  },
  {
    "id": "f2l.25",
    "group": "f2l-corner-in-slot",
    "name": "F2L 25",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "U' (R' F R F') (R U R')",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_25.svg"
  },
  {
    "id": "f2l.26",
    "group": "f2l-corner-in-slot",
    "name": "F2L 26",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "y U (L F' L' F) (L' U' L)",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_26.svg"
  },
  {
    "id": "f2l.27",
    "group": "f2l-corner-in-slot",
    "name": "F2L 27",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "(R U' R') U (R U' R')",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_27.svg"
  },
  {
    "id": "f2l.28",
    "group": "f2l-corner-in-slot",
    "name": "F2L 28",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "y (L' U L) U' (L' U L)",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_28.svg"
  },
  {
    "id": "f2l.29",
    "group": "f2l-corner-in-slot",
    "name": "F2L 29",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "y (L' U' L) U (L' U' L)",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_29.svg"
  },
  {
    "id": "f2l.30",
    "group": "f2l-corner-in-slot",
    "name": "F2L 30",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "(R U R') U' (R U R')",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_30.svg"
  },
  {
    "id": "f2l.31",
    "group": "f2l-edge-in-slot",
    "name": "F2L 31",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "U' (R' F R F') (R U' R')",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_31.svg"
  },
  {
    "id": "f2l.32",
    "group": "f2l-edge-in-slot",
    "name": "F2L 32",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "(U R U' R')3",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_32.svg"
  },
  {
    "id": "f2l.33",
    "group": "f2l-edge-in-slot",
    "name": "F2L 33",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "y U' (L' U' L) U2 (L' U' L)",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_33.svg"
  },
  {
    "id": "f2l.34",
    "group": "f2l-edge-in-slot",
    "name": "F2L 34",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "U (R U R') U2 (R U R')",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_34.svg"
  },
  {
    "id": "f2l.35",
    "group": "f2l-edge-in-slot",
    "name": "F2L 35",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "y U' (F U F') U (L' U' L)",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_35.svg"
  },
  {
    "id": "f2l.36",
    "group": "f2l-edge-in-slot",
    "name": "F2L 36",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "U (F' U' F) U' (R U R')",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_36.svg"
  },
  {
    "id": "f2l.37",
    "group": "f2l-pieces-in-slot",
    "name": "F2L 37",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "R2' U2' F R2 F' U2' R' U R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_37.svg"
  },
  {
    "id": "f2l.38",
    "group": "f2l-pieces-in-slot",
    "name": "F2L 38",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "(R U' R') U' (R U R' U2 R U' R')",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_38.svg"
  },
  {
    "id": "f2l.39",
    "group": "f2l-pieces-in-slot",
    "name": "F2L 39",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "(R U' R') U (R U2 R' U R U' R')",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_39.svg"
  },
  {
    "id": "f2l.40",
    "group": "f2l-pieces-in-slot",
    "name": "F2L 40",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "y (L' U L) (F R U2' R' F')",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_40.svg"
  },
  {
    "id": "f2l.41",
    "group": "f2l-pieces-in-slot",
    "name": "F2L 41",
    "stickering": "F2L",
    "puzzle": "3x3x3",
    "phase": "full-f2l",
    "algs": [
      {
        "moves": "(R U' R') (F' L' U2 L F)",
        "primary": true
      }
    ],
    "icon": "/diagrams/f2l/f2l_41.svg"
  },
  {
    "id": "555.l2e-1",
    "group": "555-l2e",
    "name": "L2E 1",
    "stickering": "full",
    "puzzle": "5x5x5",
    "phase": "555",
    "algs": [
      {
        "moves": "Rw' U' R' U R' F R F' Rw",
        "primary": true
      }
    ]
  },
  {
    "id": "555.l2e-2",
    "group": "555-l2e",
    "name": "L2E 2",
    "stickering": "full",
    "puzzle": "5x5x5",
    "phase": "555",
    "algs": [
      {
        "moves": "Lw U' R' U R' F R F' Lw'",
        "primary": true
      }
    ]
  },
  {
    "id": "555.l2e-3",
    "group": "555-l2e",
    "name": "L2E 3",
    "stickering": "full",
    "puzzle": "5x5x5",
    "phase": "555",
    "algs": [
      {
        "moves": "x' M' U' R' U R' F R F' M x",
        "primary": true
      }
    ]
  },
  {
    "id": "555.l2e-4",
    "group": "555-l2e",
    "name": "L2E 4",
    "stickering": "full",
    "puzzle": "5x5x5",
    "phase": "555",
    "algs": [
      {
        "moves": "Rw2 F2 U2 Rw2 U2 F2 Rw2",
        "primary": true
      }
    ]
  },
  {
    "id": "555.l2e-5",
    "group": "555-l2e",
    "name": "L2E 5",
    "stickering": "full",
    "puzzle": "5x5x5",
    "phase": "555",
    "algs": [
      {
        "moves": "Rw2 B2 Rw' U2 Rw' U2' x' U2 Rw' U2' Rw U2 Rw' U2' Rw2 U2 x",
        "primary": true
      }
    ]
  },
  {
    "id": "555.l2e-6",
    "group": "555-l2e",
    "name": "L2E 6",
    "stickering": "full",
    "puzzle": "5x5x5",
    "phase": "555",
    "algs": [
      {
        "moves": "Rw' U2 3Rw U2 3Rw' F2 Rw2 U2 Rw U2 Rw' U2 F2 Rw2 F2",
        "primary": true
      }
    ]
  },
  {
    "id": "555.l2e-7",
    "group": "555-l2e",
    "name": "L2E 7",
    "stickering": "full",
    "puzzle": "5x5x5",
    "phase": "555",
    "algs": [
      {
        "moves": "y2 Rw U2 Rw U2' x U2 Rw U2' 3Rw' U2 Lw U2' Rw2",
        "primary": true
      }
    ]
  },
  {
    "id": "555.l2e-8",
    "group": "555-l2e",
    "name": "L2E 8",
    "stickering": "full",
    "puzzle": "5x5x5",
    "phase": "555",
    "algs": [
      {
        "moves": "Lw2 F2 U2 Lw' U2 Lw2 F2 Lw' U2 Lw2 U2 F2 Lw' F2",
        "primary": true
      }
    ]
  },
  {
    "id": "555.l2e-9",
    "group": "555-l2e",
    "name": "L2E 9",
    "stickering": "full",
    "puzzle": "5x5x5",
    "phase": "555",
    "algs": [
      {
        "moves": "B2 Rw' U2 Rw' U2' Rw B2 Rw U2 Rw U2' Rw' U2 Rw U2' Rw2",
        "primary": true
      }
    ]
  },
  {
    "id": "555.l2e-10",
    "group": "555-l2e",
    "name": "L2E 10",
    "stickering": "full",
    "puzzle": "5x5x5",
    "phase": "555",
    "algs": [
      {
        "moves": "Rw' U2 Rw2 U2 Rw U2 Rw' U2 Rw U2 Rw2 U2 Rw'",
        "primary": true
      }
    ]
  },
  {
    "id": "555.l2e-11",
    "group": "555-l2e",
    "name": "L2E 11",
    "stickering": "full",
    "puzzle": "5x5x5",
    "phase": "555",
    "algs": [
      {
        "moves": "Rw U2 Rw2 U2 Rw' U2 Rw U2 Rw' U2 Rw2 U2 Rw",
        "primary": true
      }
    ]
  },
  {
    "id": "555.l2e-12",
    "group": "555-l2e",
    "name": "L2E 12",
    "stickering": "full",
    "puzzle": "5x5x5",
    "phase": "555",
    "algs": [
      {
        "moves": "Rw' U2 Rw U2 3Lw' U2 Rw U2 Rw U2' Rw' U2 Rw U2' Rw2 D2 F2 U2 D2",
        "primary": true
      }
    ]
  },
  {
    "id": "555.l2e-13",
    "group": "555-l2e",
    "name": "L2E 13",
    "stickering": "full",
    "puzzle": "5x5x5",
    "phase": "555",
    "algs": [
      {
        "moves": "r U R' U' r2 U' R' U r2 U R' U' r'",
        "primary": true
      }
    ]
  },
  {
    "id": "444.oll.solved",
    "group": "4x4oll-4-corners",
    "name": "Solved (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "R U2 R' U' Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' F R' F' R",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_solved.svg"
  },
  {
    "id": "444.oll.u-f",
    "group": "4x4oll-2-corners",
    "name": "U (F) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw'",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_u_f.svg"
  },
  {
    "id": "444.oll.u-r",
    "group": "4x4oll-2-corners",
    "name": "U (R) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U' R U R' U R U2 R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_u_r.svg"
  },
  {
    "id": "444.oll.u-l",
    "group": "4x4oll-2-corners",
    "name": "U (L) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R U2 R' U' R U' R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_u_l.svg"
  },
  {
    "id": "444.oll.u-b",
    "group": "4x4oll-2-corners",
    "name": "U (B) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "m Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' m'",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_u_b.svg"
  },
  {
    "id": "444.oll.t-f",
    "group": "4x4oll-2-corners",
    "name": "T (F) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "R U R' U' R Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R' U R U' R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_t_f.svg"
  },
  {
    "id": "444.oll.t-r",
    "group": "4x4oll-2-corners",
    "name": "T (R) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R U R' U' R' F R F'",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_t_r.svg"
  },
  {
    "id": "444.oll.t-l",
    "group": "4x4oll-2-corners",
    "name": "T (L) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "F R U' R' U' R U R' F' Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw'",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_t_l.svg"
  },
  {
    "id": "444.oll.t-b",
    "group": "4x4oll-2-corners",
    "name": "T (B) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U R U2 (R2 U' R2 U' R2) U2 R",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_t_b.svg"
  },
  {
    "id": "444.oll.l-fr",
    "group": "4x4oll-2-corners",
    "name": "L (FR) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "R' U' R Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R' U R",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_l_fr.svg"
  },
  {
    "id": "444.oll.l-fl",
    "group": "4x4oll-2-corners",
    "name": "L (FL) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "L U L' Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' L U' L'",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_l_fl.svg"
  },
  {
    "id": "444.oll.l-br",
    "group": "4x4oll-2-corners",
    "name": "L (BR) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U R' U2 R U R' U R",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_l_br.svg"
  },
  {
    "id": "444.oll.l-bl",
    "group": "4x4oll-2-corners",
    "name": "L (BL) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R' U' R U' R' U2 R",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_l_bl.svg"
  },
  {
    "id": "444.oll.sune-fr",
    "group": "4x4oll-1-corner",
    "name": "Sune (FR) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "m' U R U' 3Rw' Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U R U2 R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_sune_fr.svg"
  },
  {
    "id": "444.oll.sune-fl",
    "group": "4x4oll-1-corner",
    "name": "Sune (FL) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R U R' U R U2 R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_sune_fl.svg"
  },
  {
    "id": "444.oll.sune-br",
    "group": "4x4oll-1-corner",
    "name": "Sune (BR) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "L F' L' F Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' L' U L",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_sune_br.svg"
  },
  {
    "id": "444.oll.sune-bl",
    "group": "4x4oll-1-corner",
    "name": "Sune (BL) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "F' L' U' L U F Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw'",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_sune_bl.svg"
  },
  {
    "id": "444.oll.antisune-fr",
    "group": "4x4oll-1-corner",
    "name": "Antisune (FR) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U' R U2 R' U' R U' R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_antisune_fr.svg"
  },
  {
    "id": "444.oll.antisune-fl",
    "group": "4x4oll-1-corner",
    "name": "Antisune (FL) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R U2 (R2 U' R2 U' R2) U2 R",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_antisune_fl.svg"
  },
  {
    "id": "444.oll.antisune-br",
    "group": "4x4oll-1-corner",
    "name": "Antisune (BR) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "F R U R' U' F' Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw'",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_antisune_br.svg"
  },
  {
    "id": "444.oll.antisune-bl",
    "group": "4x4oll-1-corner",
    "name": "Antisune (BL) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "R' F R F' Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R U' R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_antisune_bl.svg"
  },
  {
    "id": "444.oll.h-fb",
    "group": "4x4oll-0-corners",
    "name": "H (FB) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R2 D' R U2 R' D R U2 R",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_h_fb.svg"
  },
  {
    "id": "444.oll.h-lr",
    "group": "4x4oll-0-corners",
    "name": "H (LR) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R U R' U R U' R' U R U2 R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_h_lr.svg"
  },
  {
    "id": "444.oll.pi-f",
    "group": "4x4oll-0-corners",
    "name": "Pi (F) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U' R U2 (R2 U' R2 U' R2) U2 R",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_pi_f.svg"
  },
  {
    "id": "444.oll.pi-r",
    "group": "4x4oll-0-corners",
    "name": "Pi (R) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U R' U' R U' R' U2 R",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_pi_r.svg"
  },
  {
    "id": "444.oll.pi-l",
    "group": "4x4oll-0-corners",
    "name": "Pi (L) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' R' U2 R U R' U R",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_pi_l.svg"
  },
  {
    "id": "444.oll.pi-b",
    "group": "4x4oll-0-corners",
    "name": "Pi (B) (4×4 OLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' U' 3Rw U R' U' 3Rw' F R F'",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-oll/444_oll_pi_b.svg"
  },
  {
    "id": "444.pll.pure-e",
    "group": "4x4pll-edges-only",
    "name": "Pure-E (4×4 PLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-pll/444_pll_pure_e.svg"
  },
  {
    "id": "444.pll.adj-e",
    "group": "4x4pll-edges-only",
    "name": "Adj-E (4×4 PLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "R U R' U' 2R2 U2 2R2 Uw2 2R2 Uw2 U' R U' R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-pll/444_pll_adj_e.svg"
  },
  {
    "id": "444.pll.o-plus",
    "group": "4x4pll-edges-only",
    "name": "O+ (4×4 PLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "m' U' m2 U' m2 U' m' U2 m2 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-pll/444_pll_o_plus.svg"
  },
  {
    "id": "444.pll.o-minus",
    "group": "4x4pll-edges-only",
    "name": "O- (4×4 PLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "m' U' m2 U' m2 U' m' U2 m2 U' 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-pll/444_pll_o_minus.svg"
  },
  {
    "id": "444.pll.w",
    "group": "4x4pll-edges-only",
    "name": "W (4×4 PLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "R U' R U R U R U' R' U' R2 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-pll/444_pll_w.svg"
  },
  {
    "id": "444.pll.ba",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "Ba (4×4 PLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "2R2 U2 2R2 Uw2 2R2 Uw2 U R U R' F' R U R' U' R' F R2 U' R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-pll/444_pll_ba.svg"
  },
  {
    "id": "444.pll.bb",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "Bb (4×4 PLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "R U R' U' R' F R2 U' R' 2R2 U2 2R2 Uw2 2R2 Uw2 U R U R' F'",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-pll/444_pll_bb.svg"
  },
  {
    "id": "444.pll.ca",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "Ca (4×4 PLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "2R2 U2 2R2 Uw2 2R2 Uw2 U R' U2 R U2 R' F R U R' U' R' F' R2",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-pll/444_pll_ca.svg"
  },
  {
    "id": "444.pll.cb",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "Cb (4×4 PLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "2R2 U2 2R2 Uw2 2R2 Uw2 R U R' F' R U2 R' U2 R' F R U R U2 R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-pll/444_pll_cb.svg"
  },
  {
    "id": "444.pll.da",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "Da (4×4 PLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "R' U L' U2 R U' R' U2 R L U' 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-pll/444_pll_da.svg"
  },
  {
    "id": "444.pll.db",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "Db (4×4 PLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "R U R' F' R U R' U' R' F R2 U' R' 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-pll/444_pll_db.svg"
  },
  {
    "id": "444.pll.pa",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "Pa (4×4 PLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "R U R' F' R U R' U' R' F R2 U' R' U' 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-pll/444_pll_pa.svg"
  },
  {
    "id": "444.pll.pb",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "Pb (4×4 PLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "2R2 U2 2R2 Uw2 2R2 Uw2 R U R' F' R U R' U' R' F R2 U' R'",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-pll/444_pll_pb.svg"
  },
  {
    "id": "444.pll.ka",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "Ka (4×4 PLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "2R2 U2 2R2 Uw2 2R2 Uw2 x R2 D2 R U R' D2 R U' R",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-pll/444_pll_ka.svg"
  },
  {
    "id": "444.pll.kb",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "Kb (4×4 PLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "2R2 U2 2R2 Uw2 2R2 Uw2 U x R' U R' D2 R U' R' D2 R2",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-pll/444_pll_kb.svg"
  },
  {
    "id": "444.pll.q",
    "group": "4x4pll-diagonal-corner-swap",
    "name": "Q (4×4 PLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "x' R U' R' D R U R' D' R U R' D R U' R' D' x U 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-pll/444_pll_q.svg"
  },
  {
    "id": "444.pll.sa",
    "group": "4x4pll-diagonal-corner-swap",
    "name": "Sa (4×4 PLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "F R U' R' U' R U R' F' R U R' U' R' F R F' U' 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-pll/444_pll_sa.svg"
  },
  {
    "id": "444.pll.sb",
    "group": "4x4pll-diagonal-corner-swap",
    "name": "Sb (4×4 PLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "F R U' R' U' R U R' F' R U R' U' R' F R F' 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-pll/444_pll_sb.svg"
  },
  {
    "id": "444.pll.x",
    "group": "4x4pll-diagonal-corner-swap",
    "name": "X (4×4 PLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "x' R U' R' D R U R' D' R U R' D R U' R' D' x 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-pll/444_pll_x.svg"
  },
  {
    "id": "444.pll.m",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "M (4×4 PLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "R U R' U' R' F R2 U' R' U' R U R' F' 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-pll/444_pll_m.svg"
  },
  {
    "id": "444.pll.adj-c",
    "group": "4x4pll-adjacent-corner-swap",
    "name": "Adj-C (4×4 PLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "R U R' U' R' F R2 U' R' U' R U R' F' U' 2R2 U2 2R2 Uw2 2R2 Uw2",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-pll/444_pll_adj_c.svg"
  },
  {
    "id": "444.pll.diag-c",
    "group": "4x4pll-diagonal-corner-swap",
    "name": "Diag-C (4×4 PLL)",
    "stickering": "full",
    "puzzle": "4x4x4",
    "phase": "444",
    "algs": [
      {
        "moves": "F R U' R' U' R U R' F' U' 2R2 U2 2R2 Uw2 2R2 Uw2 U' R U R' U' R' F R F'",
        "primary": true
      }
    ],
    "icon": "/diagrams/444-pll/444_pll_diag_c.svg"
  }
];

/** Verified per-case trainer scrambles (each produces its case). */
export const CASE_SCRAMBLES: Record<string, string[]> = {
  "oll.1": [
    "F' U2 B L' U2 B L F' D2 R2 U B2 U F2 R2 B2 D B2 D L2",
    "L' B L B U2 L' B L U' R2 U R2 U' R2 F2 B2 D' L2 D F2",
    "R B' R' B' U2 R B' R U2 R2 D' R2 D R2 B2 U R2 U R2 U",
    "R B' R' B' U2 R B' R F2 R2 U R2 F2 D L2 D R2 U2 L2 B2",
    "F' U2 B L' U2 B L F B2 U R2 U R2 U2 R2 U' R2 U2 R2 U"
  ],
  "oll.2": [
    "L U2 R' F U2 R' F' L' D' B2 D' F2 D B2 D' L2 F2 D2 R2",
    "R' U2 L F' U2 L F R D B2 D F2 D' B2 D R2 F2 D2 L2",
    "R U2 L' B U2 L' B' R' U' F2 D2 B2 R2 D B2 L2 U L2 D",
    "R U2 L' B U2 L' B' R' U F2 D2 R2 D B2 L2 U' L2 D2 R2 D'",
    "R' U2 L F' U2 L F R L2 U' B2 L2 U B2 U' B2 U' L2 U2"
  ],
  "oll.3": [
    "R L' B' L U2 L' B' R B' L U2 D2 R2 L2 U2 D2 L2",
    "R L' B' L U2 L' B' R B' L F2 B2 L2 D R2 F2 B2 L2 U'",
    "L U2 F U2 R' F R F2 L' U B2 D F2 U2 D F2 D B2 D",
    "R' L F' R U2 R' F' L F' R' F2 R2 L2 B2 U R2 L2 D R2 L2",
    "R U2 B U2 L' B R D2 L' U R2 U L2 D' R2 B2 D' B2 R2 D'"
  ],
  "oll.4": [
    "R L' B R' U2 R B L' B R U2 D2 R2 L2 U2 D2",
    "R L' B R' U2 R B L' B R U F2 B2 D2 F2 B2 U R2 L2",
    "R B U2 B' R' U2 R' F R F U' F2 U' R2 U F2 U F2 U' R2",
    "R' U2 F' U2 L F' L' F2 R U D2 F2 D' B2 D F2 D' B2 D'",
    "B' R2 F R U2 F' R B L2 U L2 F2 U F2 D' L2 B2 U' B2 D"
  ],
  "oll.5": [
    "R' F' L F' R' D2 L F2 R2 U2 L2 B2 L2 U2 L2",
    "R L2 B' L2 B L2 B' R U' R2 U F2 L2 F2 U B2 U' R2 B2 U'",
    "L' B' R B' R' B2 L F2 R2 F2 B2 L2 B2 U F2 B2 D F2 B2",
    "R2 L F' R2 F R2 F' L U L2 B2 R2 D B2 U' B2 R2 B2",
    "R2 B' R F R F' R2 B U R2 F2 D2 B2 D' B2 D' F2 U"
  ],
  "oll.6": [
    "L F R' F R F2 L U D' B2 U B2 U' D L2",
    "R2 L' B R2 B' R2 B L' U L2 U' F2 R2 F2 U' B2 U L2 B2 U",
    "R' L2 F L2 F' L2 F R F2 R2 B2 R2 F2 R2 D' F2 R2 L2 B2",
    "R B L' B R D2 L F2 R2 U2 L2 B2 L2 U' R2 L2 D R2 L2",
    "R U R' B' U' R2 U R B U2 F2 R2 B2 D' F2 B2 U' B2 L2 B2"
  ],
  "oll.7": [
    "F' L2 D L' D' L' F L2 U L2 U B2 D' B2 D L2 U2 L2",
    "B2 L' B R B R' B2 L U B2 L2 U' R2 D F2 L2 D' R2 B2 U2",
    "R B2 L' B' L B' R F2 R2 L2 B2 L2 U' R2 L2 D' R2 L2",
    "F2 R' F L F L' F2 R U R2 U L2 B2 D B2 L2 U' R2 F2",
    "B' R' F R' F' R2 B R2 U' F2 R2 F2 U2 F2 R2 F2 U' R2"
  ],
  "oll.8": [
    "R' F2 L F L' F R U2 R2 L2 U2 D2 R2 L2 D2",
    "B2 R B' L' B' R D2 L' U R2 F2 U' R2 D F2 L2 U F2 U2 F2",
    "F2 L F' R' F' R F2 L U' R2 B2 D B2 R2 U L2 U F2",
    "R' U2 L F R' F L U2 R2 U R2 U2 L2 B2 L2 D2 F2 D L2 B2",
    "R2 U F' R' B' R' B R2 F R2 F2 U L2 D R2 B2 D' R2 L2"
  ],
  "oll.9": [
    "R' B' R U' R U B U' R B2 U B2 D' R2 D",
    "R' B' R U' R U B U' R' B2 U' R2 D R2 F2 U R2 F2 B2 L2",
    "R U2 R' F' U F' L' U' L F2 D R2 D' F2 R2 U' F2 U R2 F2",
    "L U' F' U' L U D F L2 D B2 R2 U D2 B2 L2 F2 U L2 U'",
    "R B2 D' B D B R U F2 U' R2 B2 D B2 U2 R2 F2 R2 U'"
  ],
  "oll.10": [
    "L' B' R B' R' B2 L' U L2 B2 U2 B2 U B2 U B2 U2 L2 U' L2",
    "F' L F L F2 B2 R D2 R D' R2 B2 U2 L2 U L2 U F2 L2 U",
    "R' F' L F' L' F2 R' U' F2 B2 D' F2 U R2 U2 F2 D' L2 D2 F2",
    "F U2 B' R2 F2 L F L' B U2 L2 U2 F2 U2 B2 D' F2 D' B2 L2",
    "L2 F' L B L B' L2 F' U F2 U' F2 L2 U' L2 D F2 D' L2 U"
  ],
  "oll.11": [
    "R B2 R' U2 L' B L B' L2 U' R2 F2 U' F2 U F2 R2 L2 U' B2",
    "L U' F2 U F' U2 F' U L F2 U' B2 D' R2 D2 F2 D' B2",
    "R B' R2 F R F2 U2 L2 F' D' R2 B2 L2 U2 R2 U' L2 D L2",
    "R' U2 R B2 L F' L F R2 U' R2 U R2 D' R2 D L2 B2 U2",
    "R' U F U R' U' D' F U R2 L2 U2 R2 U' R2 D2 B2 U L2 D'"
  ],
  "oll.12": [
    "F' L2 B L B' L F U R2 U' R2 U R2 B2 R2 U B2 U' R2 B2",
    "R2 F R' B' R' F D2 B' D B2 D B2 D F2 U2 B2 U R2 U'",
    "R B2 D' B D B R' L2 U' F2 D2 R2 D' R2 D' F2 L2 U2",
    "L2 B L' F' L' F L2 B D' B2 U' L2 D L2 D L2 F2 D' F2",
    "R' L2 F L2 F' L2 F R B2 D F2 R2 F2 D R2 D2 B2 L2 F2"
  ],
  "oll.13": [
    "R2 B' R F R F' R2 B R2 F2 D2 L2 D L2 D F2 R2 U' R2 U'",
    "F U2 B' R' F R' B D R2 F2 L2 U2 F2 U' B2 U F2 U' L2",
    "R' F2 D F' D' F' R F2 U F2 L2 U L2 F2 U' F2 U",
    "L2 F' L B L F' D2 B R2 B2 U2 L2 U B2 R2 D' B2 U' L2 U",
    "R U F' L2 B' L2 F U R B2 U R2 D' R2 D B2 U' R2 U'"
  ],
  "oll.14": [
    "F R B2 R2 B2 R B2 R F D2 L2 F2 D' L2 D' B2 U R2 U2 F2",
    "R' U2 L F R' F L F2 U B2 L2 D F2 R2 U F2 U' R2 B2",
    "R' F2 L F L' F R F2 U' F2 D F2 D' L2 U L2 F2",
    "B2 R B' L' B' R D2 L' D' F2 U' F2 U L2 D' R2 U B2 U'",
    "R U2 D' R B' D B U2 R B2 D2 F2 B2 U' B2 D' L2 F2 B2 D"
  ],
  "oll.15": [
    "R' F' L F' R' D2 L D R2 B2 R2 D L2 F2 R2",
    "R L2 B' L2 B L2 B' R U R2 F2 D R2 L2 U' L2 U R2 F2 U'",
    "L' B' R B' R' B2 L U2 R2 U' F2 R2 F2 U2 F2 R2 F2 U' R2",
    "R2 L F' R2 F R2 F' L U' D F2 U R2 B2 D' R2 F2 R2 U' R2",
    "R2 B' R F R F' R2 B R2 F2 U' R2 D2 L2 B2 D L2 D R2 U'"
  ],
  "oll.16": [
    "L F R' F R F2 L U' F2 R2 B2 D B2 R2 F2 U2 L2",
    "R2 L' B R2 B' R2 B L U R2 B2 U' B2 R2 B2 U' B2",
    "R' L2 F L2 F' L2 F R U' F2 L2 U L2 F2 L2 U L2",
    "R B L' B R D2 L U' F2 L2 B2 D R2 B2 R2 D2 L2 U2",
    "R U R' B' U' R2 U R B L2 F2 U L2 B2 R2 D B2"
  ],
  "oll.17": [
    "R' F R' F L2 D2 R' B' R D2 L2 D B2 D' F2 D B2 D' R2",
    "F U R F' D2 B U L' B' U2 B2 U L2 U B2 D' R2 U' R2 D'",
    "F R B U B' U R' U2 F' U2 F2 U2 F2 L2 U' F2 U' F2 U L2",
    "R2 B2 L D' R F R' D L' B2 R2 U2 L2 U' L2 U' L2 U2 L2",
    "F R F D2 L' B L2 B2 L' U' L2 U L2 D F2 U2 F2 D F2 U'"
  ],
  "oll.18": [
    "R2 F2 L' D R' B' R D' L' B2 L2 D R2 F2 U B2 L2 U' B2 U2",
    "R2 F2 L' D R' B' R D' L U2 L2 U' R2 U R2 L2 U2 F2 R2 U'",
    "R B' R B' L2 D2 R F R F2 B2 L2 U2 R2 F2 R2 U'",
    "R B' R B' L2 D2 R F R F2 U2 R2 F2 L2 F2 L2 F2 D2 R2 U",
    "R2 B2 R' U L' B' L U' R U' R2 U B2 L2 D' F2 D R2 L2 U"
  ],
  "oll.19": [
    "R B' R B2 U L' B L' F2 U L2 B2 R2 D2 B2 U B2 D' R2 U'",
    "R B' R B2 U L' B L F2 B2 R2 F2 U' F2 U' F2 U R2 F2 U'",
    "R L' B' R' F' L2 F L' F2 U' B2 L2 D' F2 R2 U' D' B2 R2 B2",
    "R L' B' R' F' L2 F L D' L2 F2 D F2 D F2 U' F2 L2 U2 L2",
    "R B' R B2 U L' B L B2 U' R2 U' R2 U' R2 U2 R2 U' R2"
  ],
  "oll.20": [
    "R L' F2 D2 B R L U B2 D' L2 D' B2 U B2 U F2 U' L2 U2",
    "R L' F2 D2 B R L U B2 D' R2 L2 D2 R2 D B2 U F2 B2 L2",
    "R L' F2 D2 B R L F2 B2 L2 D F2 B2 U F2 B2 D F2 U' D2",
    "R L' F2 D2 B R L' F2 D F2 R2 L2 U B2 U B2 U B2 D2",
    "R L' F2 D2 B R L U' F2 L2 B2 D' L2 F2 U' B2 U D2"
  ],
  "oll.21": [
    "R U B2 R' B2 R2 U' R' U L2 F2 R2 U L2 U L2 U' F2 U' L2",
    "R U B2 R' B2 R2 U' R U R2 B2 L2 D2 B2 L2 U F2 U R2 F2",
    "R U B2 R' B2 R2 U' R' B2 L2 D2 L2 U L2 D R2 D R2 L2 U2",
    "R' U' F2 R F2 R2 U R F2 L2 D2 F2 L2 U B2 U R2 B2 U",
    "R U B2 R' B2 R2 U' R U2 L2 D' R2 F2 U' D2 F2 L2 D' B2"
  ],
  "oll.22": [
    "R D L2 B2 D' B2 D' R U2 F2 R2 D' L2 U' L2 U L2 D' B2 D'",
    "R D B2 D B2 L2 D' R U' R2 U' R2 D2 L2 D R2 F2 D' F2 D",
    "F R2 F' U L2 B' D' B L2 F2 U' L2 U' B2 D B2 U L2 F2",
    "F R2 F' U R2 F' U' F R2 B2 R2 U' R2 U' B2 U B2 U B2",
    "F U2 F' U R2 F' D' F U F2 B2 L2 D L2 D' L2 B2 D F2 U2"
  ],
  "oll.23": [
    "F D B2 D' F U' F2 U' R2 D R2 B2 U2 B2 D B2 D2",
    "F D B2 D' F L2 U R2 F2 U' L2 D R2 D' F2 U2",
    "R' D' L2 D R U2 R2 L2 D' R2 U F2 U R2 D2 R2 U' F2",
    "R' D' L2 D R U R2 U' R2 D L2 F2 U L2 B2 D' L2 F2 D R2",
    "F D B2 D' F R2 U L2 U L2 U' B2 D R2 F2 L2 B2 U2"
  ],
  "oll.24": [
    "R' F' L F' L' F' R F' R2 U2 F' U2 F R2 B' R2 B R2 U2",
    "L D R2 D' L U F2 U L2 D2 R2 F2 U2 F2 D2 B2",
    "R D L2 D' R U2 L2 F2 R2 U L2 B2 D' L2 D2",
    "R D L2 D' R F2 L2 F2 D' F2 D F2 D' L2 F2 R2 U",
    "L D R2 D' L D2 B2 L2 F2 U F2 U L2 B2 R2 L2"
  ],
  "oll.25": [
    "R U2 R F2 R' U2 R' U R2 U F2 U' R2 D R2 D' R2 U'",
    "R U2 R F2 R' U2 R F2 D' F2 D B2 D' F2 D L2 D2 L2 B2 R2",
    "R F2 R' B2 R F2 R F2 R2 U L2 U L2 U' R2 D L2 F2 R2",
    "R F2 R' B2 R F2 R B2 L2 U F2 D F2 U' L2 U R2 B2 R2",
    "R U2 R F2 R' U2 R' F2 R2 F2 R2 U R2 D' L2 U L2 F2 D F2"
  ],
  "oll.26": [
    "R U R2 U' R2 U R U2 F2 R2 F2 U2 F2 R2 F2 U",
    "R U R2 U' R2 U R L2 D' R2 D' R2 D' R2 D' R2 D' L2",
    "F' D' B D F' D' B U R2 L2 B2 U' R2 D B2 U2 B2 L2 B2",
    "F' D' B D F' D' B U B2 U' F2 R2 U' F2 L2 F2 R2 B2 U2",
    "R U R2 U' R2 U R L2 F2 U' B2 R2 F2 D' B2 U"
  ],
  "oll.27": [
    "F' U B U' F U B U F2 R2 U R2 U' R2 D R2 D' F2 B2",
    "R U2 R' U' R U' R U' R2 U R2 B2 R2 U B2 U' R2 B2",
    "R D L' D' R D L U2 B2 U2 L2 U L2 B2 U B2 D' B2 U2 R2",
    "R D L' D' R D L' U L2 U L2 U2 L2 D' R2 U R2 U R2 U2",
    "R U2 R' U' R U' R F2 U' F2 U F2 R2 B2 D L2 D' B2"
  ],
  "oll.28": [
    "F U F' R' F2 U' F' U R L2 F2 R2 D' L2 B2 L2 D R2 L2",
    "R F D B2 R D2 F U' L' U D F2 R2 U' F2 D B2 D' F2 U2",
    "R U' D F R2 F' U D' R U F2 R2 F2 U' R2 F2 U2",
    "R U R' B' R2 U' R' U B R2 F2 U2 R2 F2 R2 U2 F2",
    "R' F' L U2 L' F R B2 U' L2 U2 B2 U B2 U L2 B2 U B2 U2"
  ],
  "oll.29": [
    "F U R U' R' F U R2 B2 U' F2 D L2 U2 B2 D' R2 U' R2 U2",
    "F2 U' B L2 B D2 R F R' U2 F2 U' B2 D2 F2 B2 D F2 D' B2",
    "R2 F U' R' U' R U R F' R2 U R2 U R2 U' R2 U R2 U",
    "B U L U' L' B R2 U B2 D' B2 D L2 U' R2 L2 B2 U'",
    "R B' R D B2 L' B L' U' L2 U' R2 U B2 U2 R2 D B2 D2"
  ],
  "oll.30": [
    "F R U R' U' F U F2 U F2 U' F2 U L2 U' L2 D F2 D' F2",
    "F R U R' U' F U R2 L2 U F2 U F2 U2 L2 U R2 U2 F2 U",
    "R B' R D B2 L' B L B2 L2 U R2 D' F2 D L2 F2 U L2 F2",
    "R B' R D B2 L' B L D2 R2 U R2 B2 U B2 U' B2 D R2",
    "R2 B' R U2 R' U2 R' B U2 B2 U2 R2 F2 D B2 D' F2 U2 R2 B2"
  ],
  "oll.31": [
    "F R L2 U R' U' L2 F U L2 U L2 U' L2 F2 L2 D F2 D' L2",
    "F R L2 U R' U' L2 F U' F2 R2 U2 R2 F2 U F2 U2 R2 U' R2",
    "R2 U B' D R D' R' B U' R2 U F2 D' F2 D R2 U' R2 U'",
    "F U F U' F' L F' L U2 R2 F2 L2 D2 L2 D' R2 L2 U B2 U'",
    "R B' U B' U' B R U B2 U' R2 U B2 D' R2 D B2 U"
  ],
  "oll.32": [
    "R U R U' R' F R' F L2 U R2 U' L2 F2 B2 D L2 D' B2 U'",
    "F2 U F' U R U' R' F U2 L2 U2 R2 B2 D B2 R2 U' L2 F2 U2",
    "F' U' F' U F R' F R U' R2 F2 L2 D R2 B2 R2 D' R2 L2",
    "R F2 B U B' U' F2 R U F2 U' R2 U R2 U F2 U' R2",
    "R' B' R2 B R F2 D B2 U' B2 R2 U2 D' F2 R2 F2"
  ],
  "oll.33": [
    "R2 B R' U' B' R' U R2 F R2 B' R2 F D2 B D2 F2 R2",
    "R L D2 R' B L2 B' L D F2 U2 F2 L2 D' R2 D L2 F2 D R2",
    "R U' B' R' U2 L2 D F U R2 B2 U B2 R2 U' L2 U L2 F2 L2",
    "L B L2 B' L U L2 D F2 L2 D2 B2 R2 U D B2",
    "R2 U B' D R D' R' B' U D B2 U F2 U L2 F2 R2 U2 B2 U'"
  ],
  "oll.34": [
    "R F R2 F' R U D' L2 D R2 D' L2 U' D R2",
    "L2 U L B' U' B U L U B2 U' B2 U' L2 B2 U2 B2 U' L2 U",
    "R F R2 F' D L2 D' R F2 B2 U' L2 U B2 D2 L2 U' R2 B2 D'",
    "L B L2 B' L U' L2 U F2 D2 B2 D B2 D F2 L2",
    "R2 U B' D R D' R' B' U B2 U' L2 U B2 R2 U2 L2 U F2 D"
  ],
  "oll.35": [
    "R' B' R2 B R U' F2 R2 U F2 L2 D2 L2 U F2 U2 L2 D' B2 L2",
    "L' U B L U2 R2 D' F R2 U B2 U2 R2 D' L2 D' F2 L2 D' R2",
    "F L F2 L' F R2 U L2 U' B2 D' B2 U L2 F2 U F2 U' R2",
    "R' B' R2 B D' L2 D R' U2 F2 U2 D B2 D2 F2 L2 D F2 R2 F2",
    "R' B' R' B2 L' B L U2 R2 B2 R2 U2 B2 U R2 U R2"
  ],
  "oll.36": [
    "F' L F U2 R B2 R F2 D L2 F2 L2 D R2 B2 U R2 F2 R2",
    "R' U2 R' F R F' U2 R U2 B2 R2 U B2 U B2 U2 R2 B2 U2",
    "R2 B' D R D' R' B R2 F2 R2 D B2 U' B2 R2 U' D' F2",
    "R2 F' L F' U L U' L' U2 R2 B2 D L2 F2 R2 F2 D2 B2 L2 U2",
    "R2 F D' R' D R F D F2 B2 L2 F2 D' B2 U' F2 U R2 F2"
  ],
  "oll.37": [
    "B U' L U2 L' U B U2 B2 U2 B2 U B2 U B2 U' B2 U",
    "F R F U F' R' F R2 U B2 L2 F2 D L2 B2 U' F2",
    "R2 F2 R' B U B' U' R F2 B2 U B2 U' B2 D B2 D' R2 U2",
    "R2 F2 L F' D' F D L' U' R2 D R2 D' F2 B2 L2 F2 D' L2 B2",
    "R B' R' U R2 B D B U F2 U' L2 U F2 D' B2 R2 U' R2"
  ],
  "oll.38": [
    "R2 F D' R' D R F D' F2 R2 F2 R2 U R2 D F2 L2 D L2",
    "R B2 R B' L' B D2 L' F2 R2 U B2 U' B2 U' R2 F2 R2 L2 U",
    "R U2 R B' R' B U2 R U' R2 U F2 R2 U' F2 U R2 F2 R2",
    "L2 B D' L' D L B R2 B2 D' B2 U R2 F2 R2 B2 U D F2",
    "R B R U R' B' R U2 F2 R2 F2 U2 F2 R2 F2 U' R2"
  ],
  "oll.39": [
    "F2 R' D F D' F' R U F2 U' R2 B2 U' L2 B2 R2 U F2 D'",
    "F2 U R' L2 B' R2 B R' L2 U2 R2 U R2 L2 B2 R2 D' B2 L2 U2",
    "R2 B2 R U' F' U F R' U B2 R2 D B2 D' B2 R2 U' R2 U'",
    "L' B L U2 B U2 B' U B2 U2 R2 U B2 U2 R2 U' B2 U2 R2 U",
    "R2 F2 R' B U B' U' R U R2 D' R2 D B2 U' F2 B2 R2 U"
  ],
  "oll.40": [
    "F2 L D' F' D F L U R2 U' R2 U' B2 U R2 D R2 L2 F2 R2",
    "R B' R' U R2 B D B' D' R2 U2 B2 U' B2 U' B2 U2 B2 U",
    "R B' R' U2 B' U2 B U L2 U2 B2 U' L2 U2 B2 U L2 U2 B2 U",
    "L F' L' U R2 B U B U' B2 U' B2 U B2 U F2 R2 L2 B2 L2",
    "R2 B2 R U' F' U F R U D' F2 U' L2 D B2 U' F2 D B2 D'"
  ],
  "oll.41": [
    "R' U' F' U F R F2 U2 R2 B2 L2 D' L2 B2 R2 U F2",
    "B2 L' F R2 B' R2 F' L U B2 U F2 R2 B2 R2 U F2 D' L2 D",
    "F2 R' F U2 F' U2 F' R' F2 R2 U' R2 D' F2 D R2 U' F2 U'",
    "L' U' B' U B L U2 R2 U' F2 L2 B2 D B2 L2 F2 U2 R2",
    "R B U B' U' R U' F2 R2 F2 U2 F2 R2 F2 U' R2"
  ],
  "oll.42": [
    "F2 R' F U2 F' U2 F' R U B2 U L2 U' B2 U B2 L2 F2 B2 U",
    "L' U' B' U B L F2 U' R2 B2 L2 D L2 B2 R2 U2 F2",
    "R' U' F' U F R U2 R2 U F2 L2 B2 D' B2 L2 F2 U2 R2",
    "B2 R2 L' D B D' B' L U2 R2 U' B2 U2 R2 F2 L2 B2 D' L2 F2",
    "R' F' U' F U R F2 U2 R2 B2 L2 D' L2 B2 R2 U F2"
  ],
  "oll.43": [
    "B L U L' U' B U R2 F2 L2 D' L2 F2 R2 U2 B2",
    "F' L' U' L U F R2 U R2 U' R2 F2 R2 U' F2 U R2 F2",
    "R U B' U' R' B' U B U' R2 U2 F2 L2 B2 D2 L2 F2 U'",
    "R2 F2 U' R' F R2 F' R U2 B2 D' B2 U' B2 D2 F2 L2 B2 R2 U'",
    "B' U' R' U R B R2 U F2 L2 B2 D' B2 L2 F2 U2 R2"
  ],
  "oll.44": [
    "B' R' U' R U B R2 U' B2 R2 B2 U2 B2 R2 B2 U' R2",
    "F R U R' U' F U R2 U B2 L2 F2 D L2 B2 U' F2",
    "L U F' U' L' F' U F U2 L2 B2 R2 U' B2 L2 F2 D'",
    "R U R B' R' B U' R F2 R2 L2 B2 L2 U' R2 L2 D' R2 L2",
    "R2 F2 B' D R D' R' B U2 B2 D' L2 D2 F2 D F2 D' F2 B2 U'"
  ],
  "oll.45": [
    "F U R U' R' F' U F2 R2 L2 F2 B2 R2 L2 B2",
    "R B2 U' L U' L B R B' L2 B2 R2 U B2 U B2 U B2 U' B2",
    "R U' B' R' U' B' R2 U B R2 B2 U' B2 R2 B2 U' B2 U2",
    "B U L U' L' B R2 L2 F2 D F2 R2 L2 B2 U",
    "R U R B' R' B U' R B2 U B2 U' B2 R2 F2 D' L2 D F2"
  ],
  "oll.46": [
    "F' U' L' U L F R2 U' R2 U R2 B2 R2 U B2 U' R2 B2",
    "R2 F2 B' D R D' R' B U2 R2 F2 U F2 U2 R2 U' F2 R2 U2",
    "B' U' R' U R B R2 F2 R2 L2 B2 L2 U R2 L2 D R2 L2",
    "L2 F' B2 D L D' L' F U2 B2 L2 B2 L2 U B2 U2 L2 U' B2 L2",
    "R2 F B2 D' R' D R F B2 U2 R2 F2 U F2 U2 R2 U' F2 R2 U2"
  ],
  "oll.47": [
    "R D L2 D2 B' D B R D2 F2 R2 U' R2 F2 L2 D2 R2 U'",
    "R D L2 D2 B' D B R L2 B2 L2 D B2 L2 B2 D' R2 U' L2 U'",
    "R' F R' D R2 B2 D2 R' F' R' B2 D' L2 U2 F2 L2 D' F2 U F2",
    "F D' F2 L' U' L U2 F2 D F U2 R2 U' R2 U' F2 R2 U R2",
    "L F2 R2 F L F2 R2 F' U B2 R2 F2 D L2 D F2 R2 L2 B2 U"
  ],
  "oll.48": [
    "F U R U' R' U R U' R' F U2 D2 F2 B2 U2 D2 B2",
    "R2 B' D R F D R' B R2 F' U R2 B2 U B2 D' B2 U' B2 R2",
    "R D L2 D2 B' D B R U2 R2 D' B2 L2 U L2 B2 L2 D2",
    "R' D' L2 D2 F D' F' R F2 R2 U' L2 F2 L2 D B2 U F2 D'",
    "R B2 L2 B R F2 R2 B' U2 B2 L2 B2 U2 L2 U' R2 L2 D' R2 L2"
  ],
  "oll.49": [
    "L F2 L2 B L F2 L2 B R2 U2 L2 F2 R2 D2 F2",
    "F2 R' F' R L2 B D2 B' L2 U2 L2 U' B2 U' L2 U F2 U' R2 D'",
    "B2 L' B' R2 L B R2 B R2 U B2 D B2 D' R2 B2 U' R2 U' B2",
    "R B2 R2 F R F2 L2 F' U2 F2 L2 F2 U2 L2 U' R2 L2 D' R2 L2",
    "F D' F2 U L' U F' L2 D' L D B2 L2 U B2 U' L2 B2 D F2"
  ],
  "oll.50": [
    "L F2 R2 F L F2 R2 F R2 U2 L2 B2 R2 D2 B2",
    "B2 R B R' L2 F' D2 F L2 U2 L2 U F2 U L2 U' B2 U R2 D",
    "R B2 L2 B R F2 R2 B' U2 B2 L2 B2 U2 L2 U R2 L2 D R2 L2",
    "F2 L F R2 L' F' R2 F' R2 U' F2 D' F2 D R2 F2 U R2 U F2",
    "R U2 R2 D' F' R2 U2 R2 F R U R2 B2 L2 D' L2 B2 D R2 U2"
  ],
  "oll.51": [
    "F' L2 B' D2 F2 R B' R F U2 B2 U R2 U' R2 D R2 D' F2 D2",
    "L F2 L2 B L F2 L2 B R2 U F2 R2 B2 D F2 U2",
    "R B2 R2 F R F2 L2 F U R2 D R2 L2 U' L2 U2 L2 F2 L2 U'",
    "R U2 L' F' B' U2 B' L F' R' B2 U R2 U' R2 D' B2 D F2 U2",
    "R D L2 D2 B' D B R U' B2 U R2 F2 D' R2 L2 B2 D' R2 F2"
  ],
  "oll.52": [
    "R D L2 D2 B' D B R' F2 U F2 D' L2 D2 L2 F2 U' F2 L2 D'",
    "R F2 U2 B U' B' R F2 D R' U D2 F2 L2 U2 L2 D R2 U",
    "B' R' U' R' B R2 B2 U B' U R2 B2 R2 B2 U B2 U B2 U2",
    "F R U R F' R2 F2 U' F U' R2 F2 R2 F2 U' F2 U' F2 U2",
    "R2 F' L F' B2 R' U2 R B2 R2 U' R2 D2 R2 U B2 L2 U B2"
  ],
  "oll.53": [
    "F' U L F' U' L U D' L F2 B2 U F2 U L2 F2 U D R2 U",
    "R2 U R B' R U2 F' L2 F R2 B2 U F2 L2 U2 F2 D B2 D2",
    "R B U' B' R U B' D B' D L2 F2 L2 D' L2 D L2 D2 B2",
    "R2 U R B' R U2 F' L2 F' U' L2 D2 L2 F2 R2 B2 D' B2 R2",
    "R U R B2 U D2 F L' F L2 U F2 D2 R2 B2 R2 B2 U' R2 U"
  ],
  "oll.54": [
    "R2 U' R' F R' U2 F U2 F U2 B2 R2 F2 D' F2 R2 D' F2 D2 B2",
    "L2 U' L' B L' U2 F R2 F D' F2 U2 B2 L2 B2 U' F2 R2 D2 F2",
    "R' F' U F R' U' F D' F' U2 F2 D R2 F2 U F2 R2 F2 U' R2",
    "F U' R' F U R' U' D R L2 D' B2 L2 D L2 F2 U2 R2 B2 U",
    "F' U2 R B2 L B2 R' U2 F U' L2 D' B2 D L2 B2 U L2 U' B2"
  ],
  "oll.55": [
    "R U' B2 R2 L2 F' D' F' R U L2 U' R2 D' B2 R2 F2 L2 U2 F2",
    "R' U' R U R' U2 F R' F' U2 R2 B2 U B2 D' R2 D R2 U2",
    "R U' B2 R2 L2 F' D' F' R' D2 F2 L2 D B2 D' B2 R2 U' B2",
    "R B' R' L2 B L B2 L B U' L2 B2 U' R2 F2 D' F2 R2 U B2",
    "R U2 R U2 D R B R' B' L2 D F2 L2 D R2 D R2 U' R2 B2"
  ],
  "oll.56": [
    "F2 U F R' F U2 R' U2 R B2 L2 D' R2 F2 D F2 R2 D2 L2 B2",
    "R F' B L' B L' F B2 R U' F2 U B2 U' L2 D' F2 D B2 D'",
    "R F' B L' B L' F B2 R U' F2 U B2 D' B2 U' F2 U R2 U",
    "F2 U F R' F U2 R' U2 R B2 L2 D R2 F2 D2 B2 L2 U' R2 F2",
    "F2 U' F' L F' U2 L U2 L' B2 R2 D L2 F2 D' F2 L2 D2 R2 B2"
  ],
  "oll.57": [
    "R L F R2 F R L U2 L2 F2 L2 U2 L2 F2 U' R2 U' R2",
    "R L F U2 F R L U2 L2 B2 R2 D R2 U2 D R2 U' B2 U' B2",
    "R L F R2 F R L D L2 U L2 B2 L2 F2 U' R2 F2 U'",
    "R L F U2 F R L' U' B2 R2 L2 D' B2 L2 U' F2 R2 F2 U",
    "R U R' B' R2 U' R' U B U' F2 R2 F2 U F2 R2 F2"
  ],
  "pll.h": [
    "R L D2 R L D2 R2 B2 D2 B2 L2 F2 U2 R2 F2 U2",
    "F B D2 F B D2 F2 R2 D2 R2 B2 L2 U2 F2 L2 U2",
    "B F D2 B F D2 B2 L2 D2 L2 F2 R2 U2 B2 R2 U2",
    "L R D2 L R D2 L2 F2 D2 F2 R2 B2 U2 L2 B2 U2"
  ],
  "pll.z": [
    "R L U2 R L' U' R2 U' R2 U' R2 U' R2 U' R2 B2 R2 B2",
    "F B U2 F B' U R2 F2 R2 U F2 U R2 F2 R2 U F2 U'",
    "B F U2 B F' U L2 B2 L2 U B2 U L2 B2 L2 U B2 U'",
    "L R U2 L R' U' L2 U' L2 U' L2 U' L2 U' L2 F2 L2 F2"
  ],
  "pll.ua": [
    "F2 D F2 R2 F2 D R2 F2 D2 F2 B2 L2 B2 R2 D2 R2",
    "R2 U' B2 R2 B2 U B2 R2 B2 U2 B2 U2 R2 B2 R2 U2 B2",
    "R2 U' F2 R2 F2 U R' L F2 D2 B2 U2 R L B2 D2",
    "R2 D' R2 F2 R2 D R L' F2 D2 B2 U2 R' L' B2 D2"
  ],
  "pll.ub": [
    "F2 U' L2 F2 L2 U F2 L2 U2 L2 F2 L2 U2 F2 L2 U2 F2",
    "F2 D' F2 R2 B2 U R D2 F2 B2 U2 L' F2 R2 U2 B2 U2",
    "F2 D' F2 L2 F2 D F2 L2 D2 L2 B2 R2 U2 F2 R2 U2 B2",
    "L2 U B2 L2 B2 U B2 U2 B2 U2 L2 B2 L2 U2 L2 U2"
  ],
  "pll.aa": [
    "R L U2 R L' U F2 U2 R2 F2 R2 U' B2 U' F2 U R2 B2",
    "F B U2 F B L2 U R2 B2 U L2 U' B2 R2 U' L2 F2 B2",
    "B F U2 B F R2 U F2 L2 D B2 U' F2 R2 D' R2 B2 F2",
    "L R U2 L R' D F2 D' F2 U2 L2 F2 L2 U L2 U L2 F2"
  ],
  "pll.ab": [
    "R L U2 R L U' D' F2 D L2 F2 D B2 D' F2 L2 U' L2",
    "F B U2 F B' R2 U L2 U' B2 U2 B2 L2 F2 D L2 D L2",
    "B F U2 B' F R2 U L2 U' B2 U2 B2 L2 F2 D L2 D L2",
    "L R U2 L R U' D' B2 D B2 R2 U L2 U' R2 B2 U' R2"
  ],
  "pll.e": [
    "R L F2 R L' U' L2 D2 F2 U' B2 U' R2 F2 D2 B2 U' R2",
    "F B L2 F' B' L2 U R2 D' L2 B2 L2 D R2 U F2 U2 L2",
    "B F R2 B' F' R2 U L2 D' R2 F2 R2 D L2 U B2 U2 R2",
    "L R B2 L R' U' R2 D2 B2 U' F2 U' L2 B2 D2 F2 U' L2"
  ],
  "pll.f": [
    "R L' F2 R L' U' R2 U' R2 L2 F2 U L2 D' B2 D L2 F2",
    "F B D2 F B' D' L2 B2 D' L2 B2 U' F2 L2 R2 U L2 D'",
    "B F D2 B' F D' R2 L2 F2 U B2 L2 D B2 L2 U L2 D'",
    "L R' B2 L R' U R2 U L2 R2 B2 U' L2 D F2 D' L2 B2"
  ],
  "pll.ja": [
    "R L U2 R L' B2 U R2 F2 B2 U' L2 U L2 B2 D F2 U'",
    "F B U2 F B' U F2 D' F2 D R2 F2 L2 B2 D B2 L2 U",
    "B F U2 B' F U R2 B2 D B2 D' L2 U F2 R2 B2 R2 D",
    "L R U2 L' R B2 U L2 U' R2 U R2 F2 D F2 L2 R2 U'"
  ],
  "pll.jb": [
    "R L U2 R L U D' F2 U' F2 D R2 D' F2 D L2 U2",
    "F B U2 F B U L2 U B2 U' L2 R2 F2 U F2 U' L2 D",
    "B F U2 B F U L2 U B2 U' R2 L2 F2 U F2 U' L2 D",
    "L R U2 L R U D' F2 U' F2 D R2 D' F2 D L2 U2"
  ],
  "pll.ra": [
    "R L U2 R L' U' R2 L2 B2 U L2 D' R2 F2 B2 D R2 U2",
    "F B U2 F B U R2 U' L2 U F2 U' L2 D B2 D' F2 B2",
    "B F U2 B F U R2 U' L2 U F2 U' L2 D B2 D' B2 F2",
    "L R U2 L R' D' L2 F2 U' L2 U R2 U' B2 R2 F2 L2 U2"
  ],
  "pll.rb": [
    "R L U2 R L' U L2 U' L2 D F2 D' F2 R2 L2 F2 L2 U2",
    "F B U2 F B L2 U' F2 R2 D' F2 D L2 D' R2 F2",
    "B F U2 B F L2 U' F2 R2 D' F2 D L2 D' R2 F2",
    "L R U2 L R' U L2 B2 L2 R2 D B2 D' F2 D R2 F2 U2"
  ],
  "pll.t": [
    "R L F2 R L U R2 U' L2 F2 U' F2 U F2 R2 U' R2 F2",
    "F B L2 F B' U2 F2 U F2 U' R2 B2 U' L2 U B2 D' R2",
    "B F R2 B' F' U' R2 U R2 D' R2 D2 B2 U B2 D' R2",
    "L R B2 L' R D B2 U2 F2 R2 F2 U L2 U R2 U' F2 U"
  ],
  "pll.y": [
    "R L B2 R' L' U' L2 U' L2 U B2 D B2 D' R2 U R2 U",
    "F B U2 F B' U' L2 U R2 D' R2 U' B2 D R2 D' L2 U'",
    "B F U2 B' F U' L2 U R2 D' R2 U' B2 D R2 D' L2 U'",
    "L R B2 L' R' U' L2 U' L2 U B2 D B2 D' R2 U R2 U"
  ],
  "pll.v": [
    "F B U2 F B U F2 U2 L2 U' L2 F2 U2 F2 U L2 U2 B2",
    "L R U2 L R U B2 U2 L2 D' L2 F2 D2 F2 U R2 U2 F2",
    "R L U2 R L U B2 U2 L2 D' L2 F2 D2 F2 U R2 U2 F2",
    "B F U2 B F U F2 U2 L2 U' L2 F2 U2 F2 U L2 U2 B2"
  ],
  "pll.na": [
    "R L' U2 R' L U2 F2 L2 U' L2 U2 F2 U L2 U2 L2 F2 U'",
    "F B' U2 F' B U2 L2 B2 U' B2 U2 L2 U B2 U2 B2 L2 U",
    "B F' U2 B' F U2 R2 F2 U' F2 U2 R2 U F2 U2 F2 R2 U",
    "L R' U2 L' R U2 B2 R2 U' R2 U2 B2 U R2 U2 R2 B2 U'"
  ],
  "pll.nb": [
    "R L' U2 R' L U2 F2 R2 U R2 U2 F2 U' R2 U2 R2 F2 U",
    "F B' U2 F' B U2 L2 F2 U F2 U2 L2 U' F2 U2 F2 L2 U'",
    "B F' U2 B' F U2 R2 B2 U B2 U2 R2 U' B2 U2 B2 R2 U'",
    "L R' U2 L' R U2 B2 L2 U L2 U2 B2 U' L2 U2 L2 B2 U"
  ],
  "pll.ga": [
    "R L U2 R' L F2 U' B2 R2 F2 L2 D' R2 D L2 D' B2 U",
    "F B U2 F B' L2 R2 U' R2 U F2 U' R2 D F2 B2 R2 D'",
    "B F U2 B F' U' B2 L2 U' L2 U F2 U' B2 U F2 L2 B2",
    "L R U2 L R' F2 U' B2 R2 F2 L2 D' R2 D L2 D' B2 U"
  ],
  "pll.gb": [
    "R L U2 R L F2 U L2 U' R2 U B2 R2 D B2 R2 U",
    "F B U2 F B' U' R2 F2 U' F2 U F2 R2 D R2 D'",
    "B F U2 B F' U D' R2 U' F2 U B2 U' B2 D L2 U' R2",
    "L R U2 L R F2 U L2 U' R2 U B2 R2 D B2 R2 U"
  ],
  "pll.gc": [
    "R L U2 R L' B2 U R2 F2 L2 B2 U B2 U' L2 D F2 U'",
    "F B U2 F B' U L2 B2 R2 B2 L2 D' F2 D R2 U' F2 U",
    "B F U2 B F' U R2 U' B2 U R2 D' B2 L2 U' B2 L2 F2",
    "L R U2 L' R B2 U L2 U' L2 D F2 D' L2 R2 B2 L2 U'"
  ],
  "pll.gd": [
    "R L U2 R L' F2 U F2 U' L2 U R2 L2 B2 R2 D B2 U'",
    "F B U2 F B' D' L2 U L2 B2 D F2 D' B2 D R2 F2 R2",
    "B F U2 B F' U B2 R2 U R2 U' F2 U B2 U' B2 R2 F2",
    "L R U2 L R' F2 U B2 U' R2 U B2 L2 B2 F2 D B2 U'"
  ],
  "f2l.1": [
    "F R' F' R"
  ],
  "f2l.2": [
    "R' F R F'"
  ],
  "f2l.3": [
    "F' U F"
  ],
  "f2l.4": [
    "R U' R'"
  ],
  "f2l.5": [
    "R U R' U2' R U' R' U"
  ],
  "f2l.6": [
    "F' U' F U2' F' U F U'"
  ],
  "f2l.7": [
    "R U R' U2' R U2' R' U"
  ],
  "f2l.8": [
    "r' U' R2 U' R2' U2' r"
  ],
  "f2l.9": [
    "F' U F U' R U R' U"
  ],
  "f2l.10": [
    "R U' R' U' R U' R' U"
  ],
  "f2l.11": [
    "F' U F U' R U2' R' U"
  ],
  "f2l.12": [
    "R U R' U2' R U R' U' R U R'"
  ],
  "f2l.13": [
    "r U2' R' U R U' R' U M"
  ],
  "f2l.14": [
    "R U' R' U' R U R' U"
  ],
  "f2l.15": [
    "R U R' U' R U R' U2' R U' R'"
  ],
  "f2l.16": [
    "F' U F U2' R U R'"
  ],
  "f2l.17": [
    "R U' R' U R U2' R'"
  ],
  "f2l.18": [
    "R U R' U' R U R' F R' F' R"
  ],
  "f2l.19": [
    "R U R' U' R U2' R' U'"
  ],
  "f2l.20": [
    "R U R' F R' F' R2' U R' U"
  ],
  "f2l.21": [
    "R U' R' U2' R U R'"
  ],
  "f2l.22": [
    "F' L' U2' L F"
  ],
  "f2l.23": [
    "R U' R' U R U' R' U2' R U' R'"
  ],
  "f2l.24": [
    "R U R' F R U R' U' F'"
  ],
  "f2l.25": [
    "F' R U R' U' R' F R"
  ],
  "f2l.26": [
    "F' U' F U R U R' U'"
  ],
  "f2l.27": [
    "R U R' U' R U R'"
  ],
  "f2l.28": [
    "R' F R F' U R U' R'"
  ],
  "f2l.29": [
    "F R' F' R F R' F' R"
  ],
  "f2l.30": [
    "R U' R' U R U' R'"
  ],
  "f2l.31": [
    "R U R' F R' F' R U"
  ],
  "f2l.32": [
    "R U' R' U R U' R' U R U' R'"
  ],
  "f2l.33": [
    "R U R' U2' R U R' U"
  ],
  "f2l.34": [
    "R U' R' U2' R U' R' U'"
  ],
  "f2l.35": [
    "F' U F U' R U' R' U"
  ],
  "f2l.36": [
    "R U' R' U2' F R' F' R U2'"
  ],
  "f2l.37": [
    "R U' R U2' F R2' F' U2' R2'"
  ],
  "f2l.38": [
    "R U' R' U R U2' R' U R U' R'"
  ],
  "f2l.39": [
    "R U' R' U' R U R' U2' R U' R'"
  ],
  "f2l.40": [
    "R U R' F U R U' R' F' R U R'"
  ],
  "f2l.41": [
    "R F U R U' R' F' U' R'"
  ]
};
